// frontend/src/react/components/AdministratorSecurityPanel.tsx
import { CopyOutlined, CheckOutlined, ReloadOutlined, SafetyCertificateOutlined } from "@ant-design/icons";
import { Alert, Button, Card, Checkbox, Descriptions, Flex, Form, Input, Modal, Space, Tag, Typography } from "antd";
import QRCode from "qrcode";
import { useEffect, useRef, useState } from "react";
import {
  administratorSecurity, beginAdministratorTotp, confirmAdministratorTotp, disableAdministratorTotp,
  regenerateAdministratorRecoveryCodes, updateAdministratorTotpPolicy,
  type AdministratorSecurity, type AdministratorTotpEnrollment,
} from "../../services/auth";
import { useAsyncScope } from "../hooks/useAsyncScope";

type Mode = "enroll" | "disable" | "recovery" | "policy";
export default function AdministratorSecurityPanel() {
  const readScope = useAsyncScope();
  const operationScope = useAsyncScope();
  const busyRef = useRef(false);
  const [security, setSecurity] = useState<AdministratorSecurity | null>(null);
  const [loading, setLoading] = useState(false);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const [dialogError, setDialogError] = useState("");
  const [mode, setMode] = useState<Mode | null>(null);
  const [password, setPassword] = useState("");
  const [code, setCode] = useState("");
  const [enrollment, setEnrollment] = useState<AdministratorTotpEnrollment | null>(null);
  const [qr, setQr] = useState("");
  const [recoveryCodes, setRecoveryCodes] = useState<string[]>([]);
  const [accepted, setAccepted] = useState(false);
  const [requiredTarget, setRequiredTarget] = useState(false);
  const [copied, setCopied] = useState(false);
  const title = ({ enroll: "Enable administrator two-factor authentication", disable: "Disable administrator two-factor authentication", recovery: "Generate new administrator recovery codes", policy: requiredTarget ? "Require administrator 2FA" : "Make administrator 2FA optional" })[mode ?? "enroll"];
  const canSubmit = !busy && !recoveryCodes.length && (enrollment ? Boolean(code.trim()) : Boolean(password)) && (!(enrollment || mode !== "enroll") || Boolean(code.trim()));

  async function load() {
    const current = readScope.begin(); setLoading(true); setError("");
    try {
      const result = await administratorSecurity();
      if (readScope.isCurrent(current)) setSecurity(result);
    } catch (cause) {
      if (readScope.isCurrent(current)) setError(cause instanceof Error ? cause.message : "Administrator security settings unavailable");
    } finally { if (readScope.isCurrent(current)) setLoading(false); }
  }
  useEffect(() => { void load(); }, []);
  function clearSecrets() {
    setPassword(""); setCode(""); setEnrollment(null); setQr(""); setRecoveryCodes([]); setAccepted(false); setCopied(false);
  }
  function open(selected: Mode, required = false) {
    if (busyRef.current) return;
    operationScope.invalidate(); clearSecrets(); setMode(selected); setRequiredTarget(required); setDialogError("");
  }
  function close() {
    if (busyRef.current || (recoveryCodes.length > 0 && !accepted)) return;
    operationScope.invalidate(); setMode(null); clearSecrets(); setDialogError("");
  }
  async function submit() {
    if (!mode || busyRef.current || !canSubmit) return;
    const current = operationScope.begin(); busyRef.current = true; setBusy(true); setDialogError("");
    try {
      if (mode === "enroll" && !enrollment) {
        const result = await beginAdministratorTotp(password);
        if (!operationScope.isCurrent(current)) return;
        setEnrollment(result); setPassword("");
        const image = await QRCode.toDataURL(result.provisioning_uri, { width: 240, margin: 1 });
        if (operationScope.isCurrent(current)) setQr(image);
        return;
      }
      let codes: string[] = [];
      if (mode === "enroll") codes = await confirmAdministratorTotp(code);
      else if (mode === "disable") await disableAdministratorTotp(password, code);
      else if (mode === "recovery") codes = await regenerateAdministratorRecoveryCodes(password, code);
      else {
        const result = await updateAdministratorTotpPolicy(requiredTarget, password, code);
        if (operationScope.isCurrent(current)) setSecurity(result);
      }
      if (!operationScope.isCurrent(current)) return;
      setRecoveryCodes(codes); setEnrollment(null); setQr("");
      if (!codes.length) setMode(null);
      await load();
    } catch (cause) {
      if (operationScope.isCurrent(current)) setDialogError(cause instanceof Error ? cause.message : "Security update failed");
    } finally {
      if (operationScope.isCurrent(current)) { setPassword(""); setCode(""); setBusy(false); busyRef.current = false; }
    }
  }
  async function copyCodes() {
    const current = operationScope.capture();
    try { await navigator.clipboard.writeText(recoveryCodes.join("\n")); if (operationScope.isCurrent(current)) setCopied(true); }
    catch { if (operationScope.isCurrent(current)) setDialogError("Could not copy recovery codes"); }
  }
  return <section aria-label="Administrator security">
    <Card title="Administrator security" extra={<Button icon={<ReloadOutlined aria-hidden />} aria-label="Refresh administrator security" loading={loading} onClick={() => void load()} />}>
      <Space orientation="vertical" size="middle" style={{ width: "100%" }}>
        <Typography.Paragraph type="secondary">Protect control-plane access with an authenticator and one-time recovery codes.</Typography.Paragraph>
        {error && <Alert type="error" showIcon title={error} />}
        {security && <>
          <Flex gap="middle" justify="space-between" wrap align="center">
            <Descriptions column={1} size="small" items={[
              { key: "totp", label: "Two-factor authentication", children: <Tag color={security.totp_enabled ? "success" : "default"}>{security.totp_enabled ? "Enabled" : "Not enabled"}</Tag> },
              ...(security.totp_enabled ? [{ key: "remaining", label: "Recovery", children: `${security.recovery_codes_remaining} recovery codes remaining` }] : []),
            ]} />
            <Space wrap>{security.totp_enabled ? <><Button onClick={() => open("recovery")}>New recovery codes</Button><Button danger disabled={security.require_totp} onClick={() => open("disable")}>Disable</Button></> : <Button type="primary" icon={<SafetyCertificateOutlined aria-hidden />} disabled={!security.totp_available} onClick={() => open("enroll")}>Enable</Button>}</Space>
          </Flex>
          {!security.totp_enabled && !security.totp_available && <Alert type="warning" showIcon title="Enrollment unavailable because the TOTP encryption key is not configured." />}
          <Flex gap="middle" justify="space-between" wrap align="center">
            <div><Typography.Text strong>Mandatory administrator 2FA</Typography.Text><Typography.Paragraph type="secondary">{security.require_totp ? "Every password login must complete a second-factor challenge." : "Administrators may sign in with a password when 2FA is not enrolled."}</Typography.Paragraph></div>
            <Button disabled={!security.totp_enabled} onClick={() => open("policy", !security.require_totp)}>{security.require_totp ? "Make optional" : "Require 2FA"}</Button>
          </Flex>
        </>}
      </Space>
    </Card>
    <Modal open={mode !== null} title={title} width={620} destroyOnHidden mask={{ closable: false }} keyboard={false} closable={false} onCancel={close} footer={<Space wrap>
      <Button disabled={busy || (recoveryCodes.length > 0 && !accepted)} onClick={close}>{recoveryCodes.length ? "Done" : "Cancel"}</Button>
      {!recoveryCodes.length && <Button type="primary" htmlType="submit" form="administrator-security-form" aria-label={mode === "enroll" && !enrollment ? "Start enrollment" : "Confirm"} loading={busy} disabled={!canSubmit}>{mode === "enroll" && !enrollment ? "Start enrollment" : "Confirm"}</Button>}
    </Space>}>
      {dialogError && <Alert className="form-alert" type="error" showIcon title={dialogError} />}
      {recoveryCodes.length ? <Space orientation="vertical" size="middle" style={{ width: "100%" }}>
        <Alert type="success" showIcon title="Store these codes now. Existing recovery codes no longer work." />
        <Flex justify="space-between" gap="small" wrap><Typography.Text strong>One-time recovery codes</Typography.Text><Button icon={copied ? <CheckOutlined aria-hidden /> : <CopyOutlined aria-hidden />} onClick={() => void copyCodes()}>{copied ? "Copied" : "Copy"}</Button></Flex>
        <div className="recovery-grid" aria-label="Administrator recovery codes">{recoveryCodes.map(item => <Typography.Text code key={item}>{item}</Typography.Text>)}</div>
        <Checkbox checked={accepted} onChange={event => setAccepted(event.target.checked)}>I have stored the recovery codes securely</Checkbox>
      </Space> : <Form id="administrator-security-form" layout="vertical" onFinish={() => void submit()}>
        {enrollment && <>
          <Alert className="form-alert" type="info" showIcon title="Scan the QR code, then enter the current six-digit code." />
          {qr && <img src={qr} alt="Administrator authenticator enrollment QR code" width={240} height={240} className="totp-qr" />}
          <Form.Item label="Authenticator secret" htmlFor="administrator-security-secret"><Input id="administrator-security-secret" readOnly value={enrollment.secret} /></Form.Item>
        </>}
        {mode === "disable" && <Alert className="form-alert" type="warning" showIcon title="Disabling 2FA removes all recovery codes. Other administrator sessions will be revoked." />}
        {mode === "recovery" && <Alert className="form-alert" type="warning" showIcon title="Generating new codes invalidates every existing recovery code and revokes other sessions." />}
        {mode === "policy" && <Alert className="form-alert" type="info" showIcon title="Confirm this policy change with the administrator password and a current authenticator or recovery code." />}
        {!enrollment && <Form.Item label="Current password" htmlFor="administrator-security-password" required><Input.Password id="administrator-security-password" value={password} onChange={event => setPassword(event.target.value)} autoComplete="current-password" required maxLength={1024} disabled={busy} /></Form.Item>}
        {(enrollment || mode !== "enroll") && <Form.Item label={enrollment ? "Authenticator code" : "Authenticator or recovery code"} htmlFor="administrator-security-code" required><Input id="administrator-security-code" value={code} onChange={event => setCode(event.target.value)} autoComplete="one-time-code" inputMode={enrollment ? "numeric" : "text"} required maxLength={64} disabled={busy} /></Form.Item>}
      </Form>}
    </Modal>
  </section>;
}

// frontend/src/components/AdministratorSecurityPanel.vue
<script setup lang="ts">
import QRCode from "qrcode";
import { computed, onMounted, ref } from "vue";
import {
  administratorSecurity,
  beginAdministratorTotp,
  confirmAdministratorTotp,
  disableAdministratorTotp,
  regenerateAdministratorRecoveryCodes,
  updateAdministratorTotpPolicy,
  type AdministratorSecurity,
  type AdministratorTotpEnrollment,
} from "../services/auth";

type Mode = "enroll" | "disable" | "recovery" | "policy";

const security = ref<AdministratorSecurity | null>(null);
const loading = ref(false);
const busy = ref(false);
const error = ref("");
const mode = ref<Mode | null>(null);
const password = ref("");
const code = ref("");
const enrollment = ref<AdministratorTotpEnrollment | null>(null);
const qr = ref("");
const recoveryCodes = ref<string[]>([]);
const accepted = ref(false);
const requiredTarget = ref(false);
const copied = ref(false);

const title = computed(() => ({
  enroll: "Enable administrator two-factor authentication",
  disable: "Disable administrator two-factor authentication",
  recovery: "Generate new administrator recovery codes",
  policy: requiredTarget.value ? "Require administrator 2FA" : "Make administrator 2FA optional",
})[mode.value ?? "enroll"]);

async function load() {
  loading.value = true;
  error.value = "";
  try {
    security.value = await administratorSecurity();
  } catch (cause) {
    error.value = cause instanceof Error ? cause.message : "Administrator security settings unavailable";
  } finally {
    loading.value = false;
  }
}

function open(selected: Mode, required = false) {
  mode.value = selected;
  requiredTarget.value = required;
  password.value = "";
  code.value = "";
  enrollment.value = null;
  qr.value = "";
  recoveryCodes.value = [];
  accepted.value = false;
  copied.value = false;
  error.value = "";
}

function close() {
  if (recoveryCodes.value.length && !accepted.value) return;
  mode.value = null;
  password.value = "";
  code.value = "";
  enrollment.value = null;
  qr.value = "";
  recoveryCodes.value = [];
}

async function submit() {
  if (!mode.value || busy.value) return;
  busy.value = true;
  error.value = "";
  try {
    if (mode.value === "enroll" && !enrollment.value) {
      enrollment.value = await beginAdministratorTotp(password.value);
      qr.value = await QRCode.toDataURL(enrollment.value.provisioning_uri, { width: 240, margin: 1 });
      password.value = "";
      return;
    }
    if (mode.value === "enroll") {
      recoveryCodes.value = await confirmAdministratorTotp(code.value);
    } else if (mode.value === "disable") {
      await disableAdministratorTotp(password.value, code.value);
    } else if (mode.value === "recovery") {
      recoveryCodes.value = await regenerateAdministratorRecoveryCodes(password.value, code.value);
    } else {
      security.value = await updateAdministratorTotpPolicy(
        requiredTarget.value, password.value, code.value,
      );
    }
    await load();
    if (!recoveryCodes.value.length) mode.value = null;
  } catch (cause) {
    error.value = cause instanceof Error ? cause.message : "Security update failed";
  } finally {
    code.value = "";
    if (mode.value !== "enroll" || !enrollment.value) password.value = "";
    busy.value = false;
  }
}

async function copyCodes() {
  try {
    await navigator.clipboard.writeText(recoveryCodes.value.join("\n"));
    copied.value = true;
  } catch {
    error.value = "Could not copy recovery codes";
  }
}

onMounted(load);
</script>

<template>
  <section class="administrator-security" aria-label="Administrator security">
    <header class="security-heading">
      <div>
        <h2 class="section-title">Administrator security</h2>
        <p>Protect control-plane access with an authenticator and one-time recovery codes.</p>
      </div>
      <v-btn icon="mdi-refresh" aria-label="Refresh administrator security" variant="text" :loading="loading" @click="load" />
    </header>
    <v-alert v-if="error && !mode" type="error" variant="tonal">{{ error }}</v-alert>
    <template v-if="security">
      <div class="security-row">
        <div>
          <h3>Two-factor authentication</h3>
          <p>{{ security.totp_enabled ? "Enabled" : "Not enabled" }}</p>
          <p v-if="security.totp_enabled">{{ security.recovery_codes_remaining }} recovery codes remaining</p>
          <p v-else-if="!security.totp_available">Enrollment unavailable because the TOTP encryption key is not configured.</p>
        </div>
        <div class="security-actions">
          <template v-if="security.totp_enabled">
            <v-btn variant="text" prepend-icon="mdi-key-change" @click="open('recovery')">New recovery codes</v-btn>
            <v-btn variant="text" color="error" prepend-icon="mdi-shield-off-outline" :disabled="security.require_totp" @click="open('disable')">Disable</v-btn>
          </template>
          <v-btn v-else color="primary" variant="tonal" prepend-icon="mdi-shield-plus-outline" :disabled="!security.totp_available" @click="open('enroll')">Enable</v-btn>
        </div>
      </div>
      <div class="security-row">
        <div>
          <h3>Mandatory administrator 2FA</h3>
          <p>{{ security.require_totp ? "Every password login must complete a second-factor challenge." : "Administrators may sign in with a password when 2FA is not enrolled." }}</p>
        </div>
        <v-btn variant="text" :color="security.require_totp ? 'warning' : 'primary'" :disabled="!security.totp_enabled" @click="open('policy', !security.require_totp)">
          {{ security.require_totp ? "Make optional" : "Require 2FA" }}
        </v-btn>
      </div>
    </template>

    <v-dialog :model-value="!!mode" max-width="620" persistent>
      <v-card>
        <v-card-title>{{ title }}</v-card-title>
        <v-card-text class="security-dialog">
          <v-alert v-if="error" type="error" variant="tonal">{{ error }}</v-alert>
          <template v-if="recoveryCodes.length">
            <v-alert type="success" variant="tonal">Store these codes now. Existing recovery codes no longer work.</v-alert>
            <div class="recovery-heading">
              <strong>One-time recovery codes</strong>
              <v-btn variant="text" :prepend-icon="copied ? 'mdi-check' : 'mdi-content-copy'" @click="copyCodes">{{ copied ? "Copied" : "Copy" }}</v-btn>
            </div>
            <div class="recovery-grid"><code v-for="item in recoveryCodes" :key="item">{{ item }}</code></div>
            <v-checkbox v-model="accepted" label="I have stored the recovery codes securely" hide-details />
          </template>
          <template v-else>
            <template v-if="enrollment">
              <v-alert type="info" variant="tonal">Scan the QR code, then enter the current six-digit code.</v-alert>
              <img v-if="qr" :src="qr" alt="Administrator authenticator enrollment QR code" width="240" height="240" class="totp-qr" />
              <v-text-field :model-value="enrollment.secret" label="Authenticator secret" readonly />
            </template>
            <v-alert v-if="mode === 'disable'" type="warning" variant="tonal">Disabling 2FA removes all recovery codes. Other administrator sessions will be revoked.</v-alert>
            <v-alert v-if="mode === 'recovery'" type="warning" variant="tonal">Generating new codes invalidates every existing recovery code and revokes other sessions.</v-alert>
            <v-alert v-if="mode === 'policy'" type="info" variant="tonal">Confirm this policy change with the administrator password and a current authenticator or recovery code.</v-alert>
            <v-text-field v-if="!enrollment" v-model="password" label="Current password" type="password" autocomplete="current-password" required maxlength="1024" :disabled="busy" />
            <v-text-field v-if="enrollment || mode !== 'enroll'" v-model="code" label="Authenticator or recovery code" autocomplete="one-time-code" :inputmode="enrollment ? 'numeric' : 'text'" required maxlength="64" :disabled="busy" />
          </template>
        </v-card-text>
        <v-card-actions>
          <v-spacer />
          <v-btn variant="text" :disabled="busy || (recoveryCodes.length > 0 && !accepted)" @click="close">{{ recoveryCodes.length ? "Done" : "Cancel" }}</v-btn>
          <v-btn v-if="!recoveryCodes.length" color="primary" :loading="busy" :disabled="(!enrollment && !password) || ((enrollment || mode !== 'enroll') && !code)" @click="submit">
            {{ mode === "enroll" && !enrollment ? "Start enrollment" : "Confirm" }}
          </v-btn>
        </v-card-actions>
      </v-card>
    </v-dialog>
  </section>
</template>

<style scoped>
.administrator-security { border-top: 1px solid #dfe5e2; display: grid; gap: 14px; max-width: 760px; min-width: 0; padding-top: 16px; }
.security-heading, .security-row, .recovery-heading { align-items: center; display: flex; justify-content: space-between; gap: 16px; }
.security-heading p, .security-row p { color: #607069; margin: 4px 0 0; }
.security-row { border: 1px solid #dfe5e2; border-radius: 12px; padding: 14px; }
.security-row h3 { font-size: 15px; margin: 0; }
.security-actions { display: flex; flex-wrap: wrap; justify-content: flex-end; }
.security-dialog { display: grid; gap: 14px; }
.totp-qr { justify-self: center; max-width: 100%; height: auto; aspect-ratio: 1; }
.recovery-grid { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 8px 16px; }
.recovery-grid code { overflow-wrap: anywhere; }
@media (max-width: 640px) {
  .security-heading, .security-row { align-items: stretch; flex-direction: column; }
  .security-actions { justify-content: flex-start; }
  .recovery-grid { grid-template-columns: minmax(0, 1fr); }
}
</style>
