// frontend/src/react/components/NodeManagementDialog.tsx
import { useEffect, useRef, useState } from "react";
import { Alert, Button, Card, Checkbox, Descriptions, Flex, Form, Input, Modal, Select, Spin, Switch, Tag, Typography } from "antd";
import { ReloadOutlined, SyncOutlined } from "@ant-design/icons";
import type { ManagedNode, SubscriptionAccessResponse } from "../../domain/subscriptions";
import { getSubscriptionAccess, syncSubscriptionAccess } from "../../services/subscriptions";
import { getNodeManagement, getNodeRemoval, nodeSettings, parseNodeObject, removeNode, retryNodeRemoval, saveNode, type NodeManagementRead, type NodeOperation, type NodeRemoval, type NodeSettings } from "../../services/node-management";

export interface NodeManagementDialogProps { id: string; mode: NodeOperation; open: boolean; nodes: ManagedNode[]; onOpenChange: (open: boolean) => void; onUpdated?: () => void }
export default function NodeManagementDialog(props: NodeManagementDialogProps) { return props.open ? <NodeContent key={`${props.id}:${props.mode}`} {...props} /> : null; }
function NodeContent({ id, mode, nodes, onOpenChange, onUpdated }: NodeManagementDialogProps) {
  const [detail, setDetail] = useState<NodeManagementRead | null>(null), [form, setForm] = useState<NodeSettings | null>(null);
  const [removal, setRemoval] = useState<NodeRemoval | null>(null), [access, setAccess] = useState<SubscriptionAccessResponse[]>([]);
  const [config, setConfig] = useState("{}"), [clientTemplate, setClientTemplate] = useState("{}");
  const [busy, setBusy] = useState(false), [syncing, setSyncing] = useState(false), [saved, setSaved] = useState(false);
  const [error, setError] = useState(""), [statusError, setStatusError] = useState(""), [confirmName, setConfirmName] = useState("");
  const [acknowledged, setAcknowledged] = useState(false), [unmanaged, setUnmanaged] = useState(false);
  const version = useRef(0), pollVersion = useRef(0), timer = useRef<ReturnType<typeof setTimeout> | undefined>(undefined);
  const removalRef = useRef<NodeRemoval | null>(null), accessRef = useRef<SubscriptionAccessResponse[]>([]), completed = useRef(false);
  const updated = useRef(onUpdated); updated.current = onUpdated;
  function stop() { clearTimeout(timer.current); ++pollVersion.current; }
  function acceptAccess(value: SubscriptionAccessResponse[]) { accessRef.current = value; setAccess(value); }
  function acceptRemoval(value: NodeRemoval) {
    removalRef.current = value; setRemoval(value);
    if (value.status === "completed" && !completed.current) { completed.current = true; updated.current?.(); }
  }
  async function poll(run: number, retry = false) {
    clearTimeout(timer.current); const current = ++pollVersion.current; setSyncing(retry);
    try {
      if (removalRef.current) {
        const value = await (retry ? retryNodeRemoval : getNodeRemoval)(removalRef.current.id);
        if (run !== version.current || current !== pollVersion.current) return; acceptRemoval(value);
      } else {
        const values = await Promise.all(accessRef.current.map(user => (retry ? syncSubscriptionAccess : getSubscriptionAccess)(user.username)));
        if (run !== version.current || current !== pollVersion.current) return; acceptAccess(values);
      }
      setStatusError("");
    } catch (failure) { if (run === version.current && current === pollVersion.current) setStatusError(failure instanceof Error ? failure.message : "Node status unavailable"); }
    finally { if (run === version.current && current === pollVersion.current) { setSyncing(false); if (!completed.current) timer.current = setTimeout(() => void poll(run), 5000); } }
  }
  async function load() {
    const run = ++version.current; stop(); removalRef.current = null; completed.current = false;
    setDetail(null); setForm(null); setRemoval(null); acceptAccess([]); setSaved(false); setError(""); setStatusError(""); setConfirmName(""); setAcknowledged(false); setUnmanaged(false); setSyncing(false); setBusy(true);
    try {
      const value = await getNodeManagement(id); if (run !== version.current) return;
      setDetail(value); setForm(nodeSettings(value.node)); acceptAccess(value.access);
      setConfig(JSON.stringify(value.node.config, null, 2)); setClientTemplate(JSON.stringify(value.node.client_template, null, 2));
      if (value.node.removal_id) { const job = await getNodeRemoval(value.node.removal_id); if (run !== version.current) return; acceptRemoval(job); }
      if (!completed.current) timer.current = setTimeout(() => void poll(run), 5000);
    } catch (failure) { if (run === version.current) setError(failure instanceof Error ? failure.message : "Node request failed"); }
    finally { if (run === version.current) setBusy(false); }
  }
  useEffect(() => { void load(); return () => { ++version.current; stop(); }; }, []);
  const warnings = removal?.warnings ?? detail?.warnings ?? [], selectable = nodes.filter(node => node.id !== id && !node.removal_id);
  const parents = selectable.filter(node => node.server_id === detail?.node.server_id && node.inbound_tag === detail?.node.inbound_tag && node.protocol === detail?.node.protocol);
  const canSubmit = !busy && !!form && !!detail && !removal && acknowledged && (mode === "edit" ? !!form.name.trim() : !detail.blockers.length && confirmName === detail.node.name && (!warnings.length || unmanaged));
  async function submit() {
    if (!canSubmit || !detail || !form) return;
    const run = ++version.current; stop(); setSyncing(false); setBusy(true); setError("");
    try {
      if (mode === "edit") {
        const value = await saveNode(id, { ...form, config: parseNodeObject(config, "Node config"), client_template: parseNodeObject(clientTemplate, "Client template") }, detail.revision);
        if (run !== version.current) return;
        setDetail(value); setForm(nodeSettings(value.node)); acceptAccess(value.access); setSaved(true); updated.current?.();
      } else {
        const value = await removeNode(id, detail.revision, confirmName, unmanaged); if (run !== version.current) return; acceptRemoval(value); updated.current?.();
      }
      setAcknowledged(false); if (!completed.current) void poll(run);
    } catch (failure) { if (run === version.current) setError(failure instanceof Error ? failure.message : "Node update failed"); }
    finally { if (run === version.current) setBusy(false); }
  }
  function patch(change: Partial<NodeSettings>) { setForm(previous => previous ? { ...previous, ...change } : previous); }
  return <Modal open title={removal ? "Node removal" : mode === "edit" ? "Edit node" : "Remove node"} width={760} centered styles={{ body: { maxHeight: "calc(100dvh - 200px)", overflowY: "auto" } }} destroyOnHidden mask={{ closable: !busy }} keyboard={!busy} closable={!busy} onCancel={() => !busy && onOpenChange(false)}
    footer={<Flex justify="space-between"><Button disabled={busy} onClick={() => onOpenChange(false)}>{saved || removal ? "Close" : "Cancel"}</Button>{!removal && <Button type="primary" aria-label={mode === "edit" ? "Save" : "Remove"} aria-busy={busy} danger={mode === "remove"} disabled={!canSubmit} loading={busy} onClick={() => void submit()}>{mode === "edit" ? "Save" : "Remove"}</Button>}</Flex>}>
    <Flex vertical gap="middle">
      <Flex justify="space-between" align="center"><Typography.Text strong>{detail?.node.name ?? removal?.name}</Typography.Text>{detail && <Tag>{detail.node.protocol} / {detail.node.node_type}</Tag>}<Button aria-label="Reload node details" icon={<ReloadOutlined />} disabled={busy || completed.current} onClick={() => void (removal ? poll(version.current) : load())} /></Flex>
      {busy && <Spin />}{error && <Alert type="error" title={error} showIcon />}{saved && <Alert type="success" title="Node saved" showIcon />}
      {removal && <Alert type={removal.status === "completed" ? "success" : removal.status === "failed" ? "error" : "info"} title={removal.status === "completed" ? "Node removed" : removal.status === "failed" ? "Removal needs attention" : "Removal pending Agent confirmation"} showIcon />}
      {detail && form && !removal && (mode === "edit" ? <Form layout="vertical" preserve={false} disabled={busy}>
        <Form.Item label="Node name"><Input aria-label="Node name" maxLength={120} value={form.name} onChange={event => patch({ name: event.target.value })} /></Form.Item>
        <Form.Item label="Primary tag"><Input aria-label="Primary tag" maxLength={120} value={form.tag ?? ""} onChange={event => patch({ tag: event.target.value || null })} /></Form.Item>
        <Form.Item label="Tags"><Select aria-label="Tags" mode="tags" value={form.tags} onChange={tags => patch({ tags })} options={form.tags.map(value => ({ label: value, value }))} /></Form.Item>
        {detail.node.node_type === "routed" && <>
          <Form.Item label="Parent node"><Select aria-label="Parent node" allowClear value={form.parent_id ?? undefined} onChange={parent_id => patch({ parent_id: parent_id ?? null })} options={parents.map(node => ({ label: node.name, value: node.id }))} /></Form.Item>
          <Form.Item label="Target node"><Select aria-label="Target node" allowClear value={form.target_node_id ?? undefined} onChange={target_node_id => patch({ target_node_id: target_node_id ?? null })} options={selectable.map(node => ({ label: node.name, value: node.id }))} /></Form.Item>
        </>}
        <Form.Item label="Node config"><Input.TextArea aria-label="Node config" rows={5} value={config} onChange={event => setConfig(event.target.value)} /></Form.Item>
        <Form.Item label="Client template"><Input.TextArea aria-label="Client template" rows={4} value={clientTemplate} onChange={event => setClientTemplate(event.target.value)} /></Form.Item>
        <Form.Item label="Enabled"><Switch aria-label="Enabled" checked={form.enabled} onChange={enabled => patch({ enabled })} /></Form.Item>
      </Form> : <>
        <Typography.Text>{detail.nodes.length} nodes / {detail.plans.length} plans / {detail.credential_count} credentials</Typography.Text>
        <section aria-label="Affected nodes"><Typography.Title level={5}>Nodes</Typography.Title>{detail.nodes.map(node => <Typography.Paragraph key={node.id}>{node.name}</Typography.Paragraph>)}</section>
        {!!detail.plans.length && <section aria-label="Affected plans"><Typography.Title level={5}>Plans</Typography.Title>{detail.plans.map(plan => <Typography.Paragraph key={plan.id}>{plan.name}</Typography.Paragraph>)}</section>}
        {detail.blockers.map(blocker => <Alert key={blocker} type="error" title={blocker} showIcon />)}
        <Alert type="warning" title="Selected nodes leave subscriptions immediately. Remote resources remain until the Agent confirms cleanup. Shared listeners, subscriber accounts, links and charged traffic are retained. Removal cannot be cancelled." showIcon />
        <Form.Item label="Confirm node name"><Input aria-label="Confirm node name" value={confirmName} disabled={busy} onChange={event => setConfirmName(event.target.value)} /></Form.Item>
      </>)}
      {(removal || (detail && mode === "remove")) && <section aria-label="Node resource cleanup"><Flex justify="space-between"><Typography.Title level={5}>Remote resources</Typography.Title>{removal && <Button icon={<SyncOutlined />} aria-label="Retry node removal" loading={syncing} disabled={busy || completed.current} onClick={() => void poll(version.current, true)} />}</Flex>
        {(removal?.servers ?? detail?.servers ?? []).map(server => <Card key={server.server_id} size="small" title={server.server_name} extra={removal && <Tag color={server.error ? "error" : server.phase === "completed" ? "success" : "warning"}>{server.error ? "Failed" : server.phase}</Tag>}>
          <Descriptions column={1} size="small" items={[
            { key: "in", label: "Remove inbounds", children: server.inbound_tags.join(", ") || "None" }, { key: "out", label: "Remove outbounds", children: server.outbound_tags.join(", ") || "None" },
            { key: "keep-in", label: "Keep shared inbounds", children: server.retained_inbound_tags.join(", ") || "None" }, { key: "keep-out", label: "Keep shared outbounds", children: server.retained_outbound_tags.join(", ") || "None" },
          ]} />{server.error && <Alert type="error" title={server.error} showIcon />}
        </Card>)}
      </section>}
      {warnings.map(warning => <Alert key={warning} type="warning" title={warning} showIcon />)}
      {detail && !removal && <>{mode === "remove" && !!warnings.length && <Checkbox checked={unmanaged} disabled={busy} onChange={event => setUnmanaged(event.target.checked)}>I accept responsibility for unmanaged resources</Checkbox>}<Checkbox checked={acknowledged} disabled={busy} onChange={event => setAcknowledged(event.target.checked)}>I accept Xray restarts, disconnected clients and pending remote changes</Checkbox></>}
      {!removal && !!access.length && <section aria-label="Node subscription access"><Flex justify="space-between"><Typography.Title level={5}>Subscription access</Typography.Title><Button icon={<SyncOutlined />} aria-label="Retry node access synchronization" loading={syncing} disabled={busy} onClick={() => void poll(version.current, true)} /></Flex>
        {access.map(user => <Card size="small" key={user.username} title={user.username}>{user.servers.map(server => <Flex key={server.server_id} justify="space-between" wrap><span>{server.server_name}</span><Tag color={server.status === "applied" ? "success" : server.status === "failed" ? "error" : "warning"}>{server.status}</Tag>{server.error && <Alert type="error" title={server.error} showIcon />}</Flex>)}</Card>)}
      </section>}{statusError && <Alert type="error" title={statusError} showIcon />}
    </Flex>
  </Modal>;
}

// frontend/src/components/NodeManagementDialog.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, ref, watch } from "vue";
import type { ManagedNode, SubscriptionAccessResponse } from "../domain/subscriptions";
import { getSubscriptionAccess, syncSubscriptionAccess } from "../services/subscriptions";
import {
  getNodeManagement, getNodeRemoval, nodeSettings, parseNodeObject, removeNode, retryNodeRemoval, saveNode,
  type NodeManagementRead, type NodeOperation, type NodeRemoval, type NodeSettings,
} from "../services/node-management";

const props = defineProps<{ id: string; mode: NodeOperation; open: boolean; nodes: ManagedNode[] }>();
const emit = defineEmits<{ "update:open": [value: boolean]; changed: [] }>();
const detail = ref<NodeManagementRead | null>(null);
const form = ref<NodeSettings | null>(null);
const removal = ref<NodeRemoval | null>(null);
const access = ref<SubscriptionAccessResponse[]>([]);
const config = ref("{}");
const clientTemplate = ref("{}");
const error = ref("");
const statusError = ref("");
const busy = ref(false);
const syncing = ref(false);
const saved = ref(false);
const confirmName = ref("");
const acknowledged = ref(false);
const unmanaged = ref(false);
const completed = ref(false);
let version = 0;
let pollVersion = 0;
let timer: ReturnType<typeof setTimeout> | undefined;
const title = computed(() => removal.value ? "Node removal" : props.mode === "edit" ? "Edit node" : "Remove node");
const name = computed(() => detail.value?.node.name ?? removal.value?.name ?? "");
const warnings = computed(() => removal.value?.warnings ?? detail.value?.warnings ?? []);
const selectable = computed(() => props.nodes.filter(node => node.id !== props.id && !node.removal_id));
const parents = computed(() => selectable.value.filter(node => node.server_id === detail.value?.node.server_id && node.inbound_tag === detail.value.node.inbound_tag && node.protocol === detail.value.node.protocol));
const canSubmit = computed(() => !busy.value && !!form.value && !!detail.value && !removal.value && acknowledged.value
  && (props.mode === "edit" ? !!form.value.name.trim()
    : !detail.value.blockers.length && confirmName.value === detail.value.node.name && (!warnings.value.length || unmanaged.value)));

function stopPolling() { clearTimeout(timer); ++pollVersion; syncing.value = false; }
function acceptRemoval(value: NodeRemoval) {
  removal.value = value;
  if (value.status === "completed" && !completed.value) { completed.value = true; emit("changed"); }
}
async function poll(request: number, retry = false) {
  clearTimeout(timer);
  const current = ++pollVersion;
  syncing.value = retry;
  try {
    if (removal.value) {
      const value = await (retry ? retryNodeRemoval : getNodeRemoval)(removal.value.id);
      if (request !== version || current !== pollVersion) return;
      acceptRemoval(value);
    } else {
      const values: SubscriptionAccessResponse[] = [];
      for (const user of access.value) values.push(await (retry ? syncSubscriptionAccess : getSubscriptionAccess)(user.username));
      if (request !== version || current !== pollVersion) return;
      access.value = values;
    }
    statusError.value = "";
  } catch (failure) {
    if (request === version && current === pollVersion) statusError.value = failure instanceof Error ? failure.message : "Node status unavailable";
  } finally {
    if (request === version && current === pollVersion) {
      syncing.value = false;
      if (props.open && !completed.value) timer = setTimeout(() => void poll(request), 5000);
    }
  }
}
async function load() {
  const request = ++version;
  stopPolling();
  detail.value = null; form.value = null; removal.value = null; access.value = [];
  saved.value = false; completed.value = false; error.value = ""; statusError.value = "";
  confirmName.value = ""; acknowledged.value = false; unmanaged.value = false; busy.value = false;
  if (!props.open || !props.id) return;
  busy.value = true;
  try {
    const value = await getNodeManagement(props.id);
    if (request !== version) return;
    detail.value = value; form.value = nodeSettings(value.node); access.value = value.access;
    config.value = JSON.stringify(value.node.config, null, 2);
    clientTemplate.value = JSON.stringify(value.node.client_template, null, 2);
    if (value.node.removal_id) {
      const job = await getNodeRemoval(value.node.removal_id);
      if (request !== version) return;
      acceptRemoval(job);
    }
    if (!completed.value) timer = setTimeout(() => void poll(request), 5000);
  } catch (failure) {
    if (request === version) error.value = failure instanceof Error ? failure.message : "Node request failed";
  } finally { if (request === version) busy.value = false; }
}
async function submit() {
  if (!canSubmit.value || !detail.value || !form.value) return;
  const request = ++version;
  stopPolling(); busy.value = true; error.value = "";
  try {
    if (props.mode === "edit") {
      const value = await saveNode(props.id, {
        ...form.value, config: parseNodeObject(config.value, "Node config"),
        client_template: parseNodeObject(clientTemplate.value, "Client template"),
      }, detail.value.revision);
      emit("changed");
      if (request !== version) return;
      detail.value = value; form.value = nodeSettings(value.node); access.value = value.access; saved.value = true;
    } else {
      const value = await removeNode(props.id, detail.value.revision, confirmName.value, unmanaged.value);
      emit("changed");
      if (request !== version) return;
      acceptRemoval(value);
    }
    acknowledged.value = false;
    if (!completed.value) void poll(request);
  } catch (failure) {
    if (request === version) error.value = failure instanceof Error ? failure.message : "Node update failed";
  } finally { if (request === version) busy.value = false; }
}
watch(() => [props.open, props.id, props.mode], () => void load(), { immediate: true });
onBeforeUnmount(() => { ++version; stopPolling(); });
</script>

<template>
  <v-dialog :model-value="open" :persistent="busy" max-width="760" scrollable @update:model-value="emit('update:open', $event)">
    <v-card class="node-management-dialog">
      <v-card-title class="node-toolbar">
        <span>{{ title }}</span>
        <v-tooltip text="Reload node details"><template #activator="{ props: tip }"><v-btn v-bind="tip" aria-label="Reload node details" icon="mdi-refresh" variant="text" size="small" :disabled="busy || completed" @click="removal ? poll(version) : load()" /></template></v-tooltip>
      </v-card-title>
      <v-card-text>
        <v-progress-linear v-if="busy" indeterminate color="primary" class="mb-4" />
        <v-alert v-if="error" type="error" variant="tonal" class="mb-4">{{ error }}</v-alert>
        <div class="node-heading"><strong>{{ name }}</strong><v-chip v-if="detail" size="small" variant="tonal">{{ detail.node.protocol }} / {{ detail.node.node_type }}</v-chip></div>
        <v-alert v-if="saved" type="success" variant="tonal" class="my-4">Node saved</v-alert>
        <v-alert v-if="removal" :type="completed ? 'success' : removal.status === 'failed' ? 'error' : 'info'" variant="tonal" class="my-4">{{ completed ? 'Node removed' : removal.status === 'failed' ? 'Removal needs attention' : 'Removal pending Agent confirmation' }}</v-alert>
        <template v-if="detail && form && !removal">
          <div v-if="mode === 'edit'" class="node-form">
            <v-text-field v-model="form.name" label="Node name" maxlength="120" variant="outlined" density="compact" hide-details :disabled="busy" />
            <v-text-field v-model="form.tag" label="Primary tag" maxlength="120" variant="outlined" density="compact" hide-details :disabled="busy" />
            <v-combobox v-model="form.tags" label="Tags" chips multiple closable-chips variant="outlined" density="compact" hide-details :disabled="busy" />
            <template v-if="detail.node.node_type === 'routed'">
              <v-select v-model="form.parent_id" label="Parent node" :items="parents" item-title="name" item-value="id" clearable variant="outlined" density="compact" hide-details :disabled="busy" />
              <v-select v-model="form.target_node_id" label="Target node" :items="selectable" item-title="name" item-value="id" clearable variant="outlined" density="compact" hide-details :disabled="busy" />
            </template>
            <v-textarea v-model="config" label="Node config" rows="5" class="node-json" variant="outlined" density="compact" hide-details :disabled="busy" />
            <v-textarea v-model="clientTemplate" label="Client template" rows="4" class="node-json" variant="outlined" density="compact" hide-details :disabled="busy" />
            <v-switch v-model="form.enabled" label="Enabled" color="primary" hide-details :disabled="busy" />
          </div>
          <template v-else>
            <div class="node-impact">{{ detail.nodes.length }} nodes / {{ detail.plans.length }} plans / {{ detail.credential_count }} credentials</div>
            <section class="node-section" aria-label="Affected nodes"><h3>Nodes</h3><p v-for="node in detail.nodes" :key="node.id">{{ node.name }}</p></section>
            <section v-if="detail.plans.length" class="node-section" aria-label="Affected plans"><h3>Plans</h3><p v-for="plan in detail.plans" :key="plan.id">{{ plan.name }}</p></section>
            <v-alert v-for="blocker in detail.blockers" :key="blocker" type="error" variant="tonal" class="my-4">{{ blocker }}</v-alert>
            <v-alert type="warning" variant="tonal" class="my-4">Selected nodes leave subscriptions immediately. Remote resources remain until the Agent confirms cleanup. Shared listeners, subscriber accounts, links and charged traffic are retained. Removal cannot be cancelled.</v-alert>
            <v-text-field v-model="confirmName" label="Confirm node name" variant="outlined" density="compact" hide-details :disabled="busy" />
          </template>
        </template>
        <section v-if="removal || (detail && mode === 'remove')" class="node-section" aria-label="Node resource cleanup">
          <div class="node-heading"><h3>Remote resources</h3><v-tooltip v-if="removal" text="Retry node removal"><template #activator="{ props: tip }"><v-btn v-bind="tip" aria-label="Retry node removal" icon="mdi-sync" size="small" variant="text" :loading="syncing" :disabled="busy || completed" @click="poll(version, true)" /></template></v-tooltip></div>
          <div v-for="server in removal?.servers ?? detail?.servers ?? []" :key="server.server_id" class="node-server">
            <div class="node-heading"><strong>{{ server.server_name }}</strong><v-chip v-if="removal" :color="server.error ? 'error' : server.phase === 'completed' ? 'success' : 'warning'" variant="tonal" size="small">{{ server.error ? 'Failed' : server.phase }}</v-chip></div>
            <dl class="node-resources">
              <dt>Remove inbounds</dt><dd>{{ server.inbound_tags.join(', ') || 'None' }}</dd>
              <dt>Remove outbounds</dt><dd>{{ server.outbound_tags.join(', ') || 'None' }}</dd>
              <dt>Keep shared inbounds</dt><dd>{{ server.retained_inbound_tags.join(', ') || 'None' }}</dd>
              <dt>Keep shared outbounds</dt><dd>{{ server.retained_outbound_tags.join(', ') || 'None' }}</dd>
            </dl>
            <p v-if="server.error" class="text-error">{{ server.error }}</p>
          </div>
        </section>
        <v-alert v-for="warning in warnings" :key="warning" type="warning" variant="tonal" class="my-4">{{ warning }}</v-alert>
        <template v-if="detail && !removal">
          <v-checkbox v-if="mode === 'remove' && warnings.length" v-model="unmanaged" label="I accept responsibility for unmanaged resources" hide-details :disabled="busy" />
          <v-checkbox v-model="acknowledged" label="I accept Xray restarts, disconnected clients and pending remote changes" hide-details :disabled="busy" />
        </template>
        <section v-if="!removal && access.length" class="node-section" aria-label="Node subscription access">
          <div class="node-heading"><h3>Subscription access</h3><v-tooltip text="Retry access synchronization"><template #activator="{ props: tip }"><v-btn v-bind="tip" aria-label="Retry node access synchronization" icon="mdi-sync" variant="text" size="small" :loading="syncing" :disabled="busy" @click="poll(version, true)" /></template></v-tooltip></div>
          <div v-for="user in access" :key="user.username" class="node-server">
            <strong>{{ user.username }}</strong>
            <div v-for="server in user.servers" :key="server.server_id" class="node-heading">
              <span>{{ server.server_name }}</span><v-chip size="small" variant="tonal" :color="server.status === 'applied' ? 'success' : server.status === 'failed' ? 'error' : 'warning'">{{ server.status }}</v-chip>
              <p v-if="server.error" class="text-error">{{ server.error }}</p>
            </div>
          </div>
        </section>
        <p v-if="statusError" class="text-error">{{ statusError }}</p>
      </v-card-text>
      <v-card-actions>
        <v-btn :disabled="busy" @click="emit('update:open', false)">{{ saved || removal ? 'Close' : 'Cancel' }}</v-btn>
        <v-spacer />
        <v-btn v-if="!removal" :prepend-icon="mode === 'edit' ? 'mdi-content-save' : 'mdi-delete-outline'" :color="mode === 'edit' ? 'primary' : 'error'" :disabled="!canSubmit" @click="submit">{{ mode === 'edit' ? 'Save' : 'Remove' }}</v-btn>
      </v-card-actions>
    </v-card>
  </v-dialog>
</template>

<style scoped>
.node-management-dialog, .node-management-dialog :deep(*) { letter-spacing: 0; }
.node-management-dialog :deep(.v-label) { white-space: normal; }
.node-management-dialog :deep(.v-alert__content) { font-size: 14px; line-height: 1.5; overflow-wrap: anywhere; }
.node-toolbar { display: grid; grid-template-columns: minmax(0, 1fr) 36px; align-items: center; gap: 12px; font-size: 18px; white-space: normal; }
.node-heading { display: flex; align-items: center; justify-content: space-between; flex-wrap: wrap; gap: 10px; overflow-wrap: anywhere; }
.node-form { display: grid; gap: 16px; margin-top: 20px; min-width: 0; }
.node-json :deep(textarea) { font: 12px/1.6 monospace; }
.node-impact { margin-top: 16px; font-size: 13px; }
.node-section { margin-top: 20px; font-size: 13px; }
.node-section h3 { font-size: 14px; }
.node-section p { margin-top: 8px; overflow-wrap: anywhere; }
.node-server { border-top: 1px solid rgb(var(--v-theme-on-surface), .12); padding-block: 12px; margin-top: 10px; }
.node-resources { display: grid; grid-template-columns: minmax(0, 1fr) minmax(0, 1.2fr); gap: 8px 14px; margin-top: 14px; overflow-wrap: anywhere; }
.node-resources dt { color: rgb(var(--v-theme-on-surface), .7); }
</style>
