// frontend/src/react/components/PlanNodeAliases.tsx
import { useEffect, type ReactNode } from "react";
import { Card, Flex, Form, Input, Switch, Typography } from "antd";
import { aliasErrors } from "../../domain/plan-node-aliases";

export interface PlanNodeAliasesProps {
  nodes: { id: string; name: string }[];
  value: Record<string, string>;
  onChange: (value: Record<string, string>) => void;
  enabled: boolean;
  onEnabledChange: (enabled: boolean) => void;
  onValid?: (valid: boolean) => void;
  disabled?: boolean;
  renderNode?: (node: { id: string; name: string }) => ReactNode;
}

export default function PlanNodeAliases({ nodes, value, onChange, enabled, onEnabledChange, onValid, disabled, renderNode }: PlanNodeAliasesProps) {
  const ids = nodes.map(node => node.id);
  const errors = aliasErrors(value, ids);
  const valid = Object.keys(errors).length === 0;
  useEffect(() => { onValid?.(valid); }, [valid, onValid]);
  useEffect(() => {
    const allowed = new Set(nodes.map(node => node.id));
    if (Object.keys(value).some(id => !allowed.has(id))) {
      onChange(Object.fromEntries(Object.entries(value).filter(([id]) => allowed.has(id))));
    }
  }, [nodes, value, onChange]);
  return <Flex vertical gap="middle">
    <Flex gap="small" align="center">
      <Switch aria-label="Custom subscription names" checked={enabled} disabled={disabled || !nodes.length} onChange={onEnabledChange} />
      <Typography.Text>Custom subscription names</Typography.Text>
    </Flex>
    {nodes.map(node => <Card size="small" key={node.id} title={node.name} aria-label={node.name}>
      <Form.Item label="Subscription name" validateStatus={errors[node.id] ? "error" : undefined} help={errors[node.id]}>
        <Input aria-label={`${node.name}: subscription name`} value={value[node.id] ?? ""} placeholder={node.name}
          allowClear disabled={disabled || !enabled} onChange={event => {
            const next = { ...value };
            if (event.target.value) next[node.id] = event.target.value; else delete next[node.id];
            onChange(next);
          }} />
      </Form.Item>
      {renderNode?.(node)}
    </Card>)}
  </Flex>;
}

// frontend/src/components/PlanNodeAliases.vue
<script setup lang="ts">
import { computed, watch } from "vue";
import { aliasErrors } from "../domain/plan-node-aliases";

const props = defineProps<{
  nodes: { id: string; name: string }[];
  names: Record<string, string>;
  enabled: boolean;
  disabled?: boolean;
}>();
const emit = defineEmits<{
  "update:names": [value: Record<string, string>];
  "update:enabled": [value: boolean];
  valid: [value: boolean];
}>();
const ids = computed(() => props.nodes.map(node => node.id));
const errors = computed(() => aliasErrors(props.names, ids.value));
watch(errors, value => emit("valid", Object.keys(value).length === 0), { immediate: true });
watch(ids, value => {
  if (Object.keys(props.names).some(id => !value.includes(id))) {
    emit("update:names", Object.fromEntries(Object.entries(props.names).filter(([id]) => value.includes(id))));
  }
}, { immediate: true });
function setName(id: string, value: string | null) {
  const names = { ...props.names };
  if (value) names[id] = value;
  else delete names[id];
  emit("update:names", names);
}
</script>

<template>
  <div class="plan-node-aliases">
    <v-switch :model-value="enabled" label="Custom subscription names" color="primary" density="compact" hide-details :disabled="disabled || !nodes.length" @update:model-value="emit('update:enabled', !!$event)" />
    <section v-for="node in nodes" :key="node.id" class="plan-alias-node" :aria-label="node.name">
      <strong>{{ node.name }}</strong>
      <v-text-field :model-value="names[node.id] ?? ''" :aria-label="`${node.name}: subscription name`" label="Subscription name" :placeholder="node.name" variant="outlined" density="compact" hide-details="auto" clearable :disabled="disabled || !enabled" :error-messages="errors[node.id] ?? []" @update:model-value="setName(node.id, $event)" />
      <slot :node="node" />
    </section>
  </div>
</template>

<style scoped>
.plan-node-aliases { min-width: 0; }
.plan-alias-node { display: grid; gap: 12px; padding-block: 12px; border-top: 1px solid rgb(var(--v-theme-on-surface), .12); min-width: 0; }
.plan-alias-node strong { font-size: 13px; overflow-wrap: anywhere; }
.plan-node-aliases :deep(.v-label) { white-space: normal; }
.plan-node-aliases :deep(.v-field__input) { min-width: 0; }
</style>
