// frontend/src/react/components/RouteProbeFields.tsx
import { Col, Form, Input, Row, Typography } from "antd";
import { useId } from "react";
import type { AgentReturnRouteTarget } from "../../domain/inventory";
import StrictInputNumber from "./StrictInputNumber";

export interface RouteProbeFieldsProps {
  value: AgentReturnRouteTarget[];
  onChange: (value: AgentReturnRouteTarget[]) => void;
  disabled?: boolean;
}
const names = { telecom: "Telecom", unicom: "Unicom", mobile: "Mobile" };
function validPort(port: number | undefined) {
  const value = port ?? 80;
  return Number.isInteger(value) && value >= 1 && value <= 65535;
}
export default function RouteProbeFields({ value, onChange, disabled }: RouteProbeFieldsProps) {
  const id = useId();
  const update = (index: number, key: "host" | "region" | "port", next: string | number | null) => onChange(value.map((target, position) => position === index ? { ...target, [key]: key === "port" ? (typeof next === "number" ? next : Number.NaN) : String(next ?? "") } : target));
  return <div className="route-probe-fields">{value.map((target, index) => <section key={target.carrier}>
    <Typography.Title level={5}>{names[target.carrier]}</Typography.Title>
    <Row gutter={12}>
      <Col xs={24} sm={16}><Form.Item label={`${names[target.carrier]} host`} htmlFor={`${id}-${index}-host`}><Input id={`${id}-${index}-host`} value={target.host} disabled={disabled} onChange={event => update(index, "host", event.target.value)} /></Form.Item></Col>
      <Col xs={24} sm={8}><Form.Item label={`${names[target.carrier]} port`} htmlFor={`${id}-${index}-port`} validateStatus={!validPort(target.port) ? "error" : undefined} help={!validPort(target.port) ? "Use a whole-number port from 1 to 65535." : undefined}><StrictInputNumber id={`${id}-${index}-port`} value={target.port ?? 80} aria-valuemin={1} aria-valuemax={65535} disabled={disabled} onChange={next => update(index, "port", next)} style={{ width: "100%" }} /></Form.Item></Col>
      <Col span={24}><Form.Item label={`${names[target.carrier]} region`} htmlFor={`${id}-${index}-region`}><Input id={`${id}-${index}-region`} value={target.region} disabled={disabled} onChange={event => update(index, "region", event.target.value)} /></Form.Item></Col>
    </Row>
  </section>)}</div>;
}

// frontend/src/components/RouteProbeFields.vue
<script setup lang="ts">
import type { AgentReturnRouteTarget } from "../domain/inventory";
const props = defineProps<{ modelValue: AgentReturnRouteTarget[] }>();
const emit = defineEmits<{ "update:modelValue": [value: AgentReturnRouteTarget[]] }>();
const names = { telecom: "Telecom", unicom: "Unicom", mobile: "Mobile" };
function update(index: number, key: "host" | "region" | "port", value: unknown) {
  emit("update:modelValue", props.modelValue.map((target, position) =>
    position === index ? { ...target, [key]: key === "port" ? Number(value) : String(value ?? "") } : target));
}
</script>

<template>
  <div class="route-probe-fields">
    <div v-for="(target, index) in modelValue" :key="target.carrier" class="route-probe-target">
      <div class="route-probe-name">{{ names[target.carrier] }}</div>
      <v-text-field :model-value="target.host" :label="names[target.carrier] + ' host'"
        density="comfortable" variant="outlined" @update:model-value="update(index, 'host', $event)" />
      <v-text-field :model-value="target.port" :label="names[target.carrier] + ' port'"
        type="number" min="1" max="65535" density="comfortable" variant="outlined"
        @update:model-value="update(index, 'port', $event)" />
      <v-text-field :model-value="target.region" :label="names[target.carrier] + ' region'"
        density="comfortable" variant="outlined" @update:model-value="update(index, 'region', $event)" />
    </div>
  </div>
</template>

<style scoped>
.route-probe-fields { width: 100%; min-width: 0; grid-column: 1 / -1; }
.route-probe-target { display: grid; grid-template-columns: minmax(0, 1fr) 104px; gap: 0 12px; }
.route-probe-name { grid-column: 1 / -1; font-size: 14px; font-weight: 600; margin-bottom: 8px; }
.route-probe-target > :last-child { grid-column: 1 / -1; }
.route-probe-target :deep(.v-field-label) { font-size: 13px; }
@media (max-width: 380px) {
  .route-probe-target { grid-template-columns: minmax(0, 1fr); }
}
</style>
