// frontend/src/react/components/TemplatesWorkspace.tsx
import { useEffect, useRef, useState } from "react";
import { Alert, Button, Card, Col, Dropdown, Empty, Flex, Form, Input, Modal, Radio, Row, Select, Spin, Switch, Tabs, Tag, Typography, Upload } from "antd";
import { CopyOutlined, DeleteOutlined, DownloadOutlined, EyeOutlined, PlusOutlined, ReloadOutlined, SaveOutlined, UploadOutlined } from "@ant-design/icons";
import type { SubscriptionTemplate, SubscriptionTemplateFormat, SubscriptionTemplatePreview, SubscriptionTemplateSettings, SubscriptionTemplateWrite } from "../../domain/subscription-templates";
import { useSubscriberSession } from "../hooks/useSession";
import { createSubscriptionTemplate, getSubscriptionTemplate, getSubscriptionTemplateSettings, getSubscriptionTemplateStarter, listSubscriptionTemplates, previewSubscriptionTemplate, removeSubscriptionTemplate, subscriptionTemplateDownloadUrl, updateSubscriptionTemplate, updateSubscriptionTemplateSettings } from "../../services/subscription-templates";
import { listProductUsers } from "../../services/subscriptions";

export interface TemplatesWorkspaceProps { subscriber?: boolean }
type TemplateDraft = SubscriptionTemplateWrite & { id: string | null; revision: string };
const formats = [{ label: "Clash / Mihomo", value: "clash" as const }, { label: "Surge", value: "surge" as const }];
export default function TemplatesWorkspace({ subscriber = false }: TemplatesWorkspaceProps) {
  const { session } = useSubscriberSession();
  return <WorkspaceContent key={subscriber ? `subscriber:${session?.username ?? ""}` : "administrator"} subscriber={subscriber} subscriberUsername={subscriber ? session?.username ?? null : null} />;
}
function WorkspaceContent({ subscriber, subscriberUsername }: { subscriber: boolean; subscriberUsername: string | null }) {
  const [templates, setTemplates] = useState<SubscriptionTemplate[]>([]), [settings, setSettings] = useState<SubscriptionTemplateSettings | null>(null), [canManage, setCanManage] = useState(false);
  const [users, setUsers] = useState<{ username: string; display_name: string; removal_id?: string | null }[]>([]), [settingsUsername, setSettingsUsername] = useState("");
  const [selectedId, setSelectedId] = useState<string | null>(null), [draft, setDraft] = useState<TemplateDraft | null>(null), [preview, setPreview] = useState<SubscriptionTemplatePreview | null>(null);
  const [previewUsername, setPreviewUsername] = useState(""), [search, setSearch] = useState(""), [formatFilter, setFormatFilter] = useState<SubscriptionTemplateFormat | "all">("all");
  const [busy, setBusy] = useState(false), [settingsBusy, setSettingsBusy] = useState(false), [error, setError] = useState(""), [success, setSuccess] = useState("");
  const [editorTab, setEditorTab] = useState("source"), [removeOpen, setRemoveOpen] = useState(false), [confirmName, setConfirmName] = useState("");
  const version = useRef(0), settingsVersion = useRef(0), settingsScope = useRef(settingsUsername); settingsScope.current = settingsUsername;
  const current = templates.find(item => item.id === selectedId), editable = canManage && (!draft?.id || !!current?.editable);
  const userOptions = users.filter(user => !user.removal_id).map(user => ({ label: user.display_name ? `${user.display_name} (${user.username})` : user.username, value: user.username }));
  const settingsOwner = subscriber ? subscriberUsername : settingsUsername || null;
  const settingOptions = (format: SubscriptionTemplateFormat) => templates.filter(item => item.format === format && (!settingsOwner || item.owner_username === settingsOwner)).map(item => ({ label: item.name, value: item.id }));
  const filteredTemplates = templates.filter(item => (formatFilter === "all" || item.format === formatFilter) && item.name.toLocaleLowerCase().includes(search.toLocaleLowerCase()));
  function clearMessages() { setError(""); setSuccess(""); }
  function acceptTemplate(item: SubscriptionTemplate) {
    setSelectedId(item.id); setDraft({ id: item.id, revision: item.revision, name: item.name, format: item.format, content: item.content ?? "", owner_username: item.owner_username, is_public: item.is_public }); setPreview(null); setEditorTab("source"); setRemoveOpen(false); setConfirmName("");
  }
  async function refresh(selectId: string | null = selectedId, existingRun?: number) {
    const run = existingRun ?? ++version.current, settingsRun = settingsVersion.current;
    setBusy(true); clearMessages();
    try {
      const [library, userResponse] = await Promise.all([listSubscriptionTemplates(subscriber), subscriber ? Promise.resolve(null) : listProductUsers()]);
      if (run !== version.current) return;
      setTemplates(library.templates); setCanManage(library.can_manage); setUsers(userResponse?.users ?? []);
      if (!settingsScope.current && settingsRun === settingsVersion.current) setSettings(library.settings);
      if (selectId && library.templates.some(item => item.id === selectId)) {
        const item = await getSubscriptionTemplate(selectId, subscriber); if (run !== version.current) return; acceptTemplate(item);
      } else if (selectId) { setSelectedId(null); setDraft(null); setPreview(null); }
    } catch (failure) { if (run === version.current) setError(failure instanceof Error ? failure.message : "Template library unavailable"); }
    finally { if (run === version.current) setBusy(false); }
  }
  useEffect(() => { void refresh(null); return () => { ++version.current; ++settingsVersion.current; }; }, []);
  async function selectTemplate(id: string) {
    if (busy) return; const run = ++version.current; setBusy(true); clearMessages(); setPreview(null);
    try { const item = await getSubscriptionTemplate(id, subscriber); if (run === version.current) acceptTemplate(item); }
    catch (failure) { if (run === version.current) setError(failure instanceof Error ? failure.message : "Template unavailable"); }
    finally { if (run === version.current) setBusy(false); }
  }
  async function newTemplate(format: SubscriptionTemplateFormat) {
    if (busy || !canManage) return;
    const run = ++version.current; setBusy(true); clearMessages();
    try {
      const starter = await getSubscriptionTemplateStarter(format, subscriber); if (run !== version.current) return;
      setSelectedId(null); setDraft({ id: null, revision: "", name: format === "clash" ? "template.yaml" : "template.conf", format, content: starter.content, owner_username: null, is_public: false }); setPreview(null); setEditorTab("source");
    } catch (failure) { if (run === version.current) setError(failure instanceof Error ? failure.message : "Starter unavailable"); }
    finally { if (run === version.current) setBusy(false); }
  }
  async function save() {
    if (!draft || !editable || busy || !draft.name.trim() || !draft.content) return;
    const run = ++version.current; setBusy(true); clearMessages();
    try {
      const payload: SubscriptionTemplateWrite = { name: draft.name.trim(), format: draft.format, content: draft.content, owner_username: subscriber ? null : draft.owner_username, is_public: subscriber ? false : draft.is_public };
      const saved = draft.id ? await updateSubscriptionTemplate(draft.id, payload, draft.revision, subscriber) : await createSubscriptionTemplate(payload, subscriber);
      if (run !== version.current) return;
      await refresh(saved.id, run); if (run === version.current) setSuccess(`${saved.name} saved`);
    } catch (failure) { if (run === version.current) setError(failure instanceof Error ? failure.message : "Template save failed"); }
    finally { if (run === version.current) setBusy(false); }
  }
  async function runPreview() {
    if (!draft || busy || !canManage) return;
    const run = ++version.current; setBusy(true); clearMessages(); setPreview(null);
    try { const value = await previewSubscriptionTemplate(draft.format, draft.content, subscriber ? null : previewUsername || null, subscriber); if (run === version.current) { setPreview(value); setEditorTab("preview"); } }
    catch (failure) { if (run === version.current) setError(failure instanceof Error ? failure.message : "Template preview failed"); }
    finally { if (run === version.current) setBusy(false); }
  }
  function duplicate() {
    if (!draft || busy || !canManage) return;
    ++version.current; const base = draft.name.replace(/\.(ya?ml|conf)$/i, "");
    setSelectedId(null); setDraft({ ...draft, id: null, revision: "", name: `${base}-copy${draft.format === "clash" ? ".yaml" : ".conf"}`, is_public: false }); setPreview(null); setEditorTab("source"); setConfirmName("");
  }
  async function remove() {
    if (busy || !draft?.id || !editable || confirmName !== draft.name) return;
    const run = ++version.current; setBusy(true); clearMessages();
    try {
      await removeSubscriptionTemplate(draft.id, draft.revision, confirmName, subscriber); if (run !== version.current) return;
      setRemoveOpen(false); setConfirmName(""); setSelectedId(null); setDraft(null); setPreview(null);
      await refresh(null, run); if (run === version.current) setSuccess("Template removed");
    } catch (failure) { if (run === version.current) setError(failure instanceof Error ? failure.message : "Template removal failed"); }
    finally { if (run === version.current) setBusy(false); }
  }
  useEffect(() => {
    const run = ++settingsVersion.current; setSettingsBusy(true); setSettings(null);
    void getSubscriptionTemplateSettings(subscriber ? null : settingsUsername || null, subscriber)
      .then(value => { if (run === settingsVersion.current) setSettings(value); })
      .catch(failure => { if (run === settingsVersion.current) setError(failure instanceof Error ? failure.message : "Template settings unavailable"); })
      .finally(() => { if (run === settingsVersion.current) setSettingsBusy(false); });
    return () => { ++settingsVersion.current; };
  }, [settingsUsername, subscriber]);
  async function saveSettings() {
    if (!settings || settingsBusy || (subscriber && !settings.enabled)) return;
    const run = ++settingsVersion.current; setSettingsBusy(true); clearMessages();
    try {
      const value = await updateSubscriptionTemplateSettings(settings, subscriber ? null : settingsUsername || null, subscriber);
      if (run !== settingsVersion.current) return; setSettings(value); setSuccess(settingsUsername ? `Settings saved for ${settingsUsername}` : "Template defaults saved");
    } catch (failure) { if (run === settingsVersion.current) setError(failure instanceof Error ? failure.message : "Template settings save failed"); }
    finally { if (run === settingsVersion.current) setSettingsBusy(false); }
  }
  async function upload(file: File) {
    if (busy || !canManage) return;
    if (file.size > 2 * 1024 * 1024) { setError("Template files are limited to 2 MiB"); return; }
    const format = /\.conf$/i.test(file.name) ? "surge" : /\.ya?ml$/i.test(file.name) ? "clash" : null;
    if (!format) { setError("Choose a .yaml, .yml, or .conf file"); return; }
    const run = ++version.current; setBusy(true); clearMessages();
    try {
      const content = await file.text(); if (run !== version.current) return;
      setSelectedId(null); setDraft({ id: null, revision: "", name: file.name, format, content, owner_username: null, is_public: false }); setPreview(null); setEditorTab("source");
    } catch { if (run === version.current) setError("Unable to read template file"); }
    finally { if (run === version.current) setBusy(false); }
  }
  function patchDraft(change: Partial<TemplateDraft>) {
    setDraft(previous => {
      if (!previous) return previous;
      const value = { ...previous, ...change };
      if (change.format && !value.id) value.name = `${value.name.replace(/\.(ya?ml|conf)$/i, "") || "template"}${change.format === "clash" ? ".yaml" : ".conf"}`;
      return value;
    }); setPreview(null);
  }
  function patchSettings(change: Partial<SubscriptionTemplateSettings>) { setSettings(previous => previous ? { ...previous, ...change } : previous); }
  return <Flex vertical gap="large">
    <Flex justify="space-between" align="center" wrap gap="middle"><div><Typography.Title level={2}>Subscription templates</Typography.Title><Typography.Text type="secondary">{templates.length} files</Typography.Text></div>
      <Flex gap="small"><Upload accept=".yaml,.yml,.conf" showUploadList={false} beforeUpload={file => { void upload(file); return Upload.LIST_IGNORE; }} disabled={busy || !canManage}><Button icon={<UploadOutlined />} aria-label="Upload template" disabled={busy || !canManage} /></Upload>
        <Dropdown menu={{ items: formats.map(format => ({ label: format.label, key: format.value })), onClick: ({ key }) => void newTemplate(key as SubscriptionTemplateFormat) }} disabled={busy || !canManage}><Button icon={<PlusOutlined />} aria-label="New template" disabled={busy || !canManage} /></Dropdown>
        <Button icon={<ReloadOutlined />} aria-label="Refresh templates" loading={busy} disabled={busy} onClick={() => void refresh()} />
      </Flex>
    </Flex>
    {error && <Alert type="error" title={error} showIcon />}{success && <Alert type="success" title={success} showIcon />}
    <section aria-label="Template defaults"><Card title={subscriber ? "My defaults" : settingsUsername ? "Subscriber permission" : "System defaults"}>
      <Form layout="vertical" preserve={false}>
        {!subscriber && <Form.Item label="Subscriber"><Select aria-label="Subscriber" allowClear showSearch optionFilterProp="label" value={settingsUsername || undefined} options={userOptions} disabled={settingsBusy} onChange={value => { setSettings(null); setSettingsUsername(value ?? ""); }} /></Form.Item>}
        {settingsBusy && <Spin />}{settings && <>
          {!subscriber && !!settingsUsername && <Form.Item label="Allow personal templates"><Switch aria-label="Allow personal templates" checked={settings.enabled} disabled={settingsBusy} onChange={enabled => patchSettings({ enabled })} /></Form.Item>}
          {subscriber && <Tag color={settings.enabled ? "success" : "warning"}>{settings.enabled ? "Editing enabled" : "Read only"}</Tag>}
          <Row gutter={16}>{(["clash", "surge"] as const).map(format => <Col xs={24} md={12} key={format}><Form.Item label={`${format === "clash" ? "Clash" : "Surge"} default`}><Select aria-label={`${format === "clash" ? "Clash" : "Surge"} default`} allowClear value={settings[`${format}_template_id`] ?? undefined} options={settingOptions(format)} disabled={settingsBusy || (subscriber && !settings.enabled)} onChange={value => patchSettings({ [`${format}_template_id`]: value ?? null })} /></Form.Item></Col>)}</Row>
          <Button type="primary" icon={<SaveOutlined />} aria-label="Save defaults" loading={settingsBusy} disabled={settingsBusy || (subscriber && !settings.enabled)} onClick={() => void saveSettings()}>Save defaults</Button>
        </>}
      </Form>
    </Card></section>
    <Row gutter={[24, 24]}>
      <Col xs={24} lg={7}><aside aria-label="Template library"><Card><Flex vertical gap="middle"><Form.Item label="Search"><Input aria-label="Search" allowClear value={search} onChange={event => setSearch(event.target.value)} /></Form.Item>
        <Radio.Group aria-label="Template format" value={formatFilter} onChange={event => setFormatFilter(event.target.value)} optionType="button" options={[{ label: "All", value: "all" }, { label: "Clash", value: "clash" }, { label: "Surge", value: "surge" }]} />
        {!filteredTemplates.length && <Empty description="No templates" />}
        {filteredTemplates.map(item => <Card key={item.id} size="small"><Button type={item.id === selectedId ? "primary" : "link"} block disabled={busy} onClick={() => void selectTemplate(item.id)}>{item.name}</Button><Typography.Text type="secondary">{item.format === "clash" ? "Clash" : "Surge"} · {item.owner_username || "System"} · {Math.max(1, Math.ceil(item.size_bytes / 1024))} KiB</Typography.Text>{item.is_public && <Tag>Public</Tag>}</Card>)}
      </Flex></Card></aside></Col>
      <Col xs={24} lg={17}><section aria-label="Template editor"><Card>{draft ? <Flex vertical gap="middle">
        <Flex justify="space-between" align="center" wrap><div><Typography.Title level={4}>{draft.name || "Untitled template"}</Typography.Title><Typography.Text type="secondary">{draft.format === "clash" ? "Clash / Mihomo YAML" : "Surge profile"}</Typography.Text></div>
          <Flex gap="small"><Button icon={<CopyOutlined />} aria-label="Duplicate template" disabled={busy || !canManage} onClick={duplicate} /><Button icon={<DownloadOutlined />} aria-label="Download template" href={draft.id ? subscriptionTemplateDownloadUrl(draft.id, subscriber) : undefined} disabled={!draft.id} download /><Button danger icon={<DeleteOutlined />} aria-label="Remove template" disabled={busy || !draft.id || !editable} onClick={() => { setConfirmName(""); setRemoveOpen(true); }} /></Flex>
        </Flex>
        <Form layout="vertical" preserve={false} disabled={busy || !editable}>
          <Row gutter={16}><Col xs={24} md={12}><Form.Item label="Filename"><Input aria-label="Filename" value={draft.name} maxLength={160} onChange={event => patchDraft({ name: event.target.value })} /></Form.Item></Col><Col xs={24} md={12}><Form.Item label="Format"><Select aria-label="Format" value={draft.format} options={formats} disabled={busy || !editable || !!draft.id} onChange={format => patchDraft({ format })} /></Form.Item></Col></Row>
          {!subscriber && <Row gutter={16}><Col xs={24} md={18}><Form.Item label="Owner"><Select aria-label="Owner" value={draft.owner_username ?? ""} options={[{ label: "System", value: "" }, ...userOptions]} onChange={value => patchDraft({ owner_username: value || null })} /></Form.Item></Col><Col xs={24} md={6}><Form.Item label="Public"><Switch aria-label="Public" checked={draft.is_public} onChange={is_public => patchDraft({ is_public })} /></Form.Item></Col></Row>}
        </Form>
        <Tabs activeKey={editorTab} onChange={setEditorTab} items={[
          { key: "source", label: "Source", children: <Input.TextArea aria-label="Template source" rows={18} value={draft.content} readOnly={!editable} disabled={busy} spellCheck={false} onChange={event => patchDraft({ content: event.target.value })} /> },
          { key: "preview", label: "Preview", children: <Flex vertical gap="small"><Input.TextArea aria-label="Rendered preview" rows={18} readOnly value={preview?.content ?? ""} spellCheck={false} />{preview && <><Flex gap="small" wrap><Tag color="success">{preview.included_nodes} included</Tag>{!!preview.excluded_nodes && <Tag color="warning">{preview.excluded_nodes} excluded</Tag>}</Flex>{preview.warnings.map(warning => <Alert type="warning" key={warning} title={warning} showIcon />)}</>}</Flex> },
        ]} />
        {!subscriber && <Form.Item label="Preview subscriber"><Select aria-label="Preview subscriber" allowClear showSearch optionFilterProp="label" options={userOptions} value={previewUsername || undefined} disabled={busy} onChange={value => { setPreviewUsername(value ?? ""); setPreview(null); }} /></Form.Item>}
        <Flex justify="end" gap="small"><Button icon={<EyeOutlined />} aria-label="Preview" loading={busy} disabled={busy || !canManage} onClick={() => void runPreview()}>Preview</Button><Button type="primary" icon={<SaveOutlined />} aria-label="Save" loading={busy} disabled={busy || !editable || !draft.name.trim() || !draft.content} onClick={() => void save()}>Save</Button></Flex>
      </Flex> : <Empty description="Select or create a template" />}</Card></section></Col>
    </Row>
    <Modal open={removeOpen} title="Remove template" destroyOnHidden mask={{ closable: !busy }} keyboard={!busy} closable={!busy} onCancel={() => !busy && setRemoveOpen(false)} okText="Remove" confirmLoading={busy} okButtonProps={{ "aria-label": "Remove", "aria-busy": busy, danger: true, disabled: confirmName !== draft?.name || !draft?.id || !editable }} cancelButtonProps={{ disabled: busy }} onOk={() => void remove()}>
      <Typography.Paragraph>{draft?.name}</Typography.Paragraph><Form.Item label="Confirm filename"><Input aria-label="Confirm filename" value={confirmName} disabled={busy} onChange={event => setConfirmName(event.target.value)} /></Form.Item>
    </Modal>
  </Flex>;
}

// frontend/src/components/TemplatesWorkspace.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, watch } from "vue";

import type {
  SubscriptionTemplate,
  SubscriptionTemplateFormat,
  SubscriptionTemplatePreview,
  SubscriptionTemplateSettings,
  SubscriptionTemplateWrite,
} from "../domain/subscription-templates";
import { subscriberState } from "../services/subscriber-auth";
import {
  createSubscriptionTemplate,
  getSubscriptionTemplate,
  getSubscriptionTemplateSettings,
  getSubscriptionTemplateStarter,
  listSubscriptionTemplates,
  previewSubscriptionTemplate,
  removeSubscriptionTemplate,
  subscriptionTemplateDownloadUrl,
  updateSubscriptionTemplate,
  updateSubscriptionTemplateSettings,
} from "../services/subscription-templates";
import { listProductUsers } from "../services/subscriptions";

const props = withDefaults(defineProps<{ subscriber?: boolean }>(), { subscriber: false });
const templates = ref<SubscriptionTemplate[]>([]);
const settings = ref<SubscriptionTemplateSettings | null>(null);
const canManage = ref(false);
const users = ref<{ username: string; display_name: string; removal_id?: string | null }[]>([]);
const settingsUsername = ref("");
const selectedId = ref<string | null>(null);
const draft = ref<(SubscriptionTemplateWrite & { id: string | null; revision: string }) | null>(null);
const preview = ref<SubscriptionTemplatePreview | null>(null);
const previewUsername = ref("");
const search = ref("");
const formatFilter = ref<SubscriptionTemplateFormat | "all">("all");
const busy = ref(false);
const settingsBusy = ref(false);
const error = ref("");
const success = ref("");
const editorTab = ref<"source" | "preview">("source");
const removeOpen = ref(false);
const confirmName = ref("");
const fileInput = ref<HTMLInputElement | null>(null);
let version = 0;

const formats: Array<{ title: string; value: SubscriptionTemplateFormat }> = [
  { title: "Clash / Mihomo", value: "clash" },
  { title: "Surge", value: "surge" },
];
const filteredTemplates = computed(() => templates.value.filter((item) =>
  (formatFilter.value === "all" || item.format === formatFilter.value)
  && item.name.toLocaleLowerCase().includes(search.value.toLocaleLowerCase()),
));
const userOptions = computed(() => users.value.filter(user => !user.removal_id).map(user => ({
  title: user.display_name ? `${user.display_name} (${user.username})` : user.username,
  value: user.username,
})));
const ownerOptions = computed(() => [{ title: "System", value: null }, ...userOptions.value]);
const targetUsername = computed(() => props.subscriber ? null : settingsUsername.value || null);
const settingsOwner = computed(() => props.subscriber
  ? subscriberState.session?.username ?? null
  : settingsUsername.value || null);
const settingOptions = (format: SubscriptionTemplateFormat) => templates.value
  .filter(item => item.format === format && (!settingsOwner.value || item.owner_username === settingsOwner.value))
  .map(item => ({ title: item.name, value: item.id }));
const current = computed(() => templates.value.find(item => item.id === selectedId.value) ?? null);
const editable = computed(() => canManage.value && (!draft.value?.id || current.value?.editable));
const downloadUrl = computed(() => draft.value?.id ? subscriptionTemplateDownloadUrl(draft.value.id, props.subscriber) : "");

function clearMessages() {
  error.value = "";
  success.value = "";
}

async function refresh(selectId = selectedId.value) {
  const request = ++version;
  busy.value = true;
  clearMessages();
  try {
    const [library, userResponse] = await Promise.all([
      listSubscriptionTemplates(props.subscriber),
      props.subscriber ? Promise.resolve(null) : listProductUsers(),
    ]);
    if (request !== version) return;
    templates.value = library.templates;
    settings.value = library.settings;
    canManage.value = library.can_manage;
    users.value = userResponse?.users ?? [];
    if (selectId && templates.value.some(item => item.id === selectId)) await selectTemplate(selectId, request);
    else if (draft.value?.id) { selectedId.value = null; draft.value = null; preview.value = null; }
  } catch (failure) {
    if (request === version) error.value = failure instanceof Error ? failure.message : "Template library unavailable";
  } finally {
    if (request === version) busy.value = false;
  }
}

async function selectTemplate(id: string, request = ++version) {
  busy.value = true;
  clearMessages();
  try {
    const item = await getSubscriptionTemplate(id, props.subscriber);
    if (request !== version) return;
    selectedId.value = id;
    draft.value = {
      id: item.id,
      revision: item.revision,
      name: item.name,
      format: item.format,
      content: item.content ?? "",
      owner_username: item.owner_username,
      is_public: item.is_public,
    };
    preview.value = null;
    editorTab.value = "source";
  } catch (failure) {
    if (request === version) error.value = failure instanceof Error ? failure.message : "Template unavailable";
  } finally {
    if (request === version) busy.value = false;
  }
}

async function newTemplate(format: SubscriptionTemplateFormat) {
  const request = ++version;
  busy.value = true;
  clearMessages();
  try {
    const starter = await getSubscriptionTemplateStarter(format, props.subscriber);
    if (request !== version) return;
    selectedId.value = null;
    draft.value = {
      id: null,
      revision: "",
      name: format === "clash" ? "template.yaml" : "template.conf",
      format,
      content: starter.content,
      owner_username: props.subscriber ? null : null,
      is_public: false,
    };
    preview.value = null;
    editorTab.value = "source";
  } catch (failure) {
    if (request === version) error.value = failure instanceof Error ? failure.message : "Starter unavailable";
  } finally {
    if (request === version) busy.value = false;
  }
}

async function save() {
  if (!draft.value || !editable.value || busy.value) return;
  busy.value = true;
  clearMessages();
  try {
    const payload: SubscriptionTemplateWrite = {
      name: draft.value.name.trim(),
      format: draft.value.format,
      content: draft.value.content,
      owner_username: props.subscriber ? null : draft.value.owner_username,
      is_public: props.subscriber ? false : draft.value.is_public,
    };
    const saved = draft.value.id
      ? await updateSubscriptionTemplate(draft.value.id, payload, draft.value.revision, props.subscriber)
      : await createSubscriptionTemplate(payload, props.subscriber);
    selectedId.value = saved.id;
    await refresh(saved.id);
    success.value = `${saved.name} saved`;
  } catch (failure) {
    error.value = failure instanceof Error ? failure.message : "Template save failed";
  } finally {
    busy.value = false;
  }
}

async function runPreview() {
  if (!draft.value || busy.value) return;
  busy.value = true;
  clearMessages();
  try {
    preview.value = await previewSubscriptionTemplate(
      draft.value.format,
      draft.value.content,
      props.subscriber ? null : previewUsername.value || null,
      props.subscriber,
    );
    editorTab.value = "preview";
  } catch (failure) {
    error.value = failure instanceof Error ? failure.message : "Template preview failed";
  } finally {
    busy.value = false;
  }
}

function duplicate() {
  if (!draft.value) return;
  const extension = draft.value.format === "clash" ? ".yaml" : ".conf";
  const base = draft.value.name.replace(/\.(ya?ml|conf)$/i, "");
  selectedId.value = null;
  draft.value = { ...draft.value, id: null, revision: "", name: `${base}-copy${extension}`, is_public: false };
  preview.value = null;
  editorTab.value = "source";
}

async function remove() {
  if (!draft.value?.id || !current.value?.editable || confirmName.value !== draft.value.name) return;
  busy.value = true;
  clearMessages();
  try {
    await removeSubscriptionTemplate(draft.value.id, draft.value.revision, confirmName.value, props.subscriber);
    removeOpen.value = false;
    confirmName.value = "";
    selectedId.value = null;
    draft.value = null;
    await refresh(null);
    success.value = "Template removed";
  } catch (failure) {
    error.value = failure instanceof Error ? failure.message : "Template removal failed";
  } finally {
    busy.value = false;
  }
}

async function loadSettings() {
  settingsBusy.value = true;
  clearMessages();
  try {
    settings.value = await getSubscriptionTemplateSettings(targetUsername.value, props.subscriber);
  } catch (failure) {
    error.value = failure instanceof Error ? failure.message : "Template settings unavailable";
  } finally {
    settingsBusy.value = false;
  }
}

async function saveSettings() {
  if (!settings.value || settingsBusy.value) return;
  settingsBusy.value = true;
  clearMessages();
  try {
    settings.value = await updateSubscriptionTemplateSettings(settings.value, targetUsername.value, props.subscriber);
    success.value = settingsUsername.value ? `Settings saved for ${settingsUsername.value}` : "Template defaults saved";
  } catch (failure) {
    error.value = failure instanceof Error ? failure.message : "Template settings save failed";
  } finally {
    settingsBusy.value = false;
  }
}

async function upload(event: Event) {
  const input = event.target as HTMLInputElement;
  const file = input.files?.[0];
  input.value = "";
  if (!file) return;
  if (file.size > 2 * 1024 * 1024) { error.value = "Template files are limited to 2 MiB"; return; }
  const format = /\.conf$/i.test(file.name) ? "surge" : /\.ya?ml$/i.test(file.name) ? "clash" : null;
  if (!format) { error.value = "Choose a .yaml, .yml, or .conf file"; return; }
  selectedId.value = null;
  draft.value = {
    id: null,
    revision: "",
    name: file.name,
    format,
    content: await file.text(),
    owner_username: null,
    is_public: false,
  };
  preview.value = null;
  editorTab.value = "source";
}

watch(settingsUsername, () => { if (!props.subscriber) void loadSettings(); });
watch(() => draft.value?.format, (format) => {
  if (!draft.value || !format || draft.value.id) return;
  const base = draft.value.name.replace(/\.(ya?ml|conf)$/i, "") || "template";
  draft.value.name = `${base}${format === "clash" ? ".yaml" : ".conf"}`;
  preview.value = null;
});
onMounted(() => { void refresh(); });
onBeforeUnmount(() => { ++version; });
</script>

<template>
  <div class="templates-workspace">
    <div class="template-toolbar">
      <div><h2>Subscription templates</h2><span>{{ templates.length }} files</span></div>
      <div class="template-actions">
        <v-tooltip text="Upload template"><template #activator="{ props: tip }"><v-btn v-bind="tip" icon="mdi-upload" aria-label="Upload template" variant="text" :disabled="busy || !canManage" @click="fileInput?.click()" /></template></v-tooltip>
        <input ref="fileInput" type="file" accept=".yaml,.yml,.conf" hidden @change="upload">
        <v-menu><template #activator="{ props: menu }"><v-tooltip text="New template"><template #activator="{ props: tip }"><v-btn v-bind="{ ...menu, ...tip }" icon="mdi-plus" aria-label="New template" variant="text" :disabled="busy || !canManage" /></template></v-tooltip></template><v-list density="compact"><v-list-item v-for="item in formats" :key="item.value" :title="item.title" @click="newTemplate(item.value)" /></v-list></v-menu>
        <v-tooltip text="Refresh templates"><template #activator="{ props: tip }"><v-btn v-bind="tip" icon="mdi-refresh" aria-label="Refresh templates" variant="text" :loading="busy" @click="refresh()" /></template></v-tooltip>
      </div>
    </div>

    <v-alert v-if="error" type="error" variant="tonal" class="mb-4">{{ error }}</v-alert>
    <v-alert v-if="success" type="success" variant="tonal" class="mb-4">{{ success }}</v-alert>

    <section class="defaults-band" aria-label="Template defaults">
      <div class="defaults-heading">
        <h3>{{ subscriber ? 'My defaults' : settingsUsername ? 'Subscriber permission' : 'System defaults' }}</h3>
        <v-select v-if="!subscriber" v-model="settingsUsername" :items="userOptions" label="Subscriber" clearable variant="outlined" density="compact" hide-details :disabled="settingsBusy" />
      </div>
      <div v-if="settings" class="defaults-controls">
        <v-switch v-if="!subscriber && settingsUsername" v-model="settings.enabled" label="Allow personal templates" color="primary" density="compact" hide-details :disabled="settingsBusy" />
        <v-chip v-else-if="subscriber" :color="settings.enabled ? 'success' : 'warning'" size="small" variant="tonal">{{ settings.enabled ? 'Editing enabled' : 'Read only' }}</v-chip>
        <v-select v-model="settings.clash_template_id" :items="settingOptions('clash')" label="Clash default" clearable variant="outlined" density="compact" hide-details :disabled="settingsBusy || (subscriber && !settings.enabled)" />
        <v-select v-model="settings.surge_template_id" :items="settingOptions('surge')" label="Surge default" clearable variant="outlined" density="compact" hide-details :disabled="settingsBusy || (subscriber && !settings.enabled)" />
        <v-btn color="primary" prepend-icon="mdi-content-save" variant="tonal" :loading="settingsBusy" :disabled="subscriber && !settings.enabled" @click="saveSettings">Save defaults</v-btn>
      </div>
    </section>

    <div class="template-grid">
      <aside class="template-library" aria-label="Template library">
        <div class="library-filters"><v-text-field v-model="search" label="Search" prepend-inner-icon="mdi-magnify" clearable variant="outlined" density="compact" hide-details /><v-btn-toggle v-model="formatFilter" mandatory color="primary" density="compact" variant="outlined" aria-label="Template format"><v-btn value="all">All</v-btn><v-btn value="clash">Clash</v-btn><v-btn value="surge">Surge</v-btn></v-btn-toggle></div>
        <v-list class="template-list" lines="two" density="compact">
          <v-list-item v-for="item in filteredTemplates" :key="item.id" :active="item.id === selectedId" :title="item.name" :subtitle="`${item.format === 'clash' ? 'Clash' : 'Surge'} · ${item.owner_username || 'System'} · ${Math.max(1, Math.ceil(item.size_bytes / 1024))} KiB`" @click="selectTemplate(item.id)"><template #prepend><v-icon :icon="item.format === 'clash' ? 'mdi-alpha-c-box-outline' : 'mdi-alpha-s-box-outline'" /></template><template #append><v-icon v-if="item.is_public" icon="mdi-earth" size="small" /></template></v-list-item>
          <v-list-item v-if="!filteredTemplates.length" title="No templates" prepend-icon="mdi-file-outline" />
        </v-list>
      </aside>

      <section class="template-editor" aria-label="Template editor">
        <div v-if="draft" class="editor-shell">
          <div class="editor-heading"><div><h3>{{ draft.name || 'Untitled template' }}</h3><span>{{ draft.format === 'clash' ? 'Clash / Mihomo YAML' : 'Surge profile' }}</span></div><div class="editor-actions"><v-tooltip text="Duplicate"><template #activator="{ props: tip }"><v-btn v-bind="tip" icon="mdi-content-duplicate" aria-label="Duplicate template" variant="text" :disabled="busy || !canManage" @click="duplicate" /></template></v-tooltip><v-tooltip text="Download"><template #activator="{ props: tip }"><v-btn v-bind="tip" icon="mdi-download" aria-label="Download template" variant="text" :href="downloadUrl || undefined" :disabled="!downloadUrl" download /></template></v-tooltip><v-tooltip text="Remove"><template #activator="{ props: tip }"><v-btn v-bind="tip" icon="mdi-delete-outline" aria-label="Remove template" color="error" variant="text" :disabled="busy || !current?.editable" @click="removeOpen = true" /></template></v-tooltip></div></div>
          <div class="editor-meta"><v-text-field v-model="draft.name" label="Filename" maxlength="160" variant="outlined" density="compact" hide-details :disabled="busy || !editable" /><v-select v-model="draft.format" :items="formats" label="Format" variant="outlined" density="compact" hide-details :disabled="busy || !editable || !!draft.id" /><v-select v-if="!subscriber" v-model="draft.owner_username" :items="ownerOptions" label="Owner" variant="outlined" density="compact" hide-details :disabled="busy || !editable" /><v-switch v-if="!subscriber" v-model="draft.is_public" label="Public" color="primary" density="compact" hide-details :disabled="busy || !editable" /></div>
          <v-tabs v-model="editorTab" color="primary" density="compact"><v-tab value="source" prepend-icon="mdi-code-braces">Source</v-tab><v-tab value="preview" prepend-icon="mdi-eye-outline">Preview</v-tab></v-tabs>
          <v-window v-model="editorTab">
            <v-window-item value="source"><v-textarea v-model="draft.content" class="template-source" aria-label="Template source" variant="outlined" rows="18" no-resize hide-details :readonly="!editable" spellcheck="false" /></v-window-item>
            <v-window-item value="preview"><v-textarea :model-value="preview?.content ?? ''" class="template-source" aria-label="Rendered preview" variant="outlined" rows="18" no-resize hide-details readonly spellcheck="false" /><div v-if="preview" class="preview-summary"><v-chip size="small" color="success" variant="tonal">{{ preview.included_nodes }} included</v-chip><v-chip v-if="preview.excluded_nodes" size="small" color="warning" variant="tonal">{{ preview.excluded_nodes }} excluded</v-chip><span v-for="warning in preview.warnings" :key="warning">{{ warning }}</span></div></v-window-item>
          </v-window>
          <div class="editor-footer"><v-select v-if="!subscriber" v-model="previewUsername" :items="userOptions" label="Preview subscriber" clearable variant="outlined" density="compact" hide-details /><v-btn prepend-icon="mdi-eye-outline" variant="tonal" :loading="busy" :disabled="!canManage" @click="runPreview">Preview</v-btn><v-btn color="primary" prepend-icon="mdi-content-save" :loading="busy" :disabled="!editable || !draft.name.trim() || !draft.content" @click="save">Save</v-btn></div>
        </div>
        <div v-else class="editor-empty"><v-icon icon="mdi-file-document-edit-outline" size="42" /><span>Select or create a template</span></div>
      </section>
    </div>

    <v-dialog v-model="removeOpen" max-width="440" :persistent="busy"><v-card><v-card-title>Remove template</v-card-title><v-card-text><p class="mb-4">{{ draft?.name }}</p><v-text-field v-model="confirmName" label="Confirm filename" variant="outlined" density="compact" hide-details :disabled="busy" /></v-card-text><v-card-actions><v-btn :disabled="busy" @click="removeOpen = false">Cancel</v-btn><v-spacer /><v-btn color="error" prepend-icon="mdi-delete-outline" :loading="busy" :disabled="confirmName !== draft?.name" @click="remove">Remove</v-btn></v-card-actions></v-card></v-dialog>
  </div>
</template>

<style scoped>
.templates-workspace, .templates-workspace :deep(*) { letter-spacing: 0; }
.template-toolbar, .editor-heading, .defaults-heading { display: flex; justify-content: space-between; align-items: center; gap: 16px; }
.template-toolbar { margin-bottom: 20px; }
.template-toolbar h2 { font-size: 22px; }
.template-toolbar span, .editor-heading span { color: #66736f; font-size: 12px; }
.template-actions, .editor-actions, .editor-footer { display: flex; align-items: center; gap: 4px; }
.defaults-band { border-block: 1px solid #dbe5e0; padding: 20px 0; margin-bottom: 24px; }
.defaults-heading h3, .editor-heading h3 { font-size: 15px; overflow-wrap: anywhere; }
.defaults-heading .v-select { width: min(100%, 320px); }
.defaults-controls { display: grid; grid-template-columns: minmax(130px, .7fr) repeat(2, minmax(180px, 1fr)) auto; align-items: center; gap: 12px; margin-top: 16px; }
.template-grid { display: grid; grid-template-columns: minmax(260px, 320px) minmax(0, 1fr); border: 1px solid #dbe5e0; min-height: 620px; }
.template-library { border-right: 1px solid #dbe5e0; min-width: 0; }
.library-filters { display: grid; gap: 12px; padding: 16px; border-bottom: 1px solid #dbe5e0; }
.library-filters .v-btn-toggle { width: 100%; }
.library-filters .v-btn { flex: 1; }
.template-list { max-height: 540px; overflow: auto; }
.template-list :deep(.v-list-item-title), .template-list :deep(.v-list-item-subtitle) { overflow-wrap: anywhere; white-space: normal; }
.template-editor { min-width: 0; }
.editor-shell { display: grid; gap: 16px; padding: 20px; }
.editor-meta { display: grid; grid-template-columns: minmax(180px, 1.3fr) minmax(130px, .7fr) minmax(160px, 1fr) auto; align-items: center; gap: 12px; }
.template-source :deep(textarea) { min-height: 390px; max-height: 390px; overflow: auto; font-family: "Cascadia Mono", Consolas, monospace; font-size: 12px; line-height: 1.55; }
.preview-summary { display: flex; flex-wrap: wrap; gap: 8px; align-items: center; padding-top: 12px; font-size: 12px; overflow-wrap: anywhere; }
.editor-footer { justify-content: flex-end; }
.editor-footer .v-select { max-width: 280px; }
.editor-empty { min-height: 600px; display: grid; place-content: center; justify-items: center; gap: 12px; color: #66736f; }
@media (max-width: 900px) {
  .template-grid { grid-template-columns: minmax(0, 1fr); }
  .template-library { border-right: 0; border-bottom: 1px solid #dbe5e0; }
  .template-list { max-height: 260px; }
  .editor-meta, .defaults-controls { grid-template-columns: repeat(2, minmax(0, 1fr)); }
}
@media (max-width: 600px) {
  .template-toolbar, .editor-heading, .defaults-heading { align-items: flex-start; flex-wrap: wrap; }
  .template-grid { border-inline: 0; }
  .editor-shell { padding: 16px 0; }
  .editor-meta, .defaults-controls { grid-template-columns: minmax(0, 1fr); }
  .editor-footer { align-items: stretch; flex-direction: column; }
  .editor-footer .v-select { max-width: none; }
  .template-source :deep(textarea) { min-height: 330px; max-height: 330px; }
}
</style>
