// frontend/src/react/components/WarpStatus.tsx
import { Descriptions, Space, Tag } from "antd";
import { resultObject } from "../../domain/diagnostics";

export interface WarpStatusProps { body: unknown }
export default function WarpStatus({ body }: WarpStatusProps) {
  const status = resultObject(body);
  const phase = ({ absent: "Not installed", configured: "Outbounds configured", needs_apply: "Needs configuration", removal_pending: "Removal pending" } as Record<string, string>)[String(status.phase)]
    ?? (status.installed ? "Outbounds configured" : "Not installed");
  const account = status.account_type === "free" ? "Free WARP" : status.license_active ? "WARP+" : String(status.account_type ?? "Unknown");
  const date = new Date(String(status.registered_at ?? ""));
  const registered = Number.isNaN(date.getTime()) ? null : date.toISOString();
  return <section aria-label="WARP result"><Space orientation="vertical" style={{ width: "100%" }}>
    <Tag color={status.installed ? "success" : status.registered ? "warning" : "default"}>{phase}</Tag>
    {Boolean(status.registered || status.installed) && <Descriptions column={1} size="small" items={[
      { key: "account", label: "Account", children: account },
      { key: "ipv4", label: "IPv4", children: String(status.addr_v4 || "None") },
      { key: "ipv6", label: "IPv6", children: String(status.addr_v6 || "None") },
      { key: "registered", label: "Registered", children: registered ? <time dateTime={registered}>{registered.slice(0, 10)}<br />{registered.slice(11, 16)} UTC</time> : "Unknown" },
    ]} />}
  </Space></section>;
}

// frontend/src/components/WarpStatus.vue
<script setup lang="ts">
import { computed } from "vue";
const props = defineProps<{ body: unknown }>();
const status = computed(() => (props.body && typeof props.body === "object"
  ? props.body : {}) as Record<string, unknown>);
const phase = computed(() => ({
  absent: "Not installed", configured: "Outbounds configured",
  needs_apply: "Needs configuration", removal_pending: "Removal pending",
}[String(status.value.phase)] ?? (status.value.installed ? "Outbounds configured" : "Not installed")));
const account = computed(() => status.value.account_type === "free" ? "Free WARP"
  : status.value.license_active ? "WARP+" : String(status.value.account_type ?? "Unknown"));
const registered = computed(() => {
  const date = new Date(String(status.value.registered_at ?? ""));
  if (Number.isNaN(date.getTime())) return null;
  const iso = date.toISOString();
  return { iso, day: iso.slice(0, 10), time: iso.slice(11, 16) + " UTC" };
});
</script>

<template>
  <section class="warp-status" aria-label="WARP result">
    <v-chip :color="status.installed ? 'success' : status.registered ? 'warning' : 'grey'"
      size="small" variant="tonal">{{ phase }}</v-chip>
    <dl v-if="status.registered || status.installed">
      <dt>Account</dt><dd>{{ account }}</dd>
      <dt>IPv4</dt><dd>{{ status.addr_v4 || "None" }}</dd>
      <dt>IPv6</dt><dd>{{ status.addr_v6 || "None" }}</dd>
      <dt>Registered</dt><dd><time v-if="registered" :datetime="registered.iso">
        <span>{{ registered.day }}</span><span>{{ registered.time }}</span>
      </time><span v-else>Unknown</span></dd>
    </dl>
  </section>
</template>

<style scoped>
.warp-status { min-width: 0; }
dl { display: grid; grid-template-columns: 80px minmax(0, 1fr); gap: 8px 12px; font-size: 13px; margin-top: 16px; }
dt { color: rgba(var(--v-theme-on-surface), .72); }
dd { margin: 0; overflow-wrap: anywhere; }
time span { display: block; }
</style>
