// frontend/src/views/ChangesView.vue
<script setup lang="ts">
import { computed, onMounted, reactive, ref } from "vue";

import type {
  AgentChangeSet,
  AgentChangeSetCreateRequest,
  AgentChangeSetStatus,
  AgentChangeSetStepCreateRequest,
  AgentRoutedOutboundChangeSetCreateRequest,
} from "../domain/changes";
import type { AgentCommand, AgentCommandCreateRequest, ServerSummary } from "../domain/inventory";
import { listServers } from "../services/inventory";
import {
  createChangeSet,
  createRoutedOutboundChangeSet,
  dispatchChangeSet,
  listChangeSets,
  rollbackChangeSet,
} from "../services/changes";

const servers = ref<ServerSummary[]>([]);
const changeSets = ref<AgentChangeSet[]>([]);
const selectedChangeSetId = ref("");
const loading = ref(false);
const savingAction = ref<"create" | "routed" | "dispatch" | "rollback" | "">("");
const errorMessage = ref("");
const successMessage = ref("");
const lastCommands = ref<AgentCommand[]>([]);
const warnings = ref<string[]>([]);
const planMode = ref<"routed" | "raw">("routed");

const inboundProtocolOptions = [
  "vless",
  "vmess",
  "trojan",
  "shadowsocks",
  "anytls",
  "snell",
  "mieru",
  "hysteria",
  "socks",
  "http",
];

const routedForm = reactive({
  server_id: "",
  inbound_tag: "",
  inbound_protocol: "vless",
  label: "direct",
  parent_ref: "",
  admin_username: "admin",
  admin_email: "",
  outbound_tag: "",
  marktag: "",
  node_name: "",
  outboundText: sampleRoutedOutboundText(),
  clientText: "",
  sniffingExcludeDomainsText: "",
  add_reality_sniffing_excludes: true,
  rollback_on_failure: true,
  dispatch: false,
  command_timeout_ms: 30000,
});

const form = reactive({
  name: "",
  description: "",
  rollback_on_failure: true,
  dispatch: false,
  rollbackReason: "",
  stepsText: sampleStepsText(""),
});

const changeStatusMeta: Record<AgentChangeSetStatus, { color: string; icon: string }> = {
  planned: { color: "grey", icon: "mdi-clipboard-text-clock-outline" },
  dispatched: { color: "info", icon: "mdi-send-clock-outline" },
  rollback_queued: { color: "warning", icon: "mdi-undo-variant" },
};

const commandStatusMeta = {
  pending: { color: "warning", icon: "mdi-clock-outline" },
  leased: { color: "info", icon: "mdi-progress-clock" },
  succeeded: { color: "success", icon: "mdi-check-circle-outline" },
  failed: { color: "error", icon: "mdi-alert-circle-outline" },
} as const;

const serverOptions = computed(() =>
  servers.value.map((server) => ({ title: server.name, value: server.id })),
);
const selectedChangeSet = computed(
  () => changeSets.value.find((changeSet) => changeSet.id === selectedChangeSetId.value) ?? null,
);
const lastCommandsJson = computed(() =>
  lastCommands.value.length > 0 ? JSON.stringify(lastCommands.value, null, 2) : "",
);

onMounted(() => {
  void refresh();
});

async function refresh() {
  loading.value = true;
  errorMessage.value = "";
  try {
    const [serverList, changeSetResponse] = await Promise.all([listServers(), listChangeSets()]);
    servers.value = serverList;
    changeSets.value = changeSetResponse.change_sets;
    syncStepSample();
    syncRoutedServer();
    syncSelectedChangeSet();
  } catch (error) {
    errorMessage.value = readableError(error);
  } finally {
    loading.value = false;
  }
}

async function submitRoutedOutbound() {
  const serverId = routedForm.server_id.trim();
  const inboundTag = routedForm.inbound_tag.trim();
  const label = routedForm.label.trim();
  const timeoutMs = Number(routedForm.command_timeout_ms);
  if (!serverId) {
    errorMessage.value = "Server is required.";
    return;
  }
  if (!inboundTag) {
    errorMessage.value = "Inbound tag is required.";
    return;
  }
  if (!label) {
    errorMessage.value = "Label is required.";
    return;
  }
  if (!Number.isFinite(timeoutMs) || timeoutMs <= 0) {
    errorMessage.value = "Timeout must be greater than zero.";
    return;
  }

  savingAction.value = "routed";
  errorMessage.value = "";
  successMessage.value = "";
  warnings.value = [];
  try {
    const payload: AgentRoutedOutboundChangeSetCreateRequest = {
      server_id: serverId,
      inbound_tag: inboundTag,
      inbound_protocol: routedForm.inbound_protocol.trim() || "vless",
      label,
      outbound: parseJsonObject(routedForm.outboundText, "Outbound JSON"),
      parent_ref: optionalText(routedForm.parent_ref),
      admin_username: routedForm.admin_username.trim() || "admin",
      admin_email: optionalText(routedForm.admin_email),
      outbound_tag: optionalText(routedForm.outbound_tag),
      marktag: optionalText(routedForm.marktag),
      node_name: optionalText(routedForm.node_name),
      client: parseOptionalJsonObject(routedForm.clientText, "Client JSON"),
      sniffing_exclude_domains: splitTextList(routedForm.sniffingExcludeDomainsText),
      add_reality_sniffing_excludes: routedForm.add_reality_sniffing_excludes,
      command_timeout_ms: timeoutMs,
      rollback_on_failure: routedForm.rollback_on_failure,
      dispatch: routedForm.dispatch,
    };
    const response = await createRoutedOutboundChangeSet(payload);
    selectedChangeSetId.value = response.change_set.id;
    lastCommands.value = response.commands;
    warnings.value = response.warnings;
    successMessage.value = response.commands.length
      ? `Created routed outbound plan and dispatched ${response.commands.length} commands.`
      : "Routed outbound change set created.";
    await refresh();
    selectedChangeSetId.value = response.change_set.id;
  } catch (error) {
    errorMessage.value = readableError(error);
  } finally {
    savingAction.value = "";
  }
}

async function submitChangeSet() {
  const name = form.name.trim();
  if (!name) {
    errorMessage.value = "Name is required.";
    return;
  }

  savingAction.value = "create";
  errorMessage.value = "";
  successMessage.value = "";
  warnings.value = [];
  try {
    const payload: AgentChangeSetCreateRequest = {
      name,
      description: form.description.trim(),
      rollback_on_failure: form.rollback_on_failure,
      dispatch: form.dispatch,
      steps: parseStepsText(),
    };
    const response = await createChangeSet(payload);
    selectedChangeSetId.value = response.change_set.id;
    lastCommands.value = response.commands;
    warnings.value = response.warnings;
    successMessage.value = response.commands.length
      ? `Created and dispatched ${response.commands.length} commands.`
      : "Change set created.";
    resetPlanForm();
    await refresh();
    selectedChangeSetId.value = response.change_set.id;
  } catch (error) {
    errorMessage.value = readableError(error);
  } finally {
    savingAction.value = "";
  }
}

async function dispatchSelected() {
  if (!selectedChangeSet.value) {
    errorMessage.value = "Change set is required.";
    return;
  }

  savingAction.value = "dispatch";
  errorMessage.value = "";
  successMessage.value = "";
  warnings.value = [];
  try {
    const response = await dispatchChangeSet(selectedChangeSet.value.id);
    selectedChangeSetId.value = response.change_set.id;
    lastCommands.value = response.commands;
    successMessage.value = response.commands.length
      ? `Dispatched ${response.commands.length} commands.`
      : "No new forward commands.";
    await refresh();
    selectedChangeSetId.value = response.change_set.id;
  } catch (error) {
    errorMessage.value = readableError(error);
  } finally {
    savingAction.value = "";
  }
}

async function rollbackSelected() {
  if (!selectedChangeSet.value) {
    errorMessage.value = "Change set is required.";
    return;
  }

  savingAction.value = "rollback";
  errorMessage.value = "";
  successMessage.value = "";
  try {
    const response = await rollbackChangeSet(selectedChangeSet.value.id, {
      reason: form.rollbackReason.trim(),
    });
    selectedChangeSetId.value = response.change_set.id;
    lastCommands.value = response.commands;
    warnings.value = response.warnings;
    successMessage.value = response.commands.length
      ? `Queued ${response.commands.length} rollback commands.`
      : "No new rollback commands.";
    await refresh();
    selectedChangeSetId.value = response.change_set.id;
  } catch (error) {
    errorMessage.value = readableError(error);
  } finally {
    savingAction.value = "";
  }
}

function syncStepSample() {
  const firstServerId = servers.value[0]?.id;
  if (firstServerId && form.stepsText.includes('"server_id": ""')) {
    form.stepsText = sampleStepsText(firstServerId);
  }
}

function syncRoutedServer() {
  if (
    routedForm.server_id &&
    servers.value.some((server) => server.id === routedForm.server_id)
  ) {
    return;
  }
  routedForm.server_id = servers.value[0]?.id ?? "";
}

function syncSelectedChangeSet() {
  if (
    selectedChangeSetId.value &&
    changeSets.value.some((changeSet) => changeSet.id === selectedChangeSetId.value)
  ) {
    return;
  }
  selectedChangeSetId.value = changeSets.value[0]?.id ?? "";
}

function resetPlanForm() {
  Object.assign(form, {
    name: "",
    description: "",
    rollback_on_failure: true,
    dispatch: false,
  });
}

function useSampleSteps() {
  form.stepsText = sampleStepsText(servers.value[0]?.id ?? "");
}

function useServerSample(serverId: unknown) {
  form.stepsText = sampleStepsText(typeof serverId === "string" ? serverId : "");
}

function useRoutedOutboundSample() {
  routedForm.outboundText = sampleRoutedOutboundText();
}

function parseStepsText(): AgentChangeSetStepCreateRequest[] {
  const parsed = JSON.parse(form.stepsText || "[]") as unknown;
  if (!Array.isArray(parsed) || parsed.length === 0) {
    throw new Error("Steps must be a non-empty JSON array.");
  }

  parsed.forEach((step, index) => {
    if (!isRecord(step)) {
      throw new Error(`Step ${index + 1} must be a JSON object.`);
    }
    if (typeof step.server_id !== "string" || !step.server_id.trim()) {
      throw new Error(`Step ${index + 1} server_id is required.`);
    }
    if (!isRecord(step.forward)) {
      throw new Error(`Step ${index + 1} forward command is required.`);
    }
    if (step.rollback !== undefined && step.rollback !== null && !isRecord(step.rollback)) {
      throw new Error(`Step ${index + 1} rollback must be an object or null.`);
    }
  });

  return parsed as AgentChangeSetStepCreateRequest[];
}

function parseJsonObject(text: string, label: string): Record<string, unknown> {
  const source = text.trim();
  if (!source) {
    throw new Error(`${label} is required.`);
  }
  const parsed = JSON.parse(source) as unknown;
  if (!isRecord(parsed)) {
    throw new Error(`${label} must be a JSON object.`);
  }
  return parsed;
}

function parseOptionalJsonObject(text: string, label: string): Record<string, unknown> | null {
  return text.trim() ? parseJsonObject(text, label) : null;
}

function optionalText(value: string) {
  const normalized = value.trim();
  return normalized ? normalized : null;
}

function splitTextList(value: string) {
  const seen = new Set<string>();
  return value
    .split(/[\n,]+/)
    .map((item) => item.trim())
    .filter((item) => {
      if (!item) {
        return false;
      }
      const key = item.toLowerCase();
      if (seen.has(key)) {
        return false;
      }
      seen.add(key);
      return true;
    });
}

function sampleStepsText(serverId: string) {
  const steps: AgentChangeSetStepCreateRequest[] = [
    {
      server_id: serverId,
      label: "Read system info",
      forward: {
        method: "GET",
        path: "/api/child/system/info",
      },
      rollback: null,
    },
  ];
  return JSON.stringify(steps, null, 2);
}

function sampleRoutedOutboundText() {
  return JSON.stringify(
    {
      protocol: "freedom",
      settings: {
        domainStrategy: "UseIPv4",
      },
    },
    null,
    2,
  );
}

function commandText(command: AgentCommandCreateRequest) {
  const method = command.method || "GET";
  const target = command.query ? `${command.path}?${command.query}` : command.path;
  return `${method} ${target}`;
}

function commandStatusColor(command?: AgentCommand | null) {
  return command ? commandStatusMeta[command.status].color : "grey";
}

function commandStatusIcon(command?: AgentCommand | null) {
  return command ? commandStatusMeta[command.status].icon : "mdi-dots-horizontal-circle-outline";
}

function commandStatusText(command?: AgentCommand | null) {
  return command ? command.status : "not queued";
}

function serverName(serverId: string) {
  return servers.value.find((server) => server.id === serverId)?.name ?? "Unknown server";
}

function stepBodyText(command: AgentCommandCreateRequest) {
  if (command.body === undefined || command.body === null) {
    return "";
  }
  return typeof command.body === "string" ? command.body : JSON.stringify(command.body);
}

function formatDate(value: string) {
  return value.replace("T", " ").slice(0, 19);
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return Boolean(value) && typeof value === "object" && !Array.isArray(value);
}

function readableError(error: unknown) {
  return error instanceof Error ? error.message : "Request failed.";
}
</script>

<template>
  <div class="page-shell">
    <section class="page-heading">
      <div>
        <div class="eyebrow">Changes</div>
        <h1 class="page-title">Change sets and rollback</h1>
      </div>

      <v-tooltip text="Refresh change sets">
        <template #activator="{ props }">
          <v-btn
            v-bind="props"
            :loading="loading"
            icon="mdi-refresh"
            variant="text"
            @click="refresh"
          />
        </template>
      </v-tooltip>
    </section>

    <v-alert
      v-if="errorMessage"
      class="status-alert"
      density="comfortable"
      type="error"
      variant="tonal"
    >
      {{ errorMessage }}
    </v-alert>
    <v-alert
      v-if="successMessage"
      class="status-alert"
      color="success"
      density="comfortable"
      variant="tonal"
    >
      {{ successMessage }}
    </v-alert>
    <v-alert
      v-for="warning in warnings"
      :key="warning"
      class="status-alert"
      color="warning"
      density="comfortable"
      variant="tonal"
    >
      {{ warning }}
    </v-alert>

    <section class="change-layout">
      <v-sheet class="section-surface change-plan-surface" border>
        <div class="section-head">
          <div>
            <div class="section-title">Plan</div>
            <div class="section-subtitle">Forward and rollback command sequence</div>
          </div>
          <v-progress-circular
            v-if="loading"
            color="primary"
            indeterminate
            size="24"
            width="3"
          />
        </div>

        <v-tabs v-model="planMode" class="change-plan-tabs" color="primary" density="comfortable">
          <v-tab prepend-icon="mdi-routes" value="routed">Routed outbound</v-tab>
          <v-tab prepend-icon="mdi-code-json" value="raw">Raw steps</v-tab>
        </v-tabs>

        <v-window v-model="planMode" class="change-mode-window">
          <v-window-item value="routed">
            <v-form class="change-form" @submit.prevent="submitRoutedOutbound">
              <v-select
                v-model="routedForm.server_id"
                :disabled="serverOptions.length === 0"
                :items="serverOptions"
                density="comfortable"
                label="Server"
                prepend-inner-icon="mdi-server-network"
                variant="outlined"
              />

              <div class="form-row">
                <v-text-field
                  v-model="routedForm.inbound_tag"
                  density="comfortable"
                  label="Parent inbound tag"
                  prepend-inner-icon="mdi-transit-connection-variant"
                  variant="outlined"
                />
                <v-select
                  v-model="routedForm.inbound_protocol"
                  :items="inboundProtocolOptions"
                  density="comfortable"
                  label="Protocol"
                  prepend-inner-icon="mdi-shield-key-outline"
                  variant="outlined"
                />
              </div>

              <div class="form-row">
                <v-text-field
                  v-model="routedForm.label"
                  density="comfortable"
                  label="Label"
                  prepend-inner-icon="mdi-label-outline"
                  variant="outlined"
                />
                <v-text-field
                  v-model="routedForm.parent_ref"
                  density="comfortable"
                  label="Parent ref"
                  prepend-inner-icon="mdi-source-branch"
                  variant="outlined"
                />
              </div>

              <v-text-field
                v-model="routedForm.node_name"
                density="comfortable"
                label="Node name"
                prepend-inner-icon="mdi-nodejs"
                variant="outlined"
              />

              <div class="form-row">
                <v-text-field
                  v-model="routedForm.admin_username"
                  density="comfortable"
                  label="Admin username"
                  prepend-inner-icon="mdi-account-key-outline"
                  variant="outlined"
                />
                <v-text-field
                  v-model="routedForm.admin_email"
                  density="comfortable"
                  label="Admin email"
                  prepend-inner-icon="mdi-email-outline"
                  variant="outlined"
                />
              </div>

              <div class="form-row">
                <v-text-field
                  v-model="routedForm.outbound_tag"
                  density="comfortable"
                  label="Outbound tag"
                  prepend-inner-icon="mdi-tag-outline"
                  variant="outlined"
                />
                <v-text-field
                  v-model="routedForm.marktag"
                  density="comfortable"
                  label="Route mark"
                  prepend-inner-icon="mdi-sign-direction"
                  variant="outlined"
                />
              </div>

              <v-textarea
                v-model="routedForm.outboundText"
                auto-grow
                class="config-editor"
                density="comfortable"
                label="Outbound JSON"
                prepend-inner-icon="mdi-code-json"
                rows="9"
                variant="outlined"
              />

              <v-textarea
                v-model="routedForm.clientText"
                auto-grow
                class="config-editor"
                density="comfortable"
                label="Client JSON"
                prepend-inner-icon="mdi-account-cog-outline"
                rows="4"
                variant="outlined"
              />

              <v-textarea
                v-model="routedForm.sniffingExcludeDomainsText"
                auto-grow
                density="comfortable"
                label="Sniffing excludes"
                prepend-inner-icon="mdi-web-minus"
                rows="2"
                variant="outlined"
              />

              <div class="change-toggle-row routed-toggle-row">
                <v-switch
                  v-model="routedForm.rollback_on_failure"
                  color="primary"
                  density="comfortable"
                  hide-details
                  label="Rollback on failure"
                />
                <v-switch
                  v-model="routedForm.dispatch"
                  color="primary"
                  density="comfortable"
                  hide-details
                  label="Dispatch now"
                />
                <v-switch
                  v-model="routedForm.add_reality_sniffing_excludes"
                  color="primary"
                  density="comfortable"
                  hide-details
                  label="Reality SNI excludes"
                />
                <v-text-field
                  v-model.number="routedForm.command_timeout_ms"
                  density="comfortable"
                  hide-details
                  label="Timeout ms"
                  min="1"
                  prepend-inner-icon="mdi-timer-outline"
                  type="number"
                  variant="outlined"
                />
              </div>

              <div class="change-action-row">
                <v-btn
                  :loading="savingAction === 'routed'"
                  color="primary"
                  prepend-icon="mdi-plus"
                  type="submit"
                  variant="flat"
                >
                  Create plan
                </v-btn>
                <v-btn prepend-icon="mdi-code-json" variant="tonal" @click="useRoutedOutboundSample">
                  Sample
                </v-btn>
              </div>
            </v-form>
          </v-window-item>

          <v-window-item value="raw">
            <v-form class="change-form" @submit.prevent="submitChangeSet">
              <v-text-field
                v-model="form.name"
                density="comfortable"
                label="Name"
                prepend-inner-icon="mdi-clipboard-text-outline"
                variant="outlined"
              />
              <v-textarea
                v-model="form.description"
                auto-grow
                density="comfortable"
                label="Description"
                prepend-inner-icon="mdi-text-box-outline"
                rows="2"
                variant="outlined"
              />

              <div class="change-toggle-row">
                <v-switch
                  v-model="form.rollback_on_failure"
                  color="primary"
                  density="comfortable"
                  hide-details
                  label="Rollback on failure"
                />
                <v-switch
                  v-model="form.dispatch"
                  color="primary"
                  density="comfortable"
                  hide-details
                  label="Dispatch now"
                />
              </div>

              <v-select
                :disabled="serverOptions.length === 0"
                :items="serverOptions"
                density="comfortable"
                label="Sample server"
                prepend-inner-icon="mdi-server-network"
                variant="outlined"
                @update:model-value="useServerSample"
              />

              <v-textarea
                v-model="form.stepsText"
                auto-grow
                class="config-editor"
                density="comfortable"
                label="Steps JSON"
                prepend-inner-icon="mdi-code-json"
                rows="16"
                variant="outlined"
              />

              <div class="change-action-row">
                <v-btn
                  :loading="savingAction === 'create'"
                  color="primary"
                  prepend-icon="mdi-plus"
                  type="submit"
                  variant="flat"
                >
                  Create
                </v-btn>
                <v-btn prepend-icon="mdi-code-json" variant="tonal" @click="useSampleSteps">
                  Sample
                </v-btn>
              </div>
            </v-form>
          </v-window-item>
        </v-window>
      </v-sheet>

      <v-sheet class="section-surface change-runs-surface" border>
        <div class="section-head">
          <div>
            <div class="section-title">Runs</div>
            <div class="section-subtitle">{{ changeSets.length }} change sets</div>
          </div>
          <v-chip color="success" size="small" variant="tonal">Free edition</v-chip>
        </div>

        <div v-if="changeSets.length === 0" class="empty-state">
          <v-icon icon="mdi-clipboard-text-clock-outline" size="34" />
          <div>No change sets yet.</div>
        </div>

        <template v-else>
          <v-list class="change-run-list" density="compact" lines="two">
            <v-list-item
              v-for="changeSet in changeSets"
              :key="changeSet.id"
              :active="changeSet.id === selectedChangeSetId"
              rounded="lg"
              @click="selectedChangeSetId = changeSet.id"
            >
              <template #prepend>
                <v-icon
                  :color="changeStatusMeta[changeSet.status].color"
                  :icon="changeStatusMeta[changeSet.status].icon"
                />
              </template>
              <v-list-item-title>{{ changeSet.name }}</v-list-item-title>
              <v-list-item-subtitle>
                {{ changeSet.steps.length }} steps - {{ formatDate(changeSet.updated_at) }}
              </v-list-item-subtitle>
              <template #append>
                <v-chip
                  :color="changeStatusMeta[changeSet.status].color"
                  density="comfortable"
                  size="small"
                  variant="tonal"
                >
                  {{ changeSet.status }}
                </v-chip>
              </template>
            </v-list-item>
          </v-list>

          <v-divider class="command-divider" />

          <div v-if="selectedChangeSet" class="change-detail">
            <div class="section-head">
              <div>
                <div class="section-title">{{ selectedChangeSet.name }}</div>
                <div class="section-subtitle">
                  {{ selectedChangeSet.description || selectedChangeSet.id }}
                </div>
              </div>
              <v-chip
                :color="changeStatusMeta[selectedChangeSet.status].color"
                density="comfortable"
                variant="tonal"
              >
                {{ selectedChangeSet.status }}
              </v-chip>
            </div>

            <div class="change-control-row">
              <v-btn
                :loading="savingAction === 'dispatch'"
                prepend-icon="mdi-send"
                variant="tonal"
                @click="dispatchSelected"
              >
                Dispatch
              </v-btn>
              <v-text-field
                v-model="form.rollbackReason"
                density="comfortable"
                hide-details
                label="Rollback reason"
                prepend-inner-icon="mdi-message-text-outline"
                variant="outlined"
              />
              <v-btn
                :loading="savingAction === 'rollback'"
                color="warning"
                prepend-icon="mdi-undo-variant"
                variant="tonal"
                @click="rollbackSelected"
              >
                Rollback
              </v-btn>
            </div>

            <div class="change-step-list">
              <v-sheet
                v-for="step in selectedChangeSet.steps"
                :key="step.id"
                class="change-step-item"
                border
              >
                <div class="change-step-title-row">
                  <div>
                    <div class="compact-title">{{ step.sequence }}. {{ step.label }}</div>
                    <div class="section-subtitle">{{ serverName(step.server_id) }}</div>
                  </div>
                  <v-chip color="grey" density="comfortable" size="small" variant="tonal">
                    {{ step.server_id.slice(0, 8) }}
                  </v-chip>
                </div>

                <div class="change-command-pair">
                  <div>
                    <div class="detail-label">Forward</div>
                    <div class="detail-value">{{ commandText(step.forward) }}</div>
                    <div v-if="stepBodyText(step.forward)" class="change-body-snippet">
                      {{ stepBodyText(step.forward) }}
                    </div>
                    <v-chip
                      :color="commandStatusColor(step.forward_command)"
                      :prepend-icon="commandStatusIcon(step.forward_command)"
                      class="change-command-chip"
                      density="comfortable"
                      size="small"
                      variant="tonal"
                    >
                      {{ commandStatusText(step.forward_command) }}
                    </v-chip>
                  </div>
                  <div>
                    <div class="detail-label">Rollback</div>
                    <div class="detail-value">
                      {{ step.rollback ? commandText(step.rollback) : "none" }}
                    </div>
                    <div
                      v-if="step.rollback && stepBodyText(step.rollback)"
                      class="change-body-snippet"
                    >
                      {{ stepBodyText(step.rollback) }}
                    </div>
                    <v-chip
                      :color="commandStatusColor(step.rollback_command)"
                      :prepend-icon="commandStatusIcon(step.rollback_command)"
                      class="change-command-chip"
                      density="comfortable"
                      size="small"
                      variant="tonal"
                    >
                      {{ commandStatusText(step.rollback_command) }}
                    </v-chip>
                  </div>
                </div>
              </v-sheet>
            </div>

            <div v-if="lastCommandsJson" class="change-command-output">
              <div class="section-title compact-title">Last commands</div>
              <pre class="command-json">{{ lastCommandsJson }}</pre>
            </div>
          </div>
        </template>
      </v-sheet>
    </section>
  </div>
</template>

// frontend/src/react/views/ChangesView.tsx
import { useEffect, useRef, useState } from "react";
import { Alert, Button, Card, Checkbox, Col, Descriptions, Empty, Form, Input, Modal, Row, Select, Space, Switch, Table, Tabs, Tag, Typography } from "antd";
import { PlusOutlined, ReloadOutlined, RollbackOutlined, SendOutlined } from "@ant-design/icons";
import { changeSetActions, type AgentChangeSet, type AgentChangeSetStatus, type AgentChangeSetStepCreateRequest } from "../../domain/changes";
import type { AgentCommand, AgentCommandCreateRequest, ServerSummary } from "../../domain/inventory";
import { listServers } from "../../services/inventory";
import { acceptChangeSet, createChangeSet, createRoutedOutboundChangeSet, dispatchChangeSet, listChangeSets, rollbackChangeSet } from "../../services/changes";
import CommandInspector from "../components/CommandInspector";
import StrictInputNumber from "../components/StrictInputNumber";

export interface ChangesViewProps {
  onCommands?: (commands: AgentCommand[]) => void;
  onUpdated?: () => void;
}
type Action = "create" | "routed" | "dispatch" | "rollback" | "accept" | "";
const protocols = ["vless", "vmess", "trojan", "shadowsocks", "anytls", "snell", "mieru", "hysteria", "socks", "http"];
const statusColors: Record<AgentChangeSetStatus, string> = {
  planned: "default", dispatched: "processing", rollback_queued: "warning", succeeded: "success", failed: "error",
  rolled_back: "success", rollback_failed: "error", rollback_incomplete: "warning", cancelled: "default", accepted: "success", needs_review: "warning",
};
const sampleOutbound = () => JSON.stringify({ protocol: "freedom", settings: { domainStrategy: "UseIPv4" } }, null, 2);
const sampleSteps = (serverId: string) => JSON.stringify([{ server_id: serverId, label: "Read system info", forward: { method: "GET", path: "/api/child/system/info" }, rollback: null }], null, 2);
const optionalText = (value: string) => value.trim() || null;
const isRecord = (value: unknown): value is Record<string, unknown> => Boolean(value) && typeof value === "object" && !Array.isArray(value);
function jsonObject(text: string, label: string) {
  if (!text.trim()) throw new Error(`${label} is required.`);
  const value: unknown = JSON.parse(text);
  if (!isRecord(value)) throw new Error(`${label} must be a JSON object.`);
  return value;
}
function stepsFrom(text: string): AgentChangeSetStepCreateRequest[] {
  const value: unknown = JSON.parse(text || "[]");
  if (!Array.isArray(value) || !value.length) throw new Error("Steps must be a non-empty JSON array.");
  value.forEach((step, index) => {
    if (!isRecord(step)) throw new Error(`Step ${index + 1} must be a JSON object.`);
    if (typeof step.server_id !== "string" || !step.server_id.trim()) throw new Error(`Step ${index + 1} server_id is required.`);
    if (!isRecord(step.forward)) throw new Error(`Step ${index + 1} forward command is required.`);
    if (step.rollback !== undefined && step.rollback !== null && !isRecord(step.rollback)) throw new Error(`Step ${index + 1} rollback must be an object or null.`);
  });
  return value as AgentChangeSetStepCreateRequest[];
}
function splitDomains(text: string) {
  const seen = new Set<string>();
  return text.split(/[\n,]+/).map((item) => item.trim()).filter((item) => {
    if (!item || seen.has(item.toLowerCase())) return false;
    seen.add(item.toLowerCase());
    return true;
  });
}
function commandText(command: AgentCommandCreateRequest) {
  return `${command.method || "GET"} ${command.path}${command.query ? `?${command.query}` : ""}`;
}
function commandBody(command: AgentCommandCreateRequest) {
  return command.body == null ? "" : typeof command.body === "string" ? command.body : JSON.stringify(command.body);
}
function CommandSummary({ request, command }: { request?: AgentCommandCreateRequest | null; command?: AgentCommand | null }) {
  const color = command?.status === "succeeded" ? "success" : command?.status === "failed" ? "error" : command?.status === "leased" ? "processing" : command?.status === "pending" ? "warning" : "default";
  return <Space orientation="vertical" size="small" style={{ maxWidth: "100%" }}>
    <Typography.Text code style={{ overflowWrap: "anywhere" }}>{request ? commandText(request) : "none"}</Typography.Text>
    {request && commandBody(request) && <Typography.Paragraph style={{ overflowWrap: "anywhere", whiteSpace: "pre-wrap" }}>{commandBody(request)}</Typography.Paragraph>}
    <Tag color={color}>{command?.status ?? "not queued"}</Tag>
  </Space>;
}

export default function ChangesView(props: ChangesViewProps) {
  const [servers, setServers] = useState<ServerSummary[]>([]);
  const [changes, setChanges] = useState<AgentChangeSet[]>([]);
  const [selectedId, setSelectedId] = useState("");
  const [loading, setLoading] = useState(false);
  const [saving, setSaving] = useState<Action>("");
  const [error, setError] = useState("");
  const [success, setSuccess] = useState("");
  const [warnings, setWarnings] = useState<string[]>([]);
  const [lastCommands, setLastCommands] = useState<AgentCommand[]>([]);
  const [planMode, setPlanMode] = useState("routed");
  const [acceptId, setAcceptId] = useState("");
  const [acceptanceReason, setAcceptanceReason] = useState("");
  const [acceptanceConfirmed, setAcceptanceConfirmed] = useState(false);
  const [form, setForm] = useState({ name: "", description: "", rollback_on_failure: true, dispatch: false, rollbackReason: "", stepsText: sampleSteps("") });
  const [routed, setRouted] = useState({ server_id: "", inbound_tag: "", inbound_protocol: "vless", label: "direct", parent_ref: "", admin_username: "admin", admin_email: "", outbound_tag: "", marktag: "", node_name: "", outboundText: sampleOutbound(), clientText: "", sniffingExcludeDomainsText: "", add_reality_sniffing_excludes: true, rollback_on_failure: true, dispatch: false, command_timeout_ms: 30000 });
  const refreshRevision = useRef(0);
  const refreshOwner = useRef(0);
  const refreshBusy = useRef(false);
  const mutationBusy = useRef(false);
  const mounted = useRef(true);
  const live = useRef({ changes, selectedId, saving, acceptId, props });
  live.current = { changes, selectedId, saving, acceptId, props };
  const selected = changes.find((change) => change.id === selectedId) ?? null;
  const actions = changeSetActions(selected);
  const options = servers.map((server) => ({ label: server.name, value: server.id }));
  const patchForm = (patch: Partial<typeof form>) => setForm((value) => ({ ...value, ...patch }));
  const patchRouted = (patch: Partial<typeof routed>) => setRouted((value) => ({ ...value, ...patch }));

  async function refresh(background = false, replace = false) {
    if (refreshBusy.current && !replace) return;
    const revision = ++refreshRevision.current;
    refreshOwner.current = revision;
    refreshBusy.current = true;
    setLoading(true);
    if (!background) setError("");
    try {
      const [inventory, response] = await Promise.all([listServers(), listChangeSets()]);
      if (!mounted.current || revision !== refreshRevision.current) return;
      setServers(inventory);
      setChanges(response.change_sets);
      setForm((value) => value.stepsText.includes('"server_id": ""') && inventory[0] ? { ...value, stepsText: sampleSteps(inventory[0].id) } : value);
      setRouted((value) => inventory.some((server) => server.id === value.server_id) ? value : { ...value, server_id: inventory[0]?.id ?? "" });
      setSelectedId((value) => response.change_sets.some((change) => change.id === value) ? value : response.change_sets[0]?.id ?? "");
    } catch (failure) {
      if (mounted.current && !background && revision === refreshRevision.current) setError(failure instanceof Error ? failure.message : "Request failed.");
    } finally {
      if (refreshOwner.current === revision) {
        refreshBusy.current = false;
        if (mounted.current) setLoading(false);
      }
    }
  }
  useEffect(() => {
    mounted.current = true;
    void refresh(false, true);
    const timer = window.setInterval(() => {
      const current = live.current;
      const active = current.changes.some((change) => ["dispatched", "rollback_queued"].includes(change.status) || change.blocking_command_ids?.length);
      if (active && !refreshBusy.current && !mutationBusy.current && !current.acceptId) void refresh(true);
    }, 2500);
    return () => { mounted.current = false; refreshRevision.current += 1; window.clearInterval(timer); };
  }, []);

  function remember(change: AgentChangeSet, commands?: AgentCommand[], responseWarnings?: string[]) {
    refreshRevision.current += 1;
    setChanges((rows) => rows.some((item) => item.id === change.id) ? rows.map((item) => item.id === change.id ? change : item) : [change, ...rows]);
    setSelectedId(change.id);
    if (commands) { setLastCommands(commands); live.current.props.onCommands?.(commands); }
    if (responseWarnings) setWarnings(responseWarnings);
    live.current.props.onUpdated?.();
  }
  async function mutate(action: Exclude<Action, "">, work: () => Promise<void>) {
    if (mutationBusy.current) return;
    mutationBusy.current = true;
    setSaving(action);
    setError("");
    setSuccess("");
    setWarnings([]);
    try { await work(); }
    catch (failure) { if (mounted.current) setError(failure instanceof Error ? failure.message : "Request failed."); }
    finally { mutationBusy.current = false; if (mounted.current) setSaving(""); }
  }
  function submitRouted() {
    void mutate("routed", async () => {
      if (!routed.server_id.trim()) throw new Error("Server is required.");
      if (!routed.inbound_tag.trim()) throw new Error("Inbound tag is required.");
      if (!routed.label.trim()) throw new Error("Label is required.");
      if (!Number.isFinite(routed.command_timeout_ms) || routed.command_timeout_ms <= 0) throw new Error("Timeout must be greater than zero.");
      const response = await createRoutedOutboundChangeSet({
        server_id: routed.server_id.trim(), inbound_tag: routed.inbound_tag.trim(), inbound_protocol: routed.inbound_protocol.trim() || "vless", label: routed.label.trim(),
        outbound: jsonObject(routed.outboundText, "Outbound JSON"), parent_ref: optionalText(routed.parent_ref), admin_username: routed.admin_username.trim() || "admin", admin_email: optionalText(routed.admin_email),
        outbound_tag: optionalText(routed.outbound_tag), marktag: optionalText(routed.marktag), node_name: optionalText(routed.node_name), client: routed.clientText.trim() ? jsonObject(routed.clientText, "Client JSON") : null,
        sniffing_exclude_domains: splitDomains(routed.sniffingExcludeDomainsText), add_reality_sniffing_excludes: routed.add_reality_sniffing_excludes,
        command_timeout_ms: routed.command_timeout_ms, rollback_on_failure: routed.rollback_on_failure, dispatch: routed.dispatch,
      });
      if (!mounted.current) return;
      remember(response.change_set, response.commands, response.warnings);
      setSuccess(response.commands.length ? `Created routed outbound plan and dispatched ${response.commands.length} commands.` : "Routed outbound change set created.");
      await refresh();
    });
  }
  function submitRaw() {
    void mutate("create", async () => {
      if (!form.name.trim()) throw new Error("Name is required.");
      const response = await createChangeSet({ name: form.name.trim(), description: form.description.trim(), rollback_on_failure: form.rollback_on_failure, dispatch: form.dispatch, steps: stepsFrom(form.stepsText) });
      if (!mounted.current) return;
      remember(response.change_set, response.commands, response.warnings);
      setSuccess(response.commands.length ? `Created and dispatched ${response.commands.length} commands.` : "Change set created.");
      patchForm({ name: "", description: "", rollback_on_failure: true, dispatch: false });
      await refresh();
    });
  }
  function dispatchSelected() {
    if (!selected || !actions.dispatch) return;
    void mutate("dispatch", async () => {
      const response = await dispatchChangeSet(selected.id);
      if (!mounted.current) return;
      remember(response.change_set, response.commands, response.warnings);
      setSuccess(response.commands.length ? `Dispatched ${response.commands.length} commands.` : "No new forward commands.");
      await refresh();
    });
  }
  function rollbackSelected() {
    if (!selected || !actions.rollback) return;
    void mutate("rollback", async () => {
      const response = await rollbackChangeSet(selected.id, { reason: form.rollbackReason.trim() });
      if (!mounted.current) return;
      remember(response.change_set, response.commands, response.warnings);
      setSuccess(response.commands.length ? `Queued ${response.commands.length} rollback commands.` : "No new rollback commands.");
      await refresh();
    });
  }
  function acceptSelected() {
    const change = changes.find((item) => item.id === acceptId);
    if (!changeSetActions(change ?? null).accept || !acceptanceConfirmed || !acceptanceReason.trim()) return;
    void mutate("accept", async () => {
      const response = await acceptChangeSet(acceptId, acceptanceReason.trim());
      if (!mounted.current) return;
      remember(response.change_set, response.commands, response.warnings);
      setAcceptId("");
      setSuccess("Current state accepted. Node reservations released.");
      await refresh();
    });
  }

  const routedForm = <Form layout="vertical" onFinish={submitRouted} disabled={Boolean(saving)}>
    <Form.Item label="Server"><Select aria-label="Server" value={routed.server_id || undefined} options={options} disabled={!options.length || Boolean(saving)} onChange={(server_id) => patchRouted({ server_id })} /></Form.Item>
    <Row gutter={16}>
      <Col xs={24} sm={12}><Form.Item label="Parent inbound tag"><Input aria-label="Parent inbound tag" value={routed.inbound_tag} onChange={(event) => patchRouted({ inbound_tag: event.target.value })} /></Form.Item></Col>
      <Col xs={24} sm={12}><Form.Item label="Protocol"><Select aria-label="Protocol" value={routed.inbound_protocol} options={protocols.map((value) => ({ value, label: value }))} onChange={(inbound_protocol) => patchRouted({ inbound_protocol })} /></Form.Item></Col>
      {([
        ["label", "Label"], ["parent_ref", "Parent ref"], ["node_name", "Node name"], ["admin_username", "Admin username"], ["admin_email", "Admin email"], ["outbound_tag", "Outbound tag"], ["marktag", "Route mark"],
      ] as const).map(([field, label]) => <Col xs={24} sm={12} key={field}><Form.Item label={label}><Input aria-label={label} value={routed[field]} onChange={(event) => patchRouted({ [field]: event.target.value })} /></Form.Item></Col>)}
    </Row>
    <Form.Item label="Outbound JSON"><Input.TextArea aria-label="Outbound JSON" value={routed.outboundText} rows={9} spellCheck={false} onChange={(event) => patchRouted({ outboundText: event.target.value })} /></Form.Item>
    <Form.Item label="Client JSON"><Input.TextArea aria-label="Client JSON" value={routed.clientText} rows={4} spellCheck={false} onChange={(event) => patchRouted({ clientText: event.target.value })} /></Form.Item>
    <Form.Item label="Sniffing excludes"><Input.TextArea aria-label="Sniffing excludes" value={routed.sniffingExcludeDomainsText} rows={2} onChange={(event) => patchRouted({ sniffingExcludeDomainsText: event.target.value })} /></Form.Item>
    <Space wrap align="start">
      <Form.Item label="Rollback on failure"><Switch aria-label="Rollback on failure" checked={routed.rollback_on_failure} onChange={(rollback_on_failure) => patchRouted({ rollback_on_failure })} /></Form.Item>
      <Form.Item label="Dispatch now"><Switch aria-label="Dispatch now" checked={routed.dispatch} onChange={(dispatch) => patchRouted({ dispatch })} /></Form.Item>
      <Form.Item label="Reality SNI excludes"><Switch aria-label="Reality SNI excludes" checked={routed.add_reality_sniffing_excludes} onChange={(add_reality_sniffing_excludes) => patchRouted({ add_reality_sniffing_excludes })} /></Form.Item>
      <Form.Item label="Timeout ms"><StrictInputNumber aria-label="Timeout ms" aria-valuemin={1} value={routed.command_timeout_ms} onChange={(value) => patchRouted({ command_timeout_ms: value ?? Number.NaN })} /></Form.Item>
    </Space>
    <Space><Button type="primary" aria-label="Create plan" icon={<PlusOutlined />} htmlType="submit" loading={saving === "routed"}>Create plan</Button><Button onClick={() => patchRouted({ outboundText: sampleOutbound() })}>Sample</Button></Space>
  </Form>;
  const rawForm = <Form layout="vertical" onFinish={submitRaw} disabled={Boolean(saving)}>
    <Form.Item label="Name"><Input aria-label="Name" value={form.name} onChange={(event) => patchForm({ name: event.target.value })} /></Form.Item>
    <Form.Item label="Description"><Input.TextArea aria-label="Description" value={form.description} rows={2} onChange={(event) => patchForm({ description: event.target.value })} /></Form.Item>
    <Space wrap><Form.Item label="Rollback on failure"><Switch aria-label="Rollback on failure" checked={form.rollback_on_failure} onChange={(rollback_on_failure) => patchForm({ rollback_on_failure })} /></Form.Item><Form.Item label="Dispatch now"><Switch aria-label="Dispatch now" checked={form.dispatch} onChange={(dispatch) => patchForm({ dispatch })} /></Form.Item></Space>
    <Form.Item label="Sample server"><Select aria-label="Sample server" options={options} disabled={!options.length || Boolean(saving)} onChange={(serverId) => patchForm({ stepsText: sampleSteps(serverId) })} /></Form.Item>
    <Form.Item label="Steps JSON"><Input.TextArea aria-label="Steps JSON" value={form.stepsText} rows={16} spellCheck={false} onChange={(event) => patchForm({ stepsText: event.target.value })} /></Form.Item>
    <Space><Button type="primary" aria-label="Create" htmlType="submit" icon={<PlusOutlined />} loading={saving === "create"}>Create</Button><Button onClick={() => patchForm({ stepsText: sampleSteps(servers[0]?.id ?? "") })}>Sample</Button></Space>
  </Form>;

  return <Space orientation="vertical" size="large" style={{ width: "100%" }}>
    <Space wrap style={{ width: "100%", justifyContent: "space-between" }}><Typography.Title level={2}>Change sets and rollback</Typography.Title><Button aria-label="Refresh change sets" icon={<ReloadOutlined />} loading={loading} onClick={() => void refresh()} /></Space>
    {error && <Alert type="error" title={error} showIcon />}
    {success && <Alert type="success" title={success} showIcon />}
    {warnings.filter((warning) => !selected?.warnings?.includes(warning)).map((warning) => <Alert key={warning} type="warning" title={warning} showIcon />)}
    <Row gutter={[24, 24]}>
      <Col xs={24} xl={10}><Card title="Plan"><Typography.Paragraph type="secondary">Forward and rollback command sequence</Typography.Paragraph><Tabs activeKey={planMode} onChange={setPlanMode} items={[{ key: "routed", label: "Routed outbound", children: routedForm }, { key: "raw", label: "Raw steps", children: rawForm }]} /></Card></Col>
      <Col xs={24} xl={14}><Card title="Runs" extra={<Tag color="success">Free edition</Tag>}>
        <Typography.Paragraph type="secondary">{changes.length} change sets</Typography.Paragraph>
        <Table<AgentChangeSet> rowKey="id" dataSource={changes} loading={loading} pagination={{ pageSize: 8, showSizeChanger: false }} locale={{ emptyText: "No change sets yet." }} scroll={{ x: 440 }} columns={[
          { title: "Change set", key: "name", render: (_, row) => <Button type="link" disabled={Boolean(saving) || Boolean(acceptId)} onClick={() => setSelectedId(row.id)}>{row.name}</Button> },
          { title: "Steps", key: "steps", render: (_, row) => row.steps.length },
          { title: "Updated", key: "updated", render: (_, row) => row.updated_at.replace("T", " ").slice(0, 19) },
          { title: "Status", key: "status", render: (_, row) => <Tag color={statusColors[row.status]}>{row.status.replaceAll("_", " ")}</Tag> },
        ]} />
        {selected ? <Space orientation="vertical" size="middle" style={{ width: "100%" }}>
          <Descriptions title={selected.name} column={1} items={[{ key: "description", label: "Description", children: selected.description || selected.id }, { key: "status", label: "Status", children: <Tag color={statusColors[selected.status]}>{selected.status.replaceAll("_", " ")}</Tag> }]} />
          <Space wrap align="end">
            <Button aria-label="Dispatch" icon={<SendOutlined />} disabled={!actions.dispatch || Boolean(saving)} loading={saving === "dispatch"} onClick={dispatchSelected}>Dispatch</Button>
            <Form.Item label="Rollback reason" style={{ marginBottom: 0 }}><Input aria-label="Rollback reason" value={form.rollbackReason} disabled={Boolean(saving)} onChange={(event) => patchForm({ rollbackReason: event.target.value })} /></Form.Item>
            <Button aria-label={actions.retry ? "Retry rollback" : selected.status === "planned" ? "Cancel plan" : "Rollback"} icon={<RollbackOutlined />} disabled={!actions.rollback || Boolean(saving)} loading={saving === "rollback"} onClick={rollbackSelected}>{actions.retry ? "Retry rollback" : selected.status === "planned" ? "Cancel plan" : "Rollback"}</Button>
            {actions.accept && <Button disabled={Boolean(saving)} onClick={() => { setAcceptanceReason(""); setAcceptanceConfirmed(false); setAcceptId(selected.id); }}>Accept current state</Button>}
          </Space>
          {Boolean(selected.held_server_ids?.length) && <Typography.Text>{selected.held_server_ids?.length} nodes reserved</Typography.Text>}
          {Boolean(selected.blocking_command_ids?.length) && <Alert type="info" title={`Waiting for command results: ${selected.blocking_command_ids?.join(", ")}`} showIcon />}
          {(selected.warnings ?? []).map((warning) => <Alert key={warning} type="warning" title={warning} showIcon />)}
          {selected.rollback_reason && <Typography.Paragraph>{selected.rollback_reason}</Typography.Paragraph>}
          {selected.resolution_reason && <Typography.Paragraph>{selected.resolution_reason}</Typography.Paragraph>}
          {selected.steps.map((step) => <Card key={step.id} size="small" title={`${step.sequence}. ${step.label}`} extra={<Tag>{step.server_id.slice(0, 8)}</Tag>}>
            <Typography.Paragraph type="secondary">{step.server_name || servers.find((server) => server.id === step.server_id)?.name || "Unknown server"}{step.archived ? " (archived)" : ""}</Typography.Paragraph>
            <Descriptions column={{ xs: 1, sm: 2 }} items={[{ key: "forward", label: "Forward", children: <CommandSummary request={step.forward} command={step.forward_command} /> }, { key: "rollback", label: "Rollback", children: <CommandSummary request={step.rollback} command={step.rollback_command} /> }]} />
            <CommandInspector commands={[...new Map([step.forward_command, ...(step.rollback_history ?? []), step.rollback_command].filter((command): command is AgentCommand => Boolean(command)).map((command) => [command.id, command])).values()]} streamFramesByCommand={{}} />
          </Card>)}
          {lastCommands.length > 0 && <Card size="small" title="Last commands"><CommandInspector commands={lastCommands} streamFramesByCommand={{}} /></Card>}
        </Space> : changes.length > 0 ? <Empty description="Select a change set" /> : null}
      </Card></Col>
    </Row>
    <Modal title="Accept current state" open={Boolean(acceptId)} onCancel={() => { if (!saving) setAcceptId(""); }} closable={!saving} mask={{ closable: !saving }} keyboard={!saving} onOk={acceptSelected} okText="Accept state" confirmLoading={saving === "accept"} okButtonProps={{ disabled: !acceptanceConfirmed || !acceptanceReason.trim() || Boolean(saving) }} cancelButtonProps={{ disabled: Boolean(saving) }}>
      {error && <Alert type="error" title={error} showIcon />}
      <Form layout="vertical" disabled={Boolean(saving)}><Form.Item label="Resolution reason"><Input.TextArea aria-label="Resolution reason" rows={3} value={acceptanceReason} onChange={(event) => setAcceptanceReason(event.target.value)} /></Form.Item><Checkbox checked={acceptanceConfirmed} onChange={(event) => setAcceptanceConfirmed(event.target.checked)}>I have checked the nodes and accept any remaining changes</Checkbox></Form>
    </Modal>
  </Space>;
}
