// frontend/src/components/AutoSpeedRuleEditor.vue
<script setup lang="ts">
import { computed, ref, toRaw, watch } from "vue";
import { newAutoSpeedRule, validAutoSpeedRule, type AutoSpeedRule } from "../domain/auto-speed";

const props = defineProps<{ modelValue: AutoSpeedRule[]; disabled?: boolean }>();
const emit = defineEmits<{ "update:modelValue": [value: AutoSpeedRule[]]; valid: [value: boolean] }>();
const rows = ref<(AutoSpeedRule & { key: number })[]>([]);
let key = 0;
let published: AutoSpeedRule[] | undefined;
watch(() => props.modelValue, value => {
  if (toRaw(value) !== published) rows.value = value.map(rule => ({ ...rule, key: ++key }));
}, { immediate: true });
const valid = computed(() => rows.value.length <= 100 && rows.value.every(validAutoSpeedRule));
watch(valid, value => emit("valid", value), { immediate: true });
function publish() {
  published = rows.value.map(({ key: _key, ...rule }) => rule);
  emit("update:modelValue", published);
}
function add() {
  if (props.disabled || rows.value.length >= 100) return;
  rows.value.push({ ...newAutoSpeedRule(), key: ++key });
  publish();
}
function remove(index: number) { rows.value.splice(index, 1); publish(); }
function move(index: number, direction: number) {
  const next = index + direction;
  if (next < 0 || next >= rows.value.length) return;
  [rows.value[index], rows.value[next]] = [rows.value[next], rows.value[index]];
  publish();
}
</script>

<template>
  <section class="auto-speed-editor" aria-label="Automatic limits">
    <div class="rule-toolbar">
      <h3>Automatic limits</h3>
      <v-spacer />
      <v-tooltip text="Add automatic rule"><template #activator="{ props: tip }"><v-btn v-bind="tip" icon="mdi-plus" variant="text" aria-label="Add automatic rule" :disabled="disabled || rows.length >= 100" @click="add" /></template></v-tooltip>
    </div>
    <section v-for="(rule, index) in rows" :key="rule.key" class="automatic-rule" :aria-label="`Automatic rule ${index + 1}`">
      <div class="rule-toolbar">
        <v-btn-toggle v-model="rule.type" mandatory variant="outlined" density="compact" :disabled="disabled" @update:model-value="publish">
          <v-btn value="sustained">Sustained</v-btn><v-btn value="burst">Burst</v-btn>
        </v-btn-toggle>
        <v-spacer />
        <div class="rule-actions">
          <v-tooltip text="Move rule up"><template #activator="{ props: tip }"><v-btn v-bind="tip" icon="mdi-arrow-up" variant="text" size="small" :aria-label="`Move rule ${index + 1} up`" :disabled="disabled || index === 0" @click="move(index, -1)" /></template></v-tooltip>
          <v-tooltip text="Move rule down"><template #activator="{ props: tip }"><v-btn v-bind="tip" icon="mdi-arrow-down" variant="text" size="small" :aria-label="`Move rule ${index + 1} down`" :disabled="disabled || index === rows.length - 1" @click="move(index, 1)" /></template></v-tooltip>
          <v-tooltip text="Remove automatic rule"><template #activator="{ props: tip }"><v-btn v-bind="tip" icon="mdi-delete-outline" variant="text" size="small" :aria-label="`Remove automatic rule ${index + 1}`" :disabled="disabled" @click="remove(index)" /></template></v-tooltip>
        </div>
      </div>
      <div class="rule-fields">
        <v-text-field v-model.number="rule.threshold_mbps" label="Trigger Mbps" type="number" min="0.000008" step="any" variant="outlined" density="compact" hide-details :disabled="disabled" @update:model-value="publish" />
        <v-text-field v-model.number="rule.sustained_seconds" label="Hold seconds" type="number" min="1" max="86400" step="1" variant="outlined" density="compact" hide-details :disabled="disabled" @update:model-value="publish" />
        <v-text-field v-model.number="rule.limit_mbps" label="Cap Mbps" type="number" min="0.000008" step="any" variant="outlined" density="compact" hide-details :disabled="disabled" @update:model-value="publish" />
        <v-text-field v-model.number="rule.limit_duration" label="Duration seconds" type="number" min="1" max="86400" step="1" variant="outlined" density="compact" hide-details :disabled="disabled" @update:model-value="publish" />
        <v-text-field v-if="rule.type === 'burst'" v-model.number="rule.window_seconds" label="Window seconds" type="number" :min="rule.sustained_seconds" max="86400" step="1" variant="outlined" density="compact" hide-details :disabled="disabled" @update:model-value="publish" />
        <v-text-field v-if="rule.type === 'burst'" v-model.number="rule.burst_count" label="Bursts" type="number" min="1" max="10000" step="1" variant="outlined" density="compact" hide-details :disabled="disabled" @update:model-value="publish" />
      </div>
      <p v-if="!validAutoSpeedRule(rule)" class="text-error">Invalid automatic limit rule</p>
    </section>
    <p v-if="!rows.length" class="rules-empty">No automatic rules</p>
  </section>
</template>

<style scoped>
.auto-speed-editor { min-width: 0; letter-spacing: 0; }
.rule-toolbar { display: flex; align-items: center; flex-wrap: wrap; gap: 8px; }
.rule-toolbar h3 { font-size: 14px; }
.rule-actions { display: flex; flex-shrink: 0; }
.automatic-rule { border-top: 1px solid rgb(var(--v-theme-on-surface), .12); padding-block: 12px; min-width: 0; }
.rule-fields { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 12px; margin-top: 12px; }
.rules-empty { font-size: 13px; opacity: .7; margin-block: 8px; }
.auto-speed-editor :deep(.v-field__input) { min-width: 0; }
@media (max-width: 600px) { .rule-fields { grid-template-columns: minmax(0, 1fr); } }
</style>

// frontend/src/react/components/AutoSpeedRuleEditor.tsx
import { useEffect } from "react";
import { Alert, Button, Card, Col, Empty, Flex, Form, Radio, Row, Typography } from "antd";
import { ArrowDownOutlined, ArrowUpOutlined, DeleteOutlined, PlusOutlined } from "@ant-design/icons";
import { newAutoSpeedRule, validAutoSpeedRule, type AutoSpeedRule } from "../../domain/auto-speed";
import StrictInputNumber from "./StrictInputNumber";

export interface AutoSpeedRuleEditorProps {
  value: AutoSpeedRule[];
  onChange: (value: AutoSpeedRule[]) => void;
  onValid?: (valid: boolean) => void;
  disabled?: boolean;
}

export default function AutoSpeedRuleEditor({ value, onChange, onValid, disabled = false }: AutoSpeedRuleEditorProps) {
  const valid = value.length <= 100 && value.every(validAutoSpeedRule);
  useEffect(() => { onValid?.(valid); }, [valid, onValid]);
  function update(index: number, change: Partial<AutoSpeedRule>) {
    if (!disabled) onChange(value.map((rule, i) => i === index ? { ...rule, ...change } : rule));
  }
  function move(index: number, direction: number) {
    const next = index + direction;
    if (disabled || next < 0 || next >= value.length) return;
    const rules = [...value];
    [rules[index], rules[next]] = [rules[next], rules[index]];
    onChange(rules);
  }
  const fields: Array<{ field: keyof Omit<AutoSpeedRule, "type">; label: string; min: number; max?: number }> = [
    { field: "threshold_mbps", label: "Trigger Mbps", min: 1 / 125000 },
    { field: "sustained_seconds", label: "Hold seconds", min: 1, max: 86400 },
    { field: "limit_mbps", label: "Cap Mbps", min: 1 / 125000 },
    { field: "limit_duration", label: "Duration seconds", min: 1, max: 86400 },
  ];
  return <section aria-label="Automatic limits">
    <Flex justify="space-between" align="center" wrap>
      <Typography.Title level={5}>Automatic limits</Typography.Title>
      <Button icon={<PlusOutlined />} aria-label="Add automatic rule" disabled={disabled || value.length >= 100}
        onClick={() => onChange([...value, newAutoSpeedRule()])}>Add rule</Button>
    </Flex>
    <Flex vertical gap="middle">
      {!value.length && <Empty description="No automatic rules" image={Empty.PRESENTED_IMAGE_SIMPLE} />}
      {value.map((rule, index) => <Card key={index} size="small" aria-label={`Automatic rule ${index + 1}`}>
        <Flex justify="space-between" align="center" wrap gap="small">
          <Radio.Group aria-label={`Rule ${index + 1} type`} value={rule.type} disabled={disabled}
            optionType="button" options={[{ label: "Sustained", value: "sustained" }, { label: "Burst", value: "burst" }]}
            onChange={event => update(index, { type: event.target.value })} />
          <Flex gap="small">
            <Button icon={<ArrowUpOutlined />} aria-label={`Move rule ${index + 1} up`} disabled={disabled || index === 0} onClick={() => move(index, -1)} />
            <Button icon={<ArrowDownOutlined />} aria-label={`Move rule ${index + 1} down`} disabled={disabled || index === value.length - 1} onClick={() => move(index, 1)} />
            <Button icon={<DeleteOutlined />} danger aria-label={`Remove automatic rule ${index + 1}`} disabled={disabled}
              onClick={() => onChange(value.filter((_, i) => i !== index))} />
          </Flex>
        </Flex>
        <Row gutter={16}>
          {[...fields, ...(rule.type === "burst" ? [
            { field: "window_seconds" as const, label: "Window seconds", min: rule.sustained_seconds, max: 86400 },
            { field: "burst_count" as const, label: "Bursts", min: 1, max: 10000 },
          ] : [])].map(field => <Col xs={24} sm={12} key={field.field}>
            <Form.Item label={field.label} layout="vertical">
              <StrictInputNumber aria-label={field.label} value={rule[field.field]}
                aria-valuemin={field.min} aria-valuemax={field.max} disabled={disabled} style={{ width: "100%" }}
                onChange={number => update(index, { [field.field]: number ?? Number.NaN })} />
            </Form.Item>
          </Col>)}
        </Row>
        {!validAutoSpeedRule(rule) && <Alert type="error" title="Invalid automatic limit rule" showIcon />}
      </Card>)}
    </Flex>
  </section>;
}
