// frontend/src/components/CommandInspector.vue
<script setup lang="ts">
import type { AgentCommand, AgentCommandStreamFrame } from "../domain/inventory";
import { diagnosticPaths } from "../domain/diagnostics";
import DiagnosticResult from "./DiagnosticResult.vue";
import WarpStatus from "./WarpStatus.vue";

defineProps<{
  commands: AgentCommand[];
  streamFramesByCommand: Record<string, AgentCommandStreamFrame[]>;
  emptyText?: string;
}>();

const commandStatusMeta = {
  waiting: { color: "secondary", icon: "mdi-link-variant" },
  pending: { color: "warning", icon: "mdi-clock-outline" },
  leased: { color: "info", icon: "mdi-progress-clock" },
  succeeded: { color: "success", icon: "mdi-check-circle-outline" },
  failed: { color: "error", icon: "mdi-alert-circle-outline" },
  skipped: { color: "grey", icon: "mdi-cancel" },
} as const;

function commandSubtitle(command: AgentCommand, frames: AgentCommandStreamFrame[]) {
  if (command.status === "waiting") return "Waiting for prerequisite";
  if (command.status === "skipped") return "Not executed";
  const status = command.result_status ? `status ${command.result_status}` : "waiting";
  const stream = command.stream ? `, ${frames.length} stream frames` : "";
  return `${command.attempts} attempts, ${status}${stream}`;
}

function commandTarget(command: AgentCommand) {
  return command.query ? `${command.path}?${command.query}` : command.path;
}

function commandTitle(command: AgentCommand) {
  if (command.path.startsWith("/api/child/warp/")) return "WARP " + command.path.split("/").at(-1);
  if (command.path === "/api/child/domains/latency") return "Domain latency";
  if (command.path === "/api/child/network/return-route-test") return "Return route";
  if (command.path === "/api/child/logs") return "Service logs";
  if (command.path === "/api/child/logs/files") return command.method === "DELETE" ? "Clear log files" : "Log files";
  return command.method + " " + commandTarget(command);
}

function hasSummary(command: AgentCommand) {
  return diagnosticPaths.has(command.path) || command.path.startsWith("/api/child/warp/");
}

function formatJson(value: unknown) {
  if (value === undefined || value === null) {
    return "";
  }
  if (typeof value === "string") {
    return value;
  }
  return JSON.stringify(value, null, 2);
}

function framesText(frames: AgentCommandStreamFrame[]) {
  return frames.map((frame) => frame.data.trimEnd()).join("\n");
}
</script>

<template>
  <v-expansion-panels
    v-if="commands.length > 0"
    class="command-inspector"
    density="comfortable"
    variant="accordion"
  >
    <v-expansion-panel v-for="command in commands" :key="command.id" :value="command.id"
      :data-command-id="command.id">
      <v-expansion-panel-title>
        <div class="command-title-row">
          <v-icon
            :color="commandStatusMeta[command.status].color"
            :icon="commandStatusMeta[command.status].icon"
            size="22"
          />
          <div class="command-title-text">
            <div class="command-title">{{ commandTitle(command) }}</div>
            <div class="command-subtitle">
              {{ commandSubtitle(command, streamFramesByCommand[command.id] ?? []) }}
            </div>
          </div>
          <v-chip
            :color="commandStatusMeta[command.status].color"
            density="comfortable"
            size="small"
            variant="tonal"
          >
            {{ command.status }}
          </v-chip>
        </div>
      </v-expansion-panel-title>
      <v-expansion-panel-text>
        <DiagnosticResult
          v-if="diagnosticPaths.has(command.path) && command.result_body != null"
          :path="command.path" :body="command.result_body"
        />
        <WarpStatus v-if="command.path.startsWith('/api/child/warp/') && command.result_body != null"
          :body="command.result_body" />
        <details v-if="hasSummary(command)" class="diagnostic-request">
          <summary>Request details</summary>
          <div class="detail-value">{{ command.method }} {{ commandTarget(command) }}</div>
          <div class="detail-value">{{ command.request_id }}</div>
          <div class="detail-value">{{ command.timeout_ms }} ms | {{ command.created_at }}</div>
          <pre v-if="command.body != null" class="command-json">{{
            command.path === '/api/child/warp/license' ? 'WARP+ credential: [redacted]' : formatJson(command.body)
          }}</pre>
        </details>
        <div v-else class="command-detail-grid">
          <div>
            <div class="detail-label">Request</div>
            <div class="detail-value">{{ command.request_id }}</div>
          </div>
          <div>
            <div class="detail-label">Timeout</div>
            <div class="detail-value">{{ command.timeout_ms }} ms</div>
          </div>
          <div v-if="command.depends_on_command_id">
            <div class="detail-label">Prerequisite</div>
            <div class="detail-value">{{ command.depends_on_command_id }}</div>
          </div>
          <div>
            <div class="detail-label">Created</div>
            <div class="detail-value">{{ command.created_at }}</div>
          </div>
          <div>
            <div class="detail-label">Updated</div>
            <div class="detail-value">{{ command.updated_at }}</div>
          </div>
        </div>

        <pre v-if="!hasSummary(command) && command.body != null" class="command-json">{{
          formatJson(command.body)
        }}</pre>

        <v-alert
          v-if="command.result_error"
          class="command-result-alert"
          density="compact"
          type="error"
          variant="tonal"
        >
          {{ command.result_error }}
        </v-alert>

        <pre
          v-if="!hasSummary(command) && command.result_body != null"
          class="command-json"
        >{{ formatJson(command.result_body) }}</pre>

        <pre
          v-if="(streamFramesByCommand[command.id] ?? []).length > 0"
          class="command-stream-block"
        >{{ framesText(streamFramesByCommand[command.id] ?? []) }}</pre>
      </v-expansion-panel-text>
    </v-expansion-panel>
  </v-expansion-panels>
  <div v-else class="empty-command">{{ emptyText ?? "No commands queued." }}</div>
</template>

<style scoped>
.diagnostic-request { margin-top: 16px; font-size: 12px; }
.diagnostic-request summary { cursor: pointer; margin-bottom: 8px; }
.command-title-row { grid-template-columns: 22px minmax(0, 1fr); align-items: start; }
.command-title-row :deep(.v-chip) { grid-column: 2; justify-self: start; }
.command-title { white-space: normal; overflow-wrap: anywhere; }
.command-subtitle { overflow-wrap: anywhere; line-height: 1.35; }
</style>

// frontend/src/react/components/CommandInspector.tsx
import { Alert, Collapse, Descriptions, Empty, Flex, Space, Tag, Typography } from "antd";
import type { AgentCommand, AgentCommandStreamFrame } from "../../domain/inventory";
import { diagnosticPaths } from "../../domain/diagnostics";
import DiagnosticResult from "./DiagnosticResult";
import WarpStatus from "./WarpStatus";

export interface CommandInspectorProps {
  commands: AgentCommand[];
  streamFramesByCommand: Record<string, AgentCommandStreamFrame[]>;
  emptyText?: string;
}
const colors = { waiting: "default", pending: "warning", leased: "processing", succeeded: "success", failed: "error", skipped: "default" };
const target = (command: AgentCommand) => command.query ? `${command.path}?${command.query}` : command.path;
const json = (value: unknown) => value == null ? "" : typeof value === "string" ? value : JSON.stringify(value, null, 2);
function title(command: AgentCommand) {
  if (command.path.startsWith("/api/child/warp/")) return `WARP ${command.path.split("/").at(-1)}`;
  if (command.path === "/api/child/domains/latency") return "Domain latency";
  if (command.path === "/api/child/network/return-route-test") return "Return route";
  if (command.path === "/api/child/logs") return "Service logs";
  if (command.path === "/api/child/logs/files") return command.method === "DELETE" ? "Clear log files" : "Log files";
  return `${command.method} ${target(command)}`;
}
function subtitle(command: AgentCommand, frames: AgentCommandStreamFrame[]) {
  if (command.status === "waiting") return "Waiting for prerequisite";
  if (command.status === "skipped") return "Not executed";
  return `${command.attempts} attempts, ${command.result_status ? `status ${command.result_status}` : "waiting"}${command.stream ? `, ${frames.length} stream frames` : ""}`;
}

export default function CommandInspector({ commands, streamFramesByCommand, emptyText }: CommandInspectorProps) {
  if (!commands.length) return <Empty description={emptyText ?? "No commands queued."} image={Empty.PRESENTED_IMAGE_SIMPLE} />;
  return <Collapse className="command-inspector" accordion items={commands.map(command => {
    const frames = streamFramesByCommand[command.id] ?? [];
    const summary = diagnosticPaths.has(command.path) || command.path.startsWith("/api/child/warp/");
    const requestItems = [
      { key: "request", label: "Request", children: command.request_id },
      { key: "timeout", label: "Timeout", children: `${command.timeout_ms} ms` },
      ...(command.depends_on_command_id ? [{ key: "prerequisite", label: "Prerequisite", children: command.depends_on_command_id }] : []),
      { key: "created", label: "Created", children: command.created_at },
      { key: "updated", label: "Updated", children: command.updated_at },
    ];
    return {
      key: command.id,
      label: <Flex gap="small" align="start" wrap data-command-id={command.id}>
        <div className="min-width-zero"><Typography.Text strong>{title(command)}</Typography.Text><div><Typography.Text type="secondary">{subtitle(command, frames)}</Typography.Text></div></div>
        <Tag color={colors[command.status]}>{command.status}</Tag>
      </Flex>,
      children: <Space orientation="vertical" style={{ width: "100%" }}>
        {diagnosticPaths.has(command.path) && command.result_body != null && <DiagnosticResult path={command.path} body={command.result_body} />}
        {command.path.startsWith("/api/child/warp/") && command.result_body != null && <WarpStatus body={command.result_body} />}
        {summary ? <Collapse size="small" items={[{ key: "request", label: "Request details", children: <>
          <Typography.Paragraph>{command.method} {target(command)}</Typography.Paragraph>
          <Descriptions size="small" column={{ xs: 1, sm: 2 }} items={requestItems} />
          {command.body != null && <pre className="code-block">{command.path === "/api/child/warp/license" ? "WARP+ credential: [redacted]" : json(command.body)}</pre>}
        </> }]} /> : <>
          <Descriptions size="small" column={{ xs: 1, sm: 2 }} items={requestItems} />
          {command.body != null && <pre className="code-block">{json(command.body)}</pre>}
        </>}
        {command.result_error && <Alert type="error" showIcon title={command.result_error} />}
        {!summary && command.result_body != null && <pre className="code-block">{json(command.result_body)}</pre>}
        {frames.length > 0 && <pre className="code-block" aria-label="Command stream">{frames.map(frame => frame.data.trimEnd()).join("\n")}</pre>}
      </Space>,
    };
  })} />;
}
