// frontend/src/components/PrivateRoutedPolicyDialog.vue
<script setup lang="ts">
import { reactive, ref, watch } from "vue";
import type { PrivateRoutedPolicy } from "../domain/private-routed-nodes";
import { updatePrivateRoutePolicy } from "../services/private-routed-nodes";

const props = defineProps<{ open: boolean; policy: PrivateRoutedPolicy | null }>();
const emit = defineEmits<{
  "update:open": [value: boolean];
  saved: [value: PrivateRoutedPolicy];
}>();
const form = reactive({ enabled: false, max_nodes: 2, daily_limit: 5 });
const busy = ref(false);
const error = ref("");

watch(() => props.open, (open) => {
  if (!open) return;
  Object.assign(form, props.policy ?? { enabled: false, max_nodes: 2, daily_limit: 5 });
  error.value = "";
});

async function save() {
  busy.value = true;
  error.value = "";
  try {
    const value = await updatePrivateRoutePolicy({
      enabled: form.enabled,
      max_nodes: Number(form.max_nodes),
      daily_limit: Number(form.daily_limit),
    });
    emit("saved", value);
    emit("update:open", false);
  } catch (failure) {
    error.value = failure instanceof Error ? failure.message : "Policy update failed";
  } finally {
    busy.value = false;
  }
}
</script>

<template>
  <v-dialog :model-value="open" :persistent="busy" max-width="560" @update:model-value="emit('update:open', $event)">
    <v-card class="policy-dialog">
      <v-card-title>Private route policy</v-card-title>
      <v-card-text class="policy-form">
        <v-alert v-if="error" type="error" variant="tonal" density="compact">{{ error }}</v-alert>
        <v-switch v-model="form.enabled" label="Allow subscriber private routes" color="primary" hide-details />
        <div class="policy-row">
          <v-text-field v-model.number="form.max_nodes" label="Routes per subscriber" type="number" min="1" max="20" variant="outlined" density="compact" />
          <v-text-field v-model.number="form.daily_limit" label="Daily actions" type="number" min="1" max="100" variant="outlined" density="compact" />
        </div>
      </v-card-text>
      <v-card-actions>
        <v-btn :disabled="busy" @click="emit('update:open', false)">Cancel</v-btn>
        <v-spacer />
        <v-btn color="primary" prepend-icon="mdi-content-save" :loading="busy" :disabled="form.max_nodes < 1 || form.daily_limit < 1" @click="save">Save</v-btn>
      </v-card-actions>
    </v-card>
  </v-dialog>
</template>

<style scoped>
.policy-dialog, .policy-dialog :deep(*) { letter-spacing: 0; }
.policy-form { display: grid; gap: 12px; }
.policy-row { display: grid; grid-template-columns: minmax(0, 1fr) minmax(0, 1fr); gap: 12px; }
.policy-dialog :deep(.v-card-title), .policy-dialog :deep(.v-alert__content) { white-space: normal; overflow-wrap: anywhere; }
@media (max-width: 480px) { .policy-row { grid-template-columns: minmax(0, 1fr); } }
</style>

// frontend/src/react/components/PrivateRoutedPolicyDialog.tsx
import { useEffect, useRef, useState } from "react";
import { Alert, Form, Modal, Switch } from "antd";
import type { PrivateRoutedPolicy } from "../../domain/private-routed-nodes";
import { updatePrivateRoutePolicy } from "../../services/private-routed-nodes";
import StrictInputNumber from "./StrictInputNumber";

export interface PrivateRoutedPolicyDialogProps {
  open: boolean; onOpenChange: (open: boolean) => void; policy: PrivateRoutedPolicy | null;
  onSaved?: (value: PrivateRoutedPolicy) => void;
}
export default function PrivateRoutedPolicyDialog(props: PrivateRoutedPolicyDialogProps) {
  return props.open ? <PolicyContent {...props} /> : null;
}
function PolicyContent({ policy, onOpenChange, onSaved }: PrivateRoutedPolicyDialogProps) {
  const [form, setForm] = useState(() => ({ enabled: policy?.enabled ?? false, max_nodes: policy?.max_nodes ?? 2, daily_limit: policy?.daily_limit ?? 5 }));
  const [busy, setBusy] = useState(false), [error, setError] = useState("");
  const version = useRef(0);
  useEffect(() => () => { ++version.current; }, []);
  const valid = Number.isInteger(form.max_nodes) && form.max_nodes >= 1 && form.max_nodes <= 20
    && Number.isInteger(form.daily_limit) && form.daily_limit >= 1 && form.daily_limit <= 100;
  async function save() {
    if (busy || !valid) return;
    const run = ++version.current; setBusy(true); setError("");
    try { const value = await updatePrivateRoutePolicy(form); if (run === version.current) { onSaved?.(value); onOpenChange(false); } }
    catch (failure) { if (run === version.current) setError(failure instanceof Error ? failure.message : "Policy update failed"); }
    finally { if (run === version.current) setBusy(false); }
  }
  return <Modal open title="Private route policy" width={560} destroyOnHidden mask={{ closable: !busy }} keyboard={!busy} closable={!busy}
    onCancel={() => !busy && onOpenChange(false)} onOk={() => void save()} okText="Save" confirmLoading={busy}
    okButtonProps={{ "aria-label": "Save", "aria-busy": busy, disabled: !valid }} cancelButtonProps={{ disabled: busy }}>
    {error && <Alert type="error" title={error} showIcon />}
    <Form layout="vertical" preserve={false} onFinish={() => void save()} disabled={busy}>
      <Form.Item label="Allow subscriber private routes"><Switch aria-label="Allow subscriber private routes" checked={form.enabled} onChange={enabled => setForm({ ...form, enabled })} /></Form.Item>
      <Form.Item label="Routes per subscriber"><StrictInputNumber aria-label="Routes per subscriber" value={form.max_nodes} aria-valuemin={1} aria-valuemax={20} onChange={number => setForm({ ...form, max_nodes: number ?? Number.NaN })} /></Form.Item>
      <Form.Item label="Daily actions"><StrictInputNumber aria-label="Daily actions" value={form.daily_limit} aria-valuemin={1} aria-valuemax={100} onChange={number => setForm({ ...form, daily_limit: number ?? Number.NaN })} /></Form.Item>
    </Form>
  </Modal>;
}
