// frontend/src/components/PrivateRoutedNodesPanel.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, reactive, ref } from "vue";
import type {
  PrivateRoutedNode,
  PrivateRoutedNodesResponse,
  PrivateRoutedNodeStatus,
} from "../domain/private-routed-nodes";
import {
  createSubscriberPrivateRoute,
  deleteSubscriberPrivateRoute,
  listSubscriberPrivateRoutes,
} from "../services/private-routed-nodes";

const state = ref<PrivateRoutedNodesResponse | null>(null);
const loading = ref(false);
const busy = ref("");
const confirming = ref("");
const error = ref("");
const form = reactive({ label: "", parent_id: "", target_node_id: "" });
let timer: ReturnType<typeof setTimeout> | null = null;
let disposed = false;

const parentOptions = computed(() => (state.value?.candidates ?? [])
  .filter(item => item.can_parent)
  .map(item => ({ title: item.name, value: item.id })));
const targetOptions = computed(() => (state.value?.candidates ?? [])
  .filter(item => item.can_target && item.id !== form.parent_id)
  .map(item => ({ title: item.name, value: item.id })));
const canCreate = computed(() => Boolean(
  state.value?.policy.enabled
  && state.value.used_nodes < state.value.policy.max_nodes
  && state.value.actions_today < state.value.policy.daily_limit
  && /^[A-Za-z0-9-]{2,32}$/.test(form.label.trim())
  && form.parent_id
  && form.target_node_id
  && form.parent_id !== form.target_node_id
  && !busy.value,
));

function statusColor(status: PrivateRoutedNodeStatus) {
  if (status === "active") return "success";
  if (status === "failed") return "error";
  return "warning";
}

function schedule() {
  if (timer) clearTimeout(timer);
  timer = null;
  if (!disposed && state.value?.nodes.some(item => ["provisioning", "removing"].includes(item.status))) {
    timer = setTimeout(() => void load(true), 2000);
  }
}

async function load(silent = false) {
  if (!silent) loading.value = true;
  try {
    state.value = await listSubscriberPrivateRoutes();
    if (form.parent_id && !parentOptions.value.some(item => item.value === form.parent_id)) {
      form.parent_id = "";
    }
    if (form.target_node_id && !targetOptions.value.some(item => item.value === form.target_node_id)) {
      form.target_node_id = "";
    }
    if (silent) error.value = "";
  } catch (failure) {
    error.value = failure instanceof Error ? failure.message : "Private routes unavailable";
  } finally {
    loading.value = false;
    schedule();
  }
}

async function create() {
  if (!canCreate.value) return;
  busy.value = "create";
  error.value = "";
  try {
    await createSubscriberPrivateRoute({
      label: form.label.trim(),
      parent_id: form.parent_id,
      target_node_id: form.target_node_id,
    });
    Object.assign(form, { label: "", parent_id: "", target_node_id: "" });
    await load(true);
  } catch (failure) {
    error.value = failure instanceof Error ? failure.message : "Private route creation failed";
  } finally {
    busy.value = "";
  }
}

async function remove(node: PrivateRoutedNode) {
  if (confirming.value !== node.id) {
    confirming.value = node.id;
    return;
  }
  busy.value = node.id;
  error.value = "";
  try {
    await deleteSubscriberPrivateRoute(node.id);
    confirming.value = "";
    await load(true);
  } catch (failure) {
    error.value = failure instanceof Error ? failure.message : "Private route deletion failed";
  } finally {
    busy.value = "";
  }
}

onMounted(() => void load());
onBeforeUnmount(() => {
  disposed = true;
  if (timer) clearTimeout(timer);
});
</script>

<template>
  <section class="private-routes" aria-label="Private routes">
    <div class="route-heading">
      <div><p class="route-label">Private routes</p><h3>Routed exits</h3></div>
      <div v-if="state" class="route-counters">
        <v-chip size="small" variant="tonal">{{ state.used_nodes }}/{{ state.policy.max_nodes }}</v-chip>
        <v-chip size="small" variant="tonal">{{ state.actions_today }}/{{ state.policy.daily_limit }} today</v-chip>
      </div>
    </div>
    <v-progress-linear v-if="loading" indeterminate color="primary" />
    <v-alert v-if="error" type="error" variant="tonal" density="compact">{{ error }}</v-alert>
    <v-alert v-if="state && !state.policy.enabled" type="info" variant="tonal" density="compact">Private routes are disabled.</v-alert>

    <form v-if="state?.policy.enabled" class="route-form" @submit.prevent="create">
      <v-text-field v-model="form.label" label="Label" maxlength="32" variant="outlined" density="compact" hide-details />
      <v-select v-model="form.parent_id" :items="parentOptions" label="Entry node" variant="outlined" density="compact" hide-details />
      <v-select v-model="form.target_node_id" :items="targetOptions" label="Exit node" variant="outlined" density="compact" hide-details />
      <v-btn type="submit" color="primary" prepend-icon="mdi-routes" :loading="busy === 'create'" :disabled="!canCreate">Create</v-btn>
    </form>

    <div v-if="state && !state.nodes.length" class="route-empty">No private routes.</div>
    <div v-for="node in state?.nodes" :key="node.id" class="route-row">
      <div class="route-main">
        <strong>{{ node.name }}</strong>
        <span>{{ node.parent_name }} <v-icon icon="mdi-arrow-right" size="14" /> {{ node.target_name }}</span>
        <span v-if="node.last_error" class="route-error">{{ node.last_error }}</span>
      </div>
      <div class="route-actions">
        <v-chip :color="statusColor(node.status)" size="small" variant="tonal">{{ node.status }}</v-chip>
        <template v-if="!['provisioning', 'removing'].includes(node.status)">
          <v-btn v-if="confirming === node.id" size="small" color="error" variant="tonal" :loading="busy === node.id" @click="remove(node)">Confirm</v-btn>
          <v-tooltip v-else text="Delete private route"><template #activator="{ props: tip }"><v-btn v-bind="tip" icon="mdi-delete-outline" :aria-label="`Delete private route ${node.name}`" variant="text" :disabled="Boolean(busy)" @click="remove(node)" /></template></v-tooltip>
          <v-btn v-if="confirming === node.id" icon="mdi-close" aria-label="Cancel private route deletion" variant="text" :disabled="busy === node.id" @click="confirming = ''" />
        </template>
      </div>
    </div>
  </section>
</template>

<style scoped>
.private-routes, .private-routes :deep(*) { letter-spacing: 0; }
.private-routes { padding-top: 28px; display: grid; gap: 18px; min-width: 0; }
.route-heading, .route-counters, .route-actions { display: flex; align-items: center; gap: 8px; }
.route-heading { justify-content: space-between; gap: 16px; }
.route-label { color: #66736f; font-size: 12px; }
.route-heading h3 { margin-top: 5px; font-size: 20px; }
.route-counters { flex-wrap: wrap; justify-content: flex-end; }
.route-form { display: grid; grid-template-columns: minmax(120px, .7fr) minmax(160px, 1fr) minmax(160px, 1fr) auto; gap: 12px; align-items: center; }
.route-row { display: grid; grid-template-columns: minmax(0, 1fr) auto; gap: 16px; align-items: center; border-bottom: 1px solid #e5ece8; padding: 14px 0; }
.route-main { min-width: 0; display: grid; gap: 5px; }
.route-main span { color: #66736f; font-size: 13px; overflow-wrap: anywhere; }
.route-main .route-error { color: #b42318; }
.route-actions { justify-content: flex-end; }
.route-empty { color: #66736f; font-size: 14px; padding: 18px 0; }
@media (max-width: 760px) {
  .route-form { grid-template-columns: minmax(0, 1fr) minmax(0, 1fr); }
  .route-form :deep(.v-btn) { min-height: 40px; }
}
@media (max-width: 480px) {
  .route-heading, .route-row { align-items: flex-start; }
  .route-heading { flex-direction: column; }
  .route-counters { justify-content: flex-start; }
  .route-form, .route-row { grid-template-columns: minmax(0, 1fr); }
  .route-actions { justify-content: flex-start; flex-wrap: wrap; }
}
</style>

// frontend/src/react/components/PrivateRoutedNodesPanel.tsx
import { ArrowRightOutlined, DeleteOutlined, ReloadOutlined } from "@ant-design/icons";
import { Alert, Button, Card, Flex, Form, Input, Select, Space, Table, Tag, Typography } from "antd";
import { useCallback, useEffect, useRef, useState } from "react";
import type { PrivateRoutedNode, PrivateRoutedNodesResponse } from "../../domain/private-routed-nodes";
import { createSubscriberPrivateRoute, deleteSubscriberPrivateRoute, listSubscriberPrivateRoutes } from "../../services/private-routed-nodes";
import { useAsyncScope } from "../hooks/useAsyncScope";

export default function PrivateRoutedNodesPanel() {
  const readScope = useAsyncScope();
  const operationScope = useAsyncScope();
  const busyRef = useRef(false);
  const [state, setState] = useState<PrivateRoutedNodesResponse | null>(null);
  const [loading, setLoading] = useState(false);
  const [busy, setBusy] = useState("");
  const [confirming, setConfirming] = useState("");
  const [error, setError] = useState("");
  const [form, setForm] = useState({ label: "", parent_id: "", target_node_id: "" });
  const parentOptions = (state?.candidates ?? []).filter(item => item.can_parent).map(item => ({ label: item.name, value: item.id }));
  const targetOptions = (state?.candidates ?? []).filter(item => item.can_target && item.id !== form.parent_id).map(item => ({ label: item.name, value: item.id }));
  const canCreate = Boolean(state?.policy.enabled && state.used_nodes < state.policy.max_nodes && state.actions_today < state.policy.daily_limit && /^[A-Za-z0-9-]{2,32}$/.test(form.label.trim()) && form.parent_id && form.target_node_id && form.parent_id !== form.target_node_id && !busy);
  const hasPending = state?.nodes.some(item => ["provisioning", "removing"].includes(item.status)) ?? false;

  const load = useCallback(async (silent = false) => {
    const current = readScope.begin(); if (!silent) setLoading(true);
    try {
      const result = await listSubscriberPrivateRoutes();
      if (!readScope.isCurrent(current)) return;
      setState(result); setError("");
      setForm(previous => ({ ...previous,
        parent_id: result.candidates.some(item => item.can_parent && item.id === previous.parent_id) ? previous.parent_id : "",
        target_node_id: result.candidates.some(item => item.can_target && item.id === previous.target_node_id && item.id !== previous.parent_id) ? previous.target_node_id : "",
      }));
    } catch (failure) {
      if (readScope.isCurrent(current)) setError(failure instanceof Error ? failure.message : "Private routes unavailable");
    } finally { if (readScope.isCurrent(current)) setLoading(false); }
  }, [readScope]);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => {
    if (!hasPending) return;
    let disposed = false;
    let timer: ReturnType<typeof setTimeout>;
    const poll = async () => {
      await load(true);
      if (!disposed) timer = setTimeout(() => void poll(), 2000);
    };
    timer = setTimeout(() => void poll(), 2000);
    return () => { disposed = true; clearTimeout(timer); };
  }, [hasPending, load]);
  async function create() {
    if (!canCreate || busyRef.current) return;
    const current = operationScope.begin(); busyRef.current = true; setBusy("create"); setError("");
    try {
      await createSubscriberPrivateRoute({ ...form, label: form.label.trim() });
      if (!operationScope.isCurrent(current)) return;
      setForm({ label: "", parent_id: "", target_node_id: "" }); await load(true);
    } catch (failure) {
      if (operationScope.isCurrent(current)) setError(failure instanceof Error ? failure.message : "Private route creation failed");
    } finally { if (operationScope.isCurrent(current)) { setBusy(""); busyRef.current = false; } }
  }
  async function remove(node: PrivateRoutedNode) {
    if (busyRef.current) return;
    if (confirming !== node.id) { setConfirming(node.id); return; }
    const current = operationScope.begin(); busyRef.current = true; setBusy(node.id); setError("");
    try {
      await deleteSubscriberPrivateRoute(node.id);
      if (!operationScope.isCurrent(current)) return;
      setConfirming(""); await load(true);
    } catch (failure) {
      if (operationScope.isCurrent(current)) setError(failure instanceof Error ? failure.message : "Private route deletion failed");
    } finally { if (operationScope.isCurrent(current)) { setBusy(""); busyRef.current = false; } }
  }
  return <section aria-label="Private routes"><Card title="Routed exits" extra={<Flex align="center" gap="small" wrap>
    {state && <><Tag>{state.used_nodes}/{state.policy.max_nodes}</Tag><Tag>{state.actions_today}/{state.policy.daily_limit} today</Tag></>}
    <Button aria-label="Refresh private routes" icon={<ReloadOutlined aria-hidden />} loading={loading} onClick={() => void load()} />
  </Flex>}><Space orientation="vertical" size="middle" style={{ width: "100%" }}>
    {error && <Alert type="error" showIcon title={error} />}
    {state && !state.policy.enabled && <Alert type="info" showIcon title="Private routes are disabled." />}
    {state?.policy.enabled && <Form layout="vertical" onFinish={() => void create()}>
      <Flex gap="middle" wrap align="end">
        <Form.Item label="Label" htmlFor="private-route-label" help="2–32 letters, digits or hyphens"><Input id="private-route-label" value={form.label} onChange={event => setForm(previous => ({ ...previous, label: event.target.value }))} maxLength={32} disabled={Boolean(busy)} /></Form.Item>
        <Form.Item label="Entry node" htmlFor="private-route-parent" style={{ minWidth: 200, flex: 1 }}><Select id="private-route-parent" value={form.parent_id || undefined} options={parentOptions} disabled={Boolean(busy)} onChange={value => setForm(previous => ({ ...previous, parent_id: value, target_node_id: previous.target_node_id === value ? "" : previous.target_node_id }))} /></Form.Item>
        <Form.Item label="Exit node" htmlFor="private-route-target" style={{ minWidth: 200, flex: 1 }}><Select id="private-route-target" value={form.target_node_id || undefined} options={targetOptions} disabled={Boolean(busy)} onChange={value => setForm(previous => ({ ...previous, target_node_id: value }))} /></Form.Item>
        <Form.Item><Button type="primary" htmlType="submit" aria-label="Create" disabled={!canCreate} loading={busy === "create"}>Create</Button></Form.Item>
      </Flex>
    </Form>}
    <Table rowKey="id" loading={loading} dataSource={state?.nodes ?? []} pagination={false} scroll={{ x: 560 }} locale={{ emptyText: "No private routes." }} columns={[
      { title: "Route", render: (_, node) => <><Typography.Text strong>{node.name}</Typography.Text><div><Space wrap>{node.parent_name}<ArrowRightOutlined aria-hidden />{node.target_name}</Space></div>{node.last_error && <Typography.Text type="danger">{node.last_error}</Typography.Text>}</> },
      { title: "Status", dataIndex: "status", width: 120, render: status => <Tag color={status === "active" ? "success" : status === "failed" ? "error" : "warning"}>{status}</Tag> },
      { title: "Action", width: 190, render: (_, node) => !["provisioning", "removing"].includes(node.status) && <Space wrap>
        {confirming === node.id ? <><Button danger aria-label="Confirm" loading={busy === node.id} disabled={Boolean(busy) && busy !== node.id} onClick={() => void remove(node)}>Confirm</Button><Button aria-label="Cancel private route deletion" disabled={Boolean(busy)} onClick={() => setConfirming("")}>Cancel</Button></> : <Button danger icon={<DeleteOutlined aria-hidden />} aria-label={`Delete private route ${node.name}`} disabled={Boolean(busy)} onClick={() => void remove(node)} />}
      </Space> },
    ]} />
  </Space></Card></section>;
}
