// frontend/src/components/SubscriptionProfileDialog.vue
<script setup lang="ts">
import { computed, reactive, ref, watch } from "vue";
import type { ManagedNode, ProductUser } from "../domain/subscriptions";
import type { SubscriptionProfile } from "../domain/subscription-profiles";
import type { SubscriptionTemplate } from "../domain/subscription-templates";
import { updateSubscriptionProfile } from "../services/subscription-profiles";

const props = defineProps<{
  open: boolean;
  profile: SubscriptionProfile | null;
  nodes: ManagedNode[];
  users: ProductUser[];
  templates: SubscriptionTemplate[];
}>();
const emit = defineEmits<{ "update:open": [value: boolean]; saved: [value: SubscriptionProfile] }>();
const form = reactive({
  name: "", description: "", node_ids: [] as string[], assigned_usernames: [] as string[],
  clash_template_id: null as string | null, surge_template_id: null as string | null, enabled: false,
});
const busy = ref(false);
const error = ref("");
const nodeOptions = computed(() => props.nodes.filter(item => !item.removal_id).map(item => ({ title: item.name, value: item.id })));
const userOptions = computed(() => props.users.filter(item => !item.removal_id).map(item => ({ title: item.display_name || item.username, value: item.username })));
const clashTemplates = computed(() => props.templates.filter(item => item.format === "clash"));
const surgeTemplates = computed(() => props.templates.filter(item => item.format === "surge"));

watch(() => [props.open, props.profile] as const, ([open, profile]) => {
  error.value = "";
  if (!open || !profile) return;
  Object.assign(form, {
    name: profile.name,
    description: profile.description,
    node_ids: [...profile.node_ids],
    assigned_usernames: [...profile.assigned_usernames],
    clash_template_id: profile.clash_template_id,
    surge_template_id: profile.surge_template_id,
    enabled: profile.enabled,
  });
}, { immediate: true });

async function save() {
  if (!props.profile || busy.value) return;
  busy.value = true;
  error.value = "";
  try {
    const value = await updateSubscriptionProfile(props.profile.id, {
      ...form,
      expected_revision: props.profile.revision,
    });
    emit("saved", value);
    emit("update:open", false);
  } catch (failure) {
    error.value = failure instanceof Error ? failure.message : "Subscription profile update failed";
  } finally {
    busy.value = false;
  }
}
</script>

<template>
  <v-dialog :model-value="open" :persistent="busy" max-width="720" scrollable @update:model-value="emit('update:open', $event)">
    <v-card class="profile-dialog">
      <v-card-title>Edit subscription profile</v-card-title>
      <v-card-text class="profile-form">
        <v-alert v-if="error" type="error" variant="tonal">{{ error }}</v-alert>
        <v-alert v-if="profile?.migration_warnings.length" type="warning" variant="tonal">{{ profile.migration_warnings.join("; ") }}</v-alert>
        <div class="field-row">
          <v-text-field v-model="form.name" label="Name" variant="outlined" density="compact" />
          <v-switch v-model="form.enabled" label="Enabled" color="primary" hide-details />
        </div>
        <v-textarea v-model="form.description" label="Description" variant="outlined" rows="2" auto-grow />
        <v-autocomplete v-model="form.assigned_usernames" :items="userOptions" label="Assigned subscribers" multiple chips closable-chips variant="outlined" />
        <v-autocomplete v-model="form.node_ids" :items="nodeOptions" label="Node subset" hint="Empty uses every node in each subscriber's plan" persistent-hint multiple chips closable-chips variant="outlined" />
        <div class="field-row">
          <v-select v-model="form.clash_template_id" :items="clashTemplates" item-title="name" item-value="id" label="Clash template" clearable variant="outlined" />
          <v-select v-model="form.surge_template_id" :items="surgeTemplates" item-title="name" item-value="id" label="Surge template" clearable variant="outlined" />
        </div>
      </v-card-text>
      <v-card-actions>
        <v-btn :disabled="busy" @click="emit('update:open', false)">Cancel</v-btn>
        <v-spacer />
        <v-btn color="primary" prepend-icon="mdi-content-save" :loading="busy" :disabled="!form.name.trim()" @click="save">Save</v-btn>
      </v-card-actions>
    </v-card>
  </v-dialog>
</template>

<style scoped>
.profile-dialog, .profile-dialog :deep(*) { letter-spacing: 0; }
.profile-form { display: grid; gap: 14px; min-width: 0; }
.field-row { display: grid; grid-template-columns: minmax(0, 1fr) minmax(0, 1fr); gap: 12px; align-items: center; }
.profile-dialog :deep(.v-card-title), .profile-dialog :deep(.v-alert__content) { white-space: normal; overflow-wrap: anywhere; }
@media (max-width: 560px) { .field-row { grid-template-columns: minmax(0, 1fr); } }
</style>

// frontend/src/react/components/SubscriptionProfileDialog.tsx
import { useEffect, useRef, useState } from "react";
import { Alert, Flex, Form, Input, Modal, Select, Switch } from "antd";
import type { ManagedNode, ProductUser } from "../../domain/subscriptions";
import type { SubscriptionProfile } from "../../domain/subscription-profiles";
import type { SubscriptionTemplate } from "../../domain/subscription-templates";
import { updateSubscriptionProfile } from "../../services/subscription-profiles";

export interface SubscriptionProfileDialogProps { open: boolean; profile: SubscriptionProfile | null; nodes: ManagedNode[]; users: ProductUser[]; templates: SubscriptionTemplate[]; onOpenChange: (open: boolean) => void; onSaved?: (profile: SubscriptionProfile) => void }
export default function SubscriptionProfileDialog(props: SubscriptionProfileDialogProps) { return props.open && props.profile ? <ProfileContent key={`${props.profile.id}:${props.profile.revision}`} {...props} profile={props.profile} /> : null; }
function ProfileContent({ profile, nodes, users, templates, onOpenChange, onSaved }: SubscriptionProfileDialogProps & { profile: SubscriptionProfile }) {
  const [form, setForm] = useState(() => ({ name: profile.name, description: profile.description, node_ids: [...profile.node_ids], assigned_usernames: [...profile.assigned_usernames], clash_template_id: profile.clash_template_id, surge_template_id: profile.surge_template_id, enabled: profile.enabled }));
  const [busy, setBusy] = useState(false), [error, setError] = useState("");
  const version = useRef(0); useEffect(() => () => { ++version.current; }, []);
  function patch(change: Partial<typeof form>) { setForm(previous => ({ ...previous, ...change })); }
  async function save() {
    if (busy || !form.name.trim()) return;
    const run = ++version.current; setBusy(true); setError("");
    try {
      const value = await updateSubscriptionProfile(profile.id, { ...form, expected_revision: profile.revision });
      if (run !== version.current) return; onSaved?.(value); onOpenChange(false);
    } catch (failure) { if (run === version.current) setError(failure instanceof Error ? failure.message : "Subscription profile update failed"); }
    finally { if (run === version.current) setBusy(false); }
  }
  return <Modal open title="Edit subscription profile" width={720} destroyOnHidden mask={{ closable: !busy }} keyboard={!busy} closable={!busy} onCancel={() => !busy && onOpenChange(false)} okText="Save" confirmLoading={busy} okButtonProps={{ "aria-label": "Save", "aria-busy": busy, disabled: !form.name.trim() }} cancelButtonProps={{ disabled: busy }} onOk={() => void save()}>
    <Flex vertical gap="middle">{error && <Alert type="error" title={error} showIcon />}{!!profile.migration_warnings.length && <Alert type="warning" title={profile.migration_warnings.join("; ")} showIcon />}
      <Form layout="vertical" preserve={false} disabled={busy}>
        <Form.Item label="Name"><Input aria-label="Name" value={form.name} onChange={event => patch({ name: event.target.value })} /></Form.Item>
        <Form.Item label="Enabled"><Switch aria-label="Enabled" checked={form.enabled} onChange={enabled => patch({ enabled })} /></Form.Item>
        <Form.Item label="Description"><Input.TextArea aria-label="Description" rows={2} value={form.description} onChange={event => patch({ description: event.target.value })} /></Form.Item>
        <Form.Item label="Assigned subscribers"><Select aria-label="Assigned subscribers" mode="multiple" value={form.assigned_usernames} onChange={assigned_usernames => patch({ assigned_usernames })} options={users.filter(user => !user.removal_id).map(user => ({ label: user.display_name || user.username, value: user.username }))} /></Form.Item>
        <Form.Item label="Node subset" extra="Empty uses every node in each subscriber's plan"><Select aria-label="Node subset" mode="multiple" value={form.node_ids} onChange={node_ids => patch({ node_ids })} options={nodes.filter(node => !node.removal_id).map(node => ({ label: node.name, value: node.id }))} /></Form.Item>
        {(["clash", "surge"] as const).map(format => <Form.Item key={format} label={`${format === "clash" ? "Clash" : "Surge"} template`}><Select aria-label={`${format === "clash" ? "Clash" : "Surge"} template`} allowClear value={form[`${format}_template_id`] ?? undefined} onChange={value => patch({ [`${format}_template_id`]: value ?? null })} options={templates.filter(template => template.format === format).map(template => ({ label: template.name, value: template.id }))} /></Form.Item>)}
      </Form>
    </Flex>
  </Modal>;
}
