// frontend/src/components/SubscriberSecurityPanel.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref } from "vue";
import QRCode from "qrcode";
import SubscriptionIpPolicyDialog from "./SubscriptionIpPolicyDialog.vue";
import type { SubscriptionIpPolicy } from "../domain/subscriptions";
import {
  beginSubscriberTotp, clearSubscriberSession, confirmSubscriberTotp, revokeSubscriberDevice,
  subscriberChangePassword, subscriberDevices, subscriberIpPolicy, subscriberSecurity, subscriberToken, updateSubscriberTotp,
  type SubscriberDevice, type SubscriberEnrollment, type SubscriberSecurity,
} from "../services/subscriber-auth";

const emit = defineEmits<{ changed: [] }>();
const security = ref<SubscriberSecurity | null>(null);
const devices = ref<SubscriberDevice[]>([]);
const ipPolicy = ref<SubscriptionIpPolicy | null>(null);
const ipDialog = ref(false);
const loading = ref(false);
const error = ref("");
const notice = ref("");
type Mode = "password" | "enroll" | "disable" | "recovery" | "link";
const mode = ref<Mode>("password");
const titles: Record<Mode, string> = { password: "Change password", enroll: "Two-factor authentication", disable: "Disable two-factor authentication", recovery: "New recovery codes", link: "Reset subscription links" };
const dialog = ref(false);
const busy = ref(false);
const dialogError = ref("");
const password = ref("");
const newPassword = ref("");
const confirmation = ref("");
const code = ref("");
const enrollment = ref<SubscriberEnrollment | null>(null);
const qr = ref("");
const recovery = ref<string[]>([]);
const accepted = ref(false);
let version = 0;
let operationVersion = 0;
const needsCode = computed(() => !!enrollment.value || (security.value?.totp_enabled && mode.value !== "enroll"));
const canSubmit = computed(() => !busy.value && !recovery.value.length && (enrollment.value ? !!code.value.trim() : !!password.value)
  && (!needsCode.value || !!code.value.trim()) && (mode.value !== "password" || (newPassword.value.length >= 12 && newPassword.value === confirmation.value)));

async function load() {
  const current = ++version;
  loading.value = true; error.value = "";
  try {
    const [settings, sessions, policy] = await Promise.all([subscriberSecurity(), subscriberDevices(), subscriberIpPolicy()]);
    if (current === version) { security.value = settings; devices.value = sessions; ipPolicy.value = policy; }
  } catch (failure) {
    if (current === version) error.value = failure instanceof Error ? failure.message : "Security settings unavailable";
  } finally { if (current === version) loading.value = false; }
}
function clearSecrets() {
  password.value = ""; newPassword.value = ""; confirmation.value = ""; code.value = "";
  enrollment.value = null; qr.value = ""; recovery.value = []; accepted.value = false;
}
function open(action: Mode) {
  ++operationVersion; clearSecrets(); mode.value = action; dialogError.value = ""; dialog.value = true;
}
function ipPolicyUpdated(value: SubscriptionIpPolicy) { ipPolicy.value = value; }
function close() {
  if (busy.value || (recovery.value.length && !accepted.value)) return;
  ++operationVersion; dialog.value = false; clearSecrets();
}
async function submit() {
  if (!canSubmit.value) return;
  const current = ++operationVersion;
  busy.value = true; dialogError.value = ""; notice.value = "";
  try {
    const proof = { password: password.value, code: code.value };
    if (mode.value === "enroll") {
      if (!enrollment.value) {
        const result = await beginSubscriberTotp(password.value);
        const image = await QRCode.toDataURL(result.provisioning_uri, { width: 240, margin: 2 });
        if (current !== operationVersion) return;
        enrollment.value = result; qr.value = image; password.value = "";
        return;
      }
      const result = await confirmSubscriberTotp(code.value);
      if (current !== operationVersion) return;
      recovery.value = result.recovery_codes; enrollment.value = null; qr.value = "";
    } else if (mode.value === "password") {
      await subscriberChangePassword(proof, newPassword.value);
    } else if (mode.value === "link") {
      await subscriberToken(proof); emit("changed"); notice.value = "Subscription links reset";
    } else {
      const result = await updateSubscriberTotp(proof, mode.value === "disable");
      if (current !== operationVersion) return;
      recovery.value = result?.recovery_codes ?? [];
      notice.value = mode.value === "disable" ? "Two-factor authentication disabled" : "Recovery codes replaced";
    }
    if (current !== operationVersion) return;
    password.value = ""; code.value = ""; newPassword.value = ""; confirmation.value = "";
    if (!recovery.value.length) dialog.value = false;
    if (mode.value !== "password") await load();
  } catch (failure) {
    if (current === operationVersion) dialogError.value = failure instanceof Error ? failure.message : "Security update failed";
  } finally { if (current === operationVersion) busy.value = false; }
}
async function revoke(device?: SubscriberDevice) {
  if (loading.value) return;
  loading.value = true; error.value = "";
  try {
    await revokeSubscriberDevice(device?.id);
    if (device?.current) clearSubscriberSession();
    else await load();
  } catch (failure) { error.value = failure instanceof Error ? failure.message : "Session revocation failed"; }
  finally { loading.value = false; }
}
async function copy(value: string) {
  try { await navigator.clipboard.writeText(value); }
  catch { dialogError.value = "Clipboard unavailable"; }
}
function saveRecovery() {
  const url = URL.createObjectURL(new Blob([recovery.value.join("\n") + "\n"], { type: "text/plain" }));
  const anchor = document.createElement("a"); anchor.href = url; anchor.download = "open-node-recovery-codes.txt"; anchor.click();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
const date = (value: string) => new Date(value).toLocaleString();
onMounted(load);
onBeforeUnmount(() => { ++version; ++operationVersion; clearSecrets(); });
</script>

<template>
  <div class="subscriber-security">
    <v-progress-linear v-if="loading" indeterminate color="primary" />
    <v-alert v-if="error" type="error" variant="tonal">{{ error }}</v-alert>
    <v-alert v-if="notice" type="success" variant="tonal" closable>{{ notice }}</v-alert>
    <div class="security-heading"><h2>Account security</h2><v-tooltip text="Refresh security settings"><template #activator="{ props: tip }"><v-btn v-bind="tip" icon="mdi-refresh" aria-label="Refresh security settings" variant="text" :disabled="loading" @click="load" /></template></v-tooltip></div>
    <template v-if="security">
      <section class="security-setting"><div><h3>Password</h3></div><v-btn variant="text" prepend-icon="mdi-key-outline" @click="open('password')">Change password</v-btn></section>
      <section class="security-setting"><div><h3>Two-factor authentication</h3><p>{{ security.totp_enabled ? 'Enabled' : 'Not enabled' }}</p><p v-if="security.totp_enabled">{{ security.recovery_codes_remaining }} recovery codes remaining</p><p v-else-if="!security.totp_available">Enrollment unavailable</p></div><div class="security-actions"><template v-if="security.totp_enabled"><v-btn variant="text" prepend-icon="mdi-key-change" @click="open('recovery')">New recovery codes</v-btn><v-btn variant="text" color="error" prepend-icon="mdi-shield-off-outline" @click="open('disable')">Disable</v-btn></template><v-btn v-else variant="text" color="primary" prepend-icon="mdi-shield-plus-outline" :disabled="!security.totp_available" @click="open('enroll')">Enable</v-btn></div></section>
      <section class="security-setting"><h3>Subscription links</h3><v-btn variant="text" prepend-icon="mdi-link-variant-remove" @click="open('link')">Reset links</v-btn></section>
      <section class="security-setting"><div><h3>Subscription IP access</h3><p>{{ ipPolicy?.enabled ? `${ipPolicy.networks.length} allowed ${ipPolicy.networks.length === 1 ? 'range' : 'ranges'}` : 'Unrestricted' }}</p></div><v-btn variant="text" prepend-icon="mdi-ip-network-outline" @click="ipDialog = true">Edit access</v-btn></section>
    </template>
    <section class="security-devices" aria-label="Active sessions">
      <div class="security-heading"><h2>Active sessions</h2><v-btn variant="text" prepend-icon="mdi-logout-variant" :disabled="loading || devices.length < 2" @click="revoke()">Revoke others</v-btn></div>
      <div v-for="device in devices" :key="device.id" class="security-device">
        <v-icon icon="mdi-monitor-cellphone" aria-hidden="true" />
        <div class="device-details"><strong>{{ device.peer }}</strong><v-chip v-if="device.current" size="x-small" color="primary" variant="tonal" class="ml-2">Current</v-chip><p>{{ device.user_agent || 'Unknown device' }}</p><dl><dt>Signed in</dt><dd>{{ date(device.created_at) }}</dd><dt>Last active</dt><dd>{{ date(device.last_seen_at) }}</dd></dl></div>
        <v-tooltip :text="device.current ? 'Sign out this device' : 'Revoke session'"><template #activator="{ props: tip }"><v-btn v-bind="tip" icon="mdi-logout" :aria-label="device.current ? 'Sign out this device' : `Revoke session ${device.id}`" variant="text" :disabled="loading" @click="revoke(device)" /></template></v-tooltip>
      </div>
      <p v-if="!loading && !devices.length">No active sessions</p>
    </section>
    <v-dialog :model-value="dialog" :persistent="busy || !!recovery.length" max-width="520" scrollable @update:model-value="close">
      <v-card class="subscriber-security-dialog">
        <v-card-title>{{ recovery.length ? 'Recovery codes' : titles[mode] }}</v-card-title>
        <v-card-text>
          <v-alert v-if="dialogError" type="error" variant="tonal" class="mb-4">{{ dialogError }}</v-alert>
          <template v-if="recovery.length">
            <div class="recovery-actions"><v-tooltip text="Download recovery codes"><template #activator="{ props: tip }"><v-btn v-bind="tip" icon="mdi-download" aria-label="Download recovery codes" variant="text" @click="saveRecovery" /></template></v-tooltip><v-tooltip text="Copy recovery codes"><template #activator="{ props: tip }"><v-btn v-bind="tip" icon="mdi-content-copy" aria-label="Copy recovery codes" variant="text" @click="copy(recovery.join('\n'))" /></template></v-tooltip></div>
            <ul class="recovery-codes"><li v-for="item in recovery" :key="item"><code>{{ item }}</code></li></ul>
            <v-checkbox v-model="accepted" label="I have stored my recovery codes securely" hide-details />
          </template>
          <form v-else id="subscriber-security-form" class="security-form" @submit.prevent="submit">
            <v-alert v-if="mode === 'password'" type="warning" variant="tonal">All sessions will be signed out.</v-alert>
            <v-alert v-if="mode === 'link'" type="warning" variant="tonal">Existing subscription links will stop working.</v-alert>
            <v-alert v-if="mode === 'disable'" type="warning" variant="tonal">Two-factor authentication and recovery codes will be removed. Other sessions will be signed out.</v-alert>
            <v-alert v-if="mode === 'recovery'" type="warning" variant="tonal">Existing recovery codes will stop working. Other sessions will be signed out.</v-alert>
            <template v-if="enrollment">
              <img :src="qr" alt="Authenticator enrollment QR code" width="240" height="240" class="totp-qr" />
              <v-text-field :model-value="enrollment.secret" label="Setup key" readonly hide-details append-inner-icon="mdi-content-copy" @click:append-inner="copy(enrollment.secret)" />
              <p class="enrollment-expiry">Expires {{ date(enrollment.expires_at) }}</p>
            </template>
            <v-text-field v-else v-model="password" label="Current password" type="password" autocomplete="current-password" required maxlength="1024" :disabled="busy" />
            <template v-if="mode === 'password'">
              <v-text-field v-model="newPassword" label="New password" type="password" autocomplete="new-password" required minlength="12" maxlength="1024" :disabled="busy" />
              <v-text-field v-model="confirmation" label="Confirm password" type="password" autocomplete="new-password" required maxlength="1024" :disabled="busy" :error-messages="confirmation && confirmation !== newPassword ? 'Passwords do not match' : ''" />
            </template>
            <v-text-field v-if="needsCode" v-model="code" :label="enrollment ? 'Authenticator code' : 'Authenticator or recovery code'" autocomplete="one-time-code" :inputmode="enrollment ? 'numeric' : 'text'" required maxlength="64" :disabled="busy" />
          </form>
        </v-card-text>
        <v-card-actions><v-btn :disabled="busy || (!!recovery.length && !accepted)" @click="close">{{ recovery.length ? 'Done' : 'Cancel' }}</v-btn><v-spacer /><v-btn v-if="!recovery.length" form="subscriber-security-form" type="submit" color="primary" :prepend-icon="mode === 'enroll' ? 'mdi-shield-check-outline' : 'mdi-check'" :disabled="!canSubmit" :loading="busy">{{ mode === 'enroll' ? (enrollment ? 'Verify and enable' : 'Continue') : 'Confirm' }}</v-btn></v-card-actions>
      </v-card>
    </v-dialog>
    <SubscriptionIpPolicyDialog v-model:open="ipDialog" subscriber @updated="ipPolicyUpdated" />
  </div>
</template>

<style scoped>
.subscriber-security, .subscriber-security-dialog, .subscriber-security-dialog :deep(*), .subscriber-security :deep(*) { letter-spacing: 0; }
.subscriber-security { display: grid; gap: 12px; }
.security-heading, .security-setting, .security-actions { display: flex; align-items: center; justify-content: space-between; gap: 12px; flex-wrap: wrap; }
.security-heading h2 { font-size: 18px; }
.security-setting { border-bottom: 1px solid #dbe5e0; padding: 20px 0; }
.security-setting h3 { font-size: 14px; }
.security-setting p, .security-device p, .enrollment-expiry { color: #66736f; font-size: 13px; margin-top: 6px; overflow-wrap: anywhere; }
.security-devices { padding-top: 24px; }
.security-actions { justify-content: flex-end; }
.security-device { display: grid; grid-template-columns: 24px minmax(0, 1fr) 48px; gap: 14px; align-items: start; border-top: 1px solid #dbe5e0; padding: 20px 0; margin-top: 12px; }
.device-details { min-width: 0; overflow-wrap: anywhere; font-size: 14px; }
.device-details dl { display: grid; grid-template-columns: 76px minmax(0, 1fr); gap: 4px 8px; margin-top: 10px; font-size: 12px; }
.device-details dt { color: #66736f; }
.security-form { display: grid; gap: 12px; }
.totp-qr { justify-self: center; max-width: 100%; height: auto; aspect-ratio: 1; }
.subscriber-security-dialog :deep(.v-card-title) { font-size: 18px; white-space: normal; }
.subscriber-security-dialog :deep(.v-label) { white-space: normal; }
.subscriber-security-dialog :deep(.v-card-actions) { flex-wrap: wrap; }
.subscriber-security-dialog :deep(.v-alert__content) { font-size: 14px; overflow-wrap: anywhere; }
.recovery-actions { display: flex; justify-content: flex-end; }
.recovery-codes { list-style: none; display: grid; gap: 12px; padding: 12px 0; font-size: 14px; overflow-wrap: anywhere; text-align: center; }
@media (max-width: 400px) { .security-device { gap: 8px; } }
</style>

// frontend/src/react/components/SubscriberSecurityPanel.tsx
import { CopyOutlined, DownloadOutlined, LogoutOutlined, ReloadOutlined, SafetyCertificateOutlined } from "@ant-design/icons";
import { Alert, Button, Card, Checkbox, Descriptions, Flex, Form, Input, Modal, Space, Table, Tag, Typography } from "antd";
import QRCode from "qrcode";
import { useEffect, useRef, useState } from "react";
import type { SubscriptionIpPolicy } from "../../domain/subscriptions";
import {
  beginSubscriberTotp, clearSubscriberSession, confirmSubscriberTotp, revokeSubscriberDevice,
  subscriberChangePassword, subscriberDevices, subscriberIpPolicy, subscriberSecurity, subscriberToken, updateSubscriberTotp,
  type SubscriberDevice, type SubscriberEnrollment, type SubscriberSecurity,
} from "../../services/subscriber-auth";
import { useAsyncScope } from "../hooks/useAsyncScope";
import SubscriptionIpPolicyDialog from "./SubscriptionIpPolicyDialog";

export interface SubscriberSecurityPanelProps { onChanged?: () => void }
type Mode = "password" | "enroll" | "disable" | "recovery" | "link";
const titles = { password: "Change password", enroll: "Two-factor authentication", disable: "Disable two-factor authentication", recovery: "New recovery codes", link: "Reset subscription links" };
const date = (value: string) => new Date(value).toLocaleString();

export default function SubscriberSecurityPanel({ onChanged }: SubscriberSecurityPanelProps) {
  const readScope = useAsyncScope();
  const operationScope = useAsyncScope();
  const busyRef = useRef(false);
  const revokeRef = useRef(false);
  const [security, setSecurity] = useState<SubscriberSecurity | null>(null);
  const [devices, setDevices] = useState<SubscriberDevice[]>([]);
  const [ipPolicy, setIpPolicy] = useState<SubscriptionIpPolicy | null>(null);
  const [ipDialog, setIpDialog] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");
  const [mode, setMode] = useState<Mode | null>(null);
  const [busy, setBusy] = useState(false);
  const [dialogError, setDialogError] = useState("");
  const [password, setPassword] = useState("");
  const [newPassword, setNewPassword] = useState("");
  const [confirmation, setConfirmation] = useState("");
  const [code, setCode] = useState("");
  const [enrollment, setEnrollment] = useState<SubscriberEnrollment | null>(null);
  const [qr, setQr] = useState("");
  const [recovery, setRecovery] = useState<string[]>([]);
  const [accepted, setAccepted] = useState(false);
  const needsCode = Boolean(enrollment || (security?.totp_enabled && mode !== "enroll"));
  const canSubmit = !busy && !recovery.length && (enrollment ? Boolean(code.trim()) : Boolean(password)) && (!needsCode || Boolean(code.trim())) && (mode !== "password" || (newPassword.length >= 12 && newPassword === confirmation));

  async function load() {
    const current = readScope.begin(); setLoading(true); setError("");
    try {
      const [settings, sessions, policy] = await Promise.all([subscriberSecurity(), subscriberDevices(), subscriberIpPolicy()]);
      if (readScope.isCurrent(current)) { setSecurity(settings); setDevices(sessions); setIpPolicy(policy); }
    } catch (failure) {
      if (readScope.isCurrent(current)) setError(failure instanceof Error ? failure.message : "Security settings unavailable");
    } finally { if (readScope.isCurrent(current)) setLoading(false); }
  }
  useEffect(() => { void load(); }, []);
  function clearSecrets() {
    setPassword(""); setNewPassword(""); setConfirmation(""); setCode(""); setEnrollment(null); setQr(""); setRecovery([]); setAccepted(false);
  }
  function open(action: Mode) {
    if (busyRef.current) return;
    operationScope.invalidate(); clearSecrets(); setMode(action); setDialogError("");
  }
  function close() {
    if (busyRef.current || (recovery.length > 0 && !accepted)) return;
    operationScope.invalidate(); setMode(null); clearSecrets(); setDialogError("");
  }
  async function submit() {
    if (!mode || !canSubmit || busyRef.current) return;
    const current = operationScope.begin(); busyRef.current = true; setBusy(true); setDialogError(""); setNotice("");
    try {
      const proof = { password, code };
      let codes: string[] = [];
      if (mode === "enroll") {
        if (!enrollment) {
          const result = await beginSubscriberTotp(password);
          if (!operationScope.isCurrent(current)) return;
          setEnrollment(result); setPassword("");
          const image = await QRCode.toDataURL(result.provisioning_uri, { width: 240, margin: 2 });
          if (operationScope.isCurrent(current)) setQr(image);
          return;
        }
        const result = await confirmSubscriberTotp(code);
        codes = result.recovery_codes;
      } else if (mode === "password") await subscriberChangePassword(proof, newPassword);
      else if (mode === "link") {
        await subscriberToken(proof);
        if (operationScope.isCurrent(current)) { onChanged?.(); setNotice("Subscription links reset"); }
      } else {
        const result = await updateSubscriberTotp(proof, mode === "disable");
        codes = result?.recovery_codes ?? [];
        if (operationScope.isCurrent(current)) setNotice(mode === "disable" ? "Two-factor authentication disabled" : "Recovery codes replaced");
      }
      if (!operationScope.isCurrent(current)) return;
      setRecovery(codes); setEnrollment(null); setQr("");
      setPassword(""); setCode(""); setNewPassword(""); setConfirmation("");
      if (!codes.length) setMode(null);
      if (mode !== "password") await load();
    } catch (failure) {
      if (operationScope.isCurrent(current)) setDialogError(failure instanceof Error ? failure.message : "Security update failed");
    } finally {
      if (operationScope.isCurrent(current)) { setBusy(false); busyRef.current = false; setPassword(""); setCode(""); setNewPassword(""); setConfirmation(""); }
    }
  }
  async function revoke(device?: SubscriberDevice) {
    if (loading || revokeRef.current) return;
    const current = readScope.begin(); revokeRef.current = true; setLoading(true); setError("");
    try {
      await revokeSubscriberDevice(device?.id);
      if (!readScope.isCurrent(current)) return;
      if (device?.current) clearSubscriberSession();
      else await load();
    } catch (failure) {
      if (readScope.isCurrent(current)) setError(failure instanceof Error ? failure.message : "Session revocation failed");
    } finally { revokeRef.current = false; if (readScope.isCurrent(current)) setLoading(false); }
  }
  async function copy(value: string) {
    const current = operationScope.capture();
    try { await navigator.clipboard.writeText(value); }
    catch { if (operationScope.isCurrent(current)) setDialogError("Clipboard unavailable"); }
  }
  function saveRecovery() {
    const url = URL.createObjectURL(new Blob([`${recovery.join("\n")}\n`], { type: "text/plain" }));
    const anchor = document.createElement("a"); anchor.href = url; anchor.download = "open-node-recovery-codes.txt"; anchor.click();
    setTimeout(() => URL.revokeObjectURL(url), 1000);
  }
  return <Space orientation="vertical" size="large" style={{ width: "100%" }}>
    {error && <Alert type="error" showIcon title={error} />}
    {notice && <Alert type="success" showIcon title={notice} closable onClose={() => setNotice("")} />}
    <Card title="Account security" extra={<Button icon={<ReloadOutlined aria-hidden />} aria-label="Refresh security settings" loading={loading} onClick={() => void load()} />}>
      {security && <Space orientation="vertical" size="large" style={{ width: "100%" }}>
        <Flex justify="space-between" align="center" wrap gap="small"><Typography.Text strong>Password</Typography.Text><Button onClick={() => open("password")}>Change password</Button></Flex>
        <Flex justify="space-between" align="center" wrap gap="middle">
          <div><Typography.Text strong>Two-factor authentication</Typography.Text><div><Tag color={security.totp_enabled ? "success" : "default"}>{security.totp_enabled ? "Enabled" : "Not enabled"}</Tag></div>
            {security.totp_enabled && <Typography.Text type="secondary">{security.recovery_codes_remaining} recovery codes remaining</Typography.Text>}
            {!security.totp_enabled && !security.totp_available && <Typography.Text type="secondary">Enrollment unavailable</Typography.Text>}
          </div>
          <Space wrap>{security.totp_enabled ? <><Button onClick={() => open("recovery")}>New recovery codes</Button><Button danger onClick={() => open("disable")}>Disable</Button></> : <Button type="primary" icon={<SafetyCertificateOutlined aria-hidden />} disabled={!security.totp_available} onClick={() => open("enroll")}>Enable</Button>}</Space>
        </Flex>
        <Flex justify="space-between" align="center" wrap gap="small"><Typography.Text strong>Subscription links</Typography.Text><Button onClick={() => open("link")}>Reset links</Button></Flex>
        <Flex justify="space-between" align="center" wrap gap="small"><div><Typography.Text strong>Subscription IP access</Typography.Text><div><Typography.Text type="secondary">{ipPolicy?.enabled ? `${ipPolicy.networks.length} allowed ${ipPolicy.networks.length === 1 ? "range" : "ranges"}` : "Unrestricted"}</Typography.Text></div></div><Button onClick={() => setIpDialog(true)}>Edit access</Button></Flex>
      </Space>}
    </Card>
    <section aria-label="Active sessions"><Card title="Active sessions" extra={<Button icon={<LogoutOutlined aria-hidden />} disabled={loading || devices.length < 2} onClick={() => void revoke()}>Revoke others</Button>}>
      <Table rowKey="id" dataSource={devices} loading={loading} pagination={false} scroll={{ x: 540 }} locale={{ emptyText: "No active sessions" }} columns={[
        { title: "Device", render: (_, device) => <><Space wrap><Typography.Text strong>{device.peer}</Typography.Text>{device.current && <Tag color="blue">Current</Tag>}</Space><Typography.Paragraph type="secondary">{device.user_agent || "Unknown device"}</Typography.Paragraph></> },
        { title: "Activity", width: 250, render: (_, device) => <Descriptions column={1} size="small" items={[
          { key: "created", label: "Signed in", children: date(device.created_at) },
          { key: "seen", label: "Last active", children: date(device.last_seen_at) },
        ]} /> },
        { title: "Action", width: 96, render: (_, device) => <Button icon={<LogoutOutlined aria-hidden />} aria-label={device.current ? "Sign out this device" : `Revoke session ${device.id}`} disabled={loading} onClick={() => void revoke(device)} /> },
      ]} />
    </Card></section>
    <Modal open={mode !== null} title={recovery.length ? "Recovery codes" : titles[mode ?? "password"]} width={560} destroyOnHidden mask={{ closable: !busy && !recovery.length }} keyboard={!busy && !recovery.length} closable={!busy && !recovery.length} onCancel={close} footer={<Space wrap>
      <Button disabled={busy || (recovery.length > 0 && !accepted)} onClick={close}>{recovery.length ? "Done" : "Cancel"}</Button>
      {!recovery.length && <Button type="primary" htmlType="submit" form="subscriber-security-form" aria-label={mode === "enroll" ? enrollment ? "Verify and enable" : "Continue" : "Confirm"} disabled={!canSubmit} loading={busy}>{mode === "enroll" ? enrollment ? "Verify and enable" : "Continue" : "Confirm"}</Button>}
    </Space>}>
      {dialogError && <Alert className="form-alert" type="error" showIcon title={dialogError} />}
      {recovery.length ? <Space orientation="vertical" size="middle" style={{ width: "100%" }}>
        <Alert type="warning" showIcon title="Save these one-time codes securely. Existing recovery codes no longer work." />
        <Flex justify="end" gap="small"><Button icon={<DownloadOutlined aria-hidden />} aria-label="Download recovery codes" onClick={saveRecovery} /><Button icon={<CopyOutlined aria-hidden />} aria-label="Copy recovery codes" onClick={() => void copy(recovery.join("\n"))} /></Flex>
        <div className="recovery-grid" aria-label="Recovery codes">{recovery.map(item => <Typography.Text code key={item}>{item}</Typography.Text>)}</div>
        <Checkbox checked={accepted} onChange={event => setAccepted(event.target.checked)}>I have stored my recovery codes securely</Checkbox>
      </Space> : <Form id="subscriber-security-form" layout="vertical" onFinish={() => void submit()}>
        {mode === "password" && <Alert className="form-alert" type="warning" showIcon title="All sessions will be signed out." />}
        {mode === "link" && <Alert className="form-alert" type="warning" showIcon title="Existing subscription links will stop working." />}
        {mode === "disable" && <Alert className="form-alert" type="warning" showIcon title="Two-factor authentication and recovery codes will be removed. Other sessions will be signed out." />}
        {mode === "recovery" && <Alert className="form-alert" type="warning" showIcon title="Existing recovery codes will stop working. Other sessions will be signed out." />}
        {enrollment ? <>
          {qr && <img src={qr} alt="Authenticator enrollment QR code" width={240} height={240} className="totp-qr" />}
          <Form.Item label="Setup key" htmlFor="subscriber-setup-key"><Space.Compact style={{ width: "100%" }}><Input id="subscriber-setup-key" readOnly value={enrollment.secret} /><Button icon={<CopyOutlined aria-hidden />} aria-label="Copy setup key" onClick={() => void copy(enrollment.secret)} /></Space.Compact></Form.Item>
          <Typography.Paragraph type="secondary">Expires {date(enrollment.expires_at)}</Typography.Paragraph>
        </> : <Form.Item label="Current password" htmlFor="subscriber-security-password" required><Input.Password id="subscriber-security-password" value={password} onChange={event => setPassword(event.target.value)} autoComplete="current-password" required maxLength={1024} disabled={busy} /></Form.Item>}
        {mode === "password" && <>
          <Form.Item label="New password" htmlFor="subscriber-security-new-password" required><Input.Password id="subscriber-security-new-password" value={newPassword} onChange={event => setNewPassword(event.target.value)} autoComplete="new-password" required minLength={12} maxLength={1024} disabled={busy} /></Form.Item>
          <Form.Item label="Confirm password" htmlFor="subscriber-security-confirmation" required validateStatus={confirmation && confirmation !== newPassword ? "error" : undefined} help={confirmation && confirmation !== newPassword ? "Passwords do not match" : undefined}><Input.Password id="subscriber-security-confirmation" value={confirmation} onChange={event => setConfirmation(event.target.value)} autoComplete="new-password" required maxLength={1024} disabled={busy} /></Form.Item>
        </>}
        {needsCode && <Form.Item label={enrollment ? "Authenticator code" : "Authenticator or recovery code"} htmlFor="subscriber-security-code" required><Input id="subscriber-security-code" value={code} onChange={event => setCode(event.target.value)} autoComplete="one-time-code" inputMode={enrollment ? "numeric" : "text"} required maxLength={64} disabled={busy} /></Form.Item>}
      </Form>}
    </Modal>
    <SubscriptionIpPolicyDialog open={ipDialog} onOpenChange={setIpDialog} subscriber onUpdated={setIpPolicy} />
  </Space>;
}
