// frontend/src/components/SubscriptionIpPolicyDialog.vue
<script setup lang="ts">
import { ref, watch } from "vue";
import type { SubscriptionIpPolicy } from "../domain/subscriptions";
import { subscriberIpPolicy, updateSubscriberIpPolicy } from "../services/subscriber-auth";
import { getProductUserIpPolicy, updateProductUserIpPolicy } from "../services/subscriptions";

const props = withDefaults(defineProps<{ open: boolean; username?: string; subscriber?: boolean }>(), {
  username: "",
  subscriber: false,
});
const emit = defineEmits<{ "update:open": [value: boolean]; updated: [value: SubscriptionIpPolicy] }>();
const policy = ref<SubscriptionIpPolicy | null>(null);
const value = ref("");
const loading = ref(false);
const saving = ref(false);
const error = ref("");
let version = 0;

function close() {
  if (!saving.value) emit("update:open", false);
}

async function load() {
  const current = ++version;
  loading.value = true;
  error.value = "";
  try {
    const result = props.subscriber ? await subscriberIpPolicy() : await getProductUserIpPolicy(props.username);
    if (current !== version) return;
    policy.value = result;
    value.value = result.networks.join("\n");
  } catch (failure) {
    if (current === version) error.value = failure instanceof Error ? failure.message : "IP policy unavailable";
  } finally {
    if (current === version) loading.value = false;
  }
}

async function save() {
  if (saving.value) return;
  const current = ++version;
  saving.value = true;
  error.value = "";
  const networks = value.value.split(/[\s,]+/).map(item => item.trim()).filter(Boolean);
  try {
    const result = props.subscriber
      ? await updateSubscriberIpPolicy(networks)
      : await updateProductUserIpPolicy(props.username, networks);
    if (current !== version) return;
    policy.value = result;
    value.value = result.networks.join("\n");
    emit("updated", result);
    emit("update:open", false);
  } catch (failure) {
    if (current === version) error.value = failure instanceof Error ? failure.message : "IP policy update failed";
  } finally {
    if (current === version) saving.value = false;
  }
}

watch(() => [props.open, props.username, props.subscriber] as const, ([open]) => {
  if (open) void load();
  else ++version;
}, { immediate: true });
</script>

<template>
  <v-dialog :model-value="open" max-width="560" persistent scrollable @update:model-value="close">
    <v-card class="ip-policy-dialog">
      <v-card-title class="ip-policy-title"><span>Subscription IP access</span><v-chip :color="policy?.enabled ? 'warning' : 'success'" size="small" variant="tonal">{{ policy?.enabled ? 'Restricted' : 'Unrestricted' }}</v-chip></v-card-title>
      <v-progress-linear v-if="loading" indeterminate color="primary" />
      <v-card-text>
        <v-alert v-if="error" type="error" variant="tonal" class="mb-4">{{ error }}</v-alert>
        <v-textarea v-model="value" label="Allowed IPs and CIDRs" placeholder="203.0.113.8&#10;2001:db8::/48" rows="7" auto-grow :disabled="loading || saving" spellcheck="false" autocomplete="off" />
      </v-card-text>
      <v-card-actions><v-btn :disabled="saving" @click="close">Cancel</v-btn><v-spacer /><v-btn color="primary" prepend-icon="mdi-content-save-outline" :loading="saving" :disabled="loading" @click="save">Save</v-btn></v-card-actions>
    </v-card>
  </v-dialog>
</template>

<style scoped>
.ip-policy-dialog, .ip-policy-dialog :deep(*) { letter-spacing: 0; }
.ip-policy-title { display: flex; align-items: center; justify-content: space-between; gap: 12px; flex-wrap: wrap; overflow: visible; font-size: 18px; white-space: normal; }
.ip-policy-title :deep(.v-chip) { flex-shrink: 0; }
.ip-policy-dialog :deep(.v-card-actions) { flex-wrap: wrap; }
.ip-policy-dialog :deep(textarea) { font-family: ui-monospace, SFMono-Regular, Consolas, monospace; font-size: 13px; }
.ip-policy-dialog :deep(.v-alert__content) { overflow-wrap: anywhere; }
</style>

// frontend/src/react/components/SubscriptionIpPolicyDialog.tsx
import { useCallback, useEffect, useRef, useState } from "react";
import { Alert, Flex, Form, Input, Modal, Spin, Tag } from "antd";
import type { SubscriptionIpPolicy } from "../../domain/subscriptions";
import { subscriberIpPolicy, updateSubscriberIpPolicy } from "../../services/subscriber-auth";
import { getProductUserIpPolicy, updateProductUserIpPolicy } from "../../services/subscriptions";

export interface SubscriptionIpPolicyDialogProps {
  open: boolean; onOpenChange: (open: boolean) => void; username?: string; subscriber?: boolean;
  onUpdated?: (value: SubscriptionIpPolicy) => void;
}
export default function SubscriptionIpPolicyDialog(props: SubscriptionIpPolicyDialogProps) {
  return props.open ? <IpPolicyContent key={`${props.username}:${!!props.subscriber}`} {...props} /> : null;
}
function IpPolicyContent({ username = "", subscriber = false, onOpenChange, onUpdated }: SubscriptionIpPolicyDialogProps) {
  const [policy, setPolicy] = useState<SubscriptionIpPolicy | null>(null), [value, setValue] = useState("");
  const [loading, setLoading] = useState(false), [saving, setSaving] = useState(false), [error, setError] = useState("");
  const version = useRef(0);
  const load = useCallback(async () => {
    const run = ++version.current; setLoading(true); setError("");
    try {
      const result = subscriber ? await subscriberIpPolicy() : await getProductUserIpPolicy(username);
      if (run === version.current) { setPolicy(result); setValue(result.networks.join("\n")); }
    } catch (failure) { if (run === version.current) setError(failure instanceof Error ? failure.message : "IP policy unavailable"); }
    finally { if (run === version.current) setLoading(false); }
  }, [username, subscriber]);
  useEffect(() => { void load(); return () => { ++version.current; }; }, [load]);
  async function save() {
    if (saving || loading || !policy) return;
    const run = ++version.current; setSaving(true); setError("");
    const networks = value.split(/[\s,]+/).map(item => item.trim()).filter(Boolean);
    try {
      const result = subscriber ? await updateSubscriberIpPolicy(networks) : await updateProductUserIpPolicy(username, networks);
      if (run !== version.current) return;
      setPolicy(result); setValue(result.networks.join("\n")); onUpdated?.(result); onOpenChange(false);
    } catch (failure) { if (run === version.current) setError(failure instanceof Error ? failure.message : "IP policy update failed"); }
    finally { if (run === version.current) setSaving(false); }
  }
  return <Modal open title="Subscription IP access" width={560} destroyOnHidden mask={{ closable: false }} keyboard={!saving} closable={!saving}
    onCancel={() => !saving && onOpenChange(false)} onOk={() => void save()} okText="Save" confirmLoading={saving}
    cancelButtonProps={{ disabled: saving }} okButtonProps={{ "aria-label": "Save", "aria-busy": saving, disabled: loading || !policy }}>
    <Flex vertical gap="middle">
      <Tag color={policy?.enabled ? "warning" : "success"}>{policy?.enabled ? "Restricted" : "Unrestricted"}</Tag>
      {loading && <Spin />}{error && <Alert type="error" title={error} showIcon />}
      <Form layout="vertical" preserve={false} onFinish={() => void save()}><Form.Item label="Allowed IPs and CIDRs">
        <Input.TextArea aria-label="Allowed IPs and CIDRs" value={value} onChange={event => setValue(event.target.value)} placeholder={"203.0.113.8\n2001:db8::/48"}
          rows={7} disabled={loading || saving} spellCheck={false} autoComplete="off" />
      </Form.Item></Form>
    </Flex>
  </Modal>;
}
