// frontend/src/components/TemporarySubscriptionDialog.vue
<script setup lang="ts">
import { computed, reactive, ref, watch } from "vue";
import type { TemporarySubscription } from "../domain/temporary-subscriptions";
import { createTemporarySubscription } from "../services/temporary-subscriptions";

const props = defineProps<{
  open: boolean;
  username: string;
  nodes: Array<{ title: string; value: string }>;
}>();
const emit = defineEmits<{
  "update:open": [value: boolean];
  created: [value: TemporarySubscription];
}>();
const form = reactive({
  label: "Temporary subscription",
  node_ids: [] as string[],
  max_access: 1,
  expires_in_seconds: 300,
});
const expiryOptions = [
  { title: "5 minutes", value: 300 },
  { title: "15 minutes", value: 900 },
  { title: "1 hour", value: 3600 },
];
const busy = ref(false);
const error = ref("");
const created = ref<TemporarySubscription | null>(null);
const copied = ref(false);
const canCreate = computed(() => Boolean(
  props.username && form.label.trim() && form.node_ids.length && form.max_access >= 1
  && form.max_access <= 100 && !busy.value,
));

watch(() => props.open, (open) => {
  if (!open) return;
  Object.assign(form, {
    label: "Temporary subscription",
    node_ids: props.nodes.map(item => item.value),
    max_access: 1,
    expires_in_seconds: 300,
  });
  error.value = "";
  created.value = null;
  copied.value = false;
});

async function submit() {
  if (!canCreate.value) return;
  busy.value = true;
  error.value = "";
  try {
    const value = await createTemporarySubscription({
      username: props.username,
      label: form.label.trim(),
      node_ids: form.node_ids,
      max_access: Number(form.max_access),
      expires_in_seconds: form.expires_in_seconds,
    });
    created.value = value;
    emit("created", value);
  } catch (failure) {
    error.value = failure instanceof Error ? failure.message : "Temporary link creation failed";
  } finally {
    busy.value = false;
  }
}

async function copyLink() {
  if (!created.value) return;
  try {
    await navigator.clipboard.writeText(created.value.subscription_url);
    copied.value = true;
  } catch {
    error.value = "Clipboard access failed";
  }
}
</script>

<template>
  <v-dialog :model-value="open" :persistent="busy" max-width="640" scrollable @update:model-value="emit('update:open', $event)">
    <v-card class="temporary-dialog">
      <v-card-title>Create temporary link</v-card-title>
      <v-card-text class="temporary-form">
        <v-alert v-if="error" type="error" variant="tonal">{{ error }}</v-alert>
        <template v-if="!created">
          <v-text-field :model-value="username" label="Subscriber" readonly variant="outlined" density="compact" />
          <v-text-field v-model="form.label" label="Label" variant="outlined" density="compact" maxlength="120" />
          <v-autocomplete v-model="form.node_ids" :items="nodes" label="Nodes" multiple chips closable-chips variant="outlined" />
          <div class="temporary-row">
            <v-text-field v-model.number="form.max_access" type="number" min="1" max="100" label="Downloads" variant="outlined" density="compact" />
            <v-select v-model="form.expires_in_seconds" :items="expiryOptions" label="Expires" variant="outlined" density="compact" />
          </div>
        </template>
        <template v-else>
          <v-text-field :model-value="created.subscription_url" label="Temporary URL" readonly variant="outlined" density="compact">
            <template #append-inner><v-btn :icon="copied ? 'mdi-check' : 'mdi-content-copy'" :aria-label="copied ? 'Copied' : 'Copy temporary URL'" variant="text" size="small" @click="copyLink" /></template>
          </v-text-field>
          <v-alert type="info" variant="tonal" density="compact">URL expiry does not revoke credentials already downloaded.</v-alert>
        </template>
      </v-card-text>
      <v-card-actions>
        <v-btn :disabled="busy" @click="emit('update:open', false)">{{ created ? "Close" : "Cancel" }}</v-btn>
        <v-spacer />
        <v-btn v-if="!created" color="primary" prepend-icon="mdi-link-plus" :loading="busy" :disabled="!canCreate" @click="submit">Create</v-btn>
      </v-card-actions>
    </v-card>
  </v-dialog>
</template>

<style scoped>
.temporary-dialog, .temporary-dialog :deep(*) { letter-spacing: 0; }
.temporary-form { display: grid; gap: 14px; min-width: 0; }
.temporary-row { display: grid; grid-template-columns: minmax(0, 1fr) minmax(0, 1fr); gap: 12px; }
.temporary-dialog :deep(.v-card-title), .temporary-dialog :deep(.v-alert__content) { white-space: normal; overflow-wrap: anywhere; }
@media (max-width: 520px) { .temporary-row { grid-template-columns: minmax(0, 1fr); } }
</style>

// frontend/src/react/components/TemporarySubscriptionDialog.tsx
import { useEffect, useRef, useState } from "react";
import { Alert, Button, Flex, Form, Input, Modal, Select } from "antd";
import { CheckOutlined, CopyOutlined } from "@ant-design/icons";
import type { TemporarySubscription } from "../../domain/temporary-subscriptions";
import { createTemporarySubscription } from "../../services/temporary-subscriptions";
import StrictInputNumber from "./StrictInputNumber";

export interface TemporarySubscriptionDialogProps {
  open: boolean; onOpenChange: (open: boolean) => void; username: string;
  nodes: { title: string; value: string }[]; onCreated?: (value: TemporarySubscription) => void;
}
export default function TemporarySubscriptionDialog(props: TemporarySubscriptionDialogProps) {
  return props.open ? <TemporaryContent key={props.username} {...props} /> : null;
}
function TemporaryContent({ username, nodes, onOpenChange, onCreated }: TemporarySubscriptionDialogProps) {
  const [form, setForm] = useState({ label: "Temporary subscription", node_ids: nodes.map(node => node.value), max_access: 1, expires_in_seconds: 300 });
  const [busy, setBusy] = useState(false), [error, setError] = useState(""), [copied, setCopied] = useState(false);
  const [created, setCreated] = useState<TemporarySubscription | null>(null);
  const version = useRef(0);
  useEffect(() => () => { ++version.current; }, []);
  const canCreate = !!username && !!form.label.trim() && form.node_ids.length > 0
    && form.node_ids.every(id => nodes.some(node => node.value === id)) && Number.isInteger(form.max_access)
    && form.max_access >= 1 && form.max_access <= 100 && !busy;
  async function submit() {
    if (!canCreate) return;
    const run = ++version.current; setBusy(true); setError("");
    try {
      const value = await createTemporarySubscription({ username, ...form, label: form.label.trim() });
      if (run === version.current) { setCreated(value); onCreated?.(value); }
    } catch (failure) { if (run === version.current) setError(failure instanceof Error ? failure.message : "Temporary link creation failed"); }
    finally { if (run === version.current) setBusy(false); }
  }
  async function copyLink() {
    if (!created) return;
    const run = version.current;
    try { await navigator.clipboard.writeText(created.subscription_url); if (run === version.current) setCopied(true); }
    catch { if (run === version.current) setError("Clipboard access failed"); }
  }
  return <Modal open title="Create temporary link" width={640} destroyOnHidden mask={{ closable: !busy }} keyboard={!busy} closable={!busy}
    onCancel={() => !busy && onOpenChange(false)} footer={<Flex justify="space-between"><Button disabled={busy} onClick={() => onOpenChange(false)}>{created ? "Close" : "Cancel"}</Button>
      {!created && <Button type="primary" aria-label="Create" aria-busy={busy} loading={busy} disabled={!canCreate} onClick={() => void submit()}>Create</Button>}</Flex>}>
    {error && <Alert type="error" title={error} showIcon />}
    {!created ? <Form layout="vertical" preserve={false} onFinish={() => void submit()} disabled={busy}>
      <Form.Item label="Subscriber"><Input aria-label="Subscriber" value={username} readOnly /></Form.Item>
      <Form.Item label="Label"><Input aria-label="Label" value={form.label} maxLength={120} onChange={event => setForm({ ...form, label: event.target.value })} /></Form.Item>
      <Form.Item label="Nodes"><Select aria-label="Nodes" mode="multiple" value={form.node_ids} optionFilterProp="label"
        options={nodes.map(node => ({ label: node.title, value: node.value }))} onChange={node_ids => setForm({ ...form, node_ids })} /></Form.Item>
      <Form.Item label="Downloads"><StrictInputNumber aria-label="Downloads" aria-valuemin={1} aria-valuemax={100} value={form.max_access} onChange={number => setForm({ ...form, max_access: number ?? Number.NaN })} /></Form.Item>
      <Form.Item label="Expires"><Select aria-label="Expires" value={form.expires_in_seconds} onChange={expires_in_seconds => setForm({ ...form, expires_in_seconds })}
        options={[{ label: "5 minutes", value: 300 }, { label: "15 minutes", value: 900 }, { label: "1 hour", value: 3600 }]} /></Form.Item>
    </Form> : <Flex vertical gap="middle"><Form.Item label="Temporary URL"><Flex gap="small"><Input aria-label="Temporary URL" value={created.subscription_url} readOnly />
      <Button icon={copied ? <CheckOutlined /> : <CopyOutlined />} aria-label={copied ? "Copied" : "Copy temporary URL"} onClick={() => void copyLink()} /></Flex></Form.Item>
      <Alert type="info" title="URL expiry does not revoke credentials already downloaded." showIcon />
    </Flex>}
  </Modal>;
}
