// frontend/src/react/views/AccountView.tsx
import { CopyOutlined, CheckOutlined, DownloadOutlined, EditOutlined, LoginOutlined, LogoutOutlined, ReloadOutlined } from "@ant-design/icons";
import { Alert, Button, Card, Descriptions, Flex, Form, Input, Layout, Progress, Segmented, Select, Space, Spin, Table, Tabs, Tag, Typography } from "antd";
import { useCallback, useEffect, useRef, useState } from "react";
import { Link } from "react-router-dom";
import type { ProductUserSubscriptionToken, SubscriptionClientFormat } from "../../domain/subscriptions";
import type { SubscriberSubscriptionProfile } from "../../domain/subscription-profiles";
import {
  loadSubscriberSession, subscriberFormatUrl, subscriberProfile, subscriberProfiles, subscriberRegister,
  subscriberSignIn, subscriberSignOut, subscriberState, subscriberToken, verifySubscriberLogin,
  type SubscriberProfile,
} from "../../services/subscriber-auth";
import PrivateRoutedNodesPanel from "../components/PrivateRoutedNodesPanel";
import SubscriberSecurityPanel from "../components/SubscriberSecurityPanel";
import SubscriptionShortCodeDialog from "../components/SubscriptionShortCodeDialog";
import TemplatesWorkspace from "../components/TemplatesWorkspace";
import { useAsyncScope } from "../hooks/useAsyncScope";
import { useSubscriberSession } from "../hooks/useSession";

const formats: { label: string; value: SubscriptionClientFormat }[] = [
  { label: "Clash / Mihomo", value: "clash" }, { label: "sing-box", value: "sing-box" }, { label: "Surge", value: "surge" },
  { label: "Xray", value: "xray" }, { label: "URI list", value: "uri-list" }, { label: "Base64", value: "base64" },
];
const date = (value?: string | null) => value ? new Date(value).toLocaleDateString() : "None";
function bytes(value: number) {
  if (!Number.isFinite(value) || value <= 0) return "0 B";
  const unit = Math.min(Math.floor(Math.log(value) / Math.log(1024)), 4);
  return `${(value / 1024 ** unit).toLocaleString(undefined, { maximumFractionDigits: 1 })} ${["B", "KiB", "MiB", "GiB", "TiB"][unit]}`;
}
function clearInvitationFragment() {
  if (typeof window !== "undefined") window.history.replaceState(window.history.state, "", window.location.pathname + window.location.search);
}

export default function AccountView() {
  const auth = useSubscriberSession();
  const [initializing, setInitializing] = useState(true);
  const [invitation, setInvitation] = useState(() => typeof window === "undefined" ? "" : new URLSearchParams(window.location.hash.slice(1)).get("invite") ?? "");
  useEffect(() => {
    let active = true;
    subscriberState.ready = false;
    void loadSubscriberSession().finally(() => { if (active) setInitializing(false); });
    return () => { active = false; };
  }, []);
  const clearInvitation = useCallback(() => { setInvitation(""); clearInvitationFragment(); }, []);
  useEffect(() => { if (auth.session?.authenticated) clearInvitation(); }, [auth.session?.authenticated, clearInvitation]);
  if (initializing || !auth.ready) return <div className="auth-page" role="status" aria-label="Loading account"><Spin size="large" /></div>;
  if (!auth.session?.authenticated) return <SubscriberSignIn invitation={invitation} onClearInvitation={clearInvitation} />;
  return <SubscriberWorkspace key={auth.session.username} username={auth.session.username ?? ""} />;
}

function SubscriberSignIn({ invitation, onClearInvitation }: { invitation: string; onClearInvitation: () => void }) {
  const auth = useSubscriberSession();
  const scope = useAsyncScope();
  const busyRef = useRef(false);
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  const [email, setEmail] = useState("");
  const [displayName, setDisplayName] = useState("");
  const [code, setCode] = useState("");
  const [challenge, setChallenge] = useState("");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const registering = Boolean(invitation);
  const canRegister = Boolean(username.trim() && password.length >= 12 && password === confirmPassword);

  async function submit() {
    if (busyRef.current || (challenge ? !code : !username || !password)) return;
    const current = scope.begin(); busyRef.current = true; setBusy(true); setError("");
    try {
      const result = challenge ? await verifySubscriberLogin(challenge, code) : await subscriberSignIn(username, password);
      if (scope.isCurrent(current)) setChallenge(result.challenge ?? "");
    } catch (failure) {
      if (scope.isCurrent(current)) setError(failure instanceof Error ? failure.message : "Sign-in failed");
    } finally { if (scope.isCurrent(current)) { setPassword(""); setCode(""); setBusy(false); busyRef.current = false; } }
  }
  async function register() {
    if (busyRef.current || !canRegister) return;
    const current = scope.begin(); busyRef.current = true; setBusy(true); setError("");
    let created = false;
    try {
      await subscriberRegister({ token: invitation, username: username.trim(), password, email: email.trim() || null, display_name: displayName.trim() || null });
      created = true;
      if (!scope.isCurrent(current)) return;
      await subscriberSignIn(username.trim(), password);
      if (scope.isCurrent(current)) onClearInvitation();
    } catch (failure) {
      if (scope.isCurrent(current)) {
        if (created) onClearInvitation();
        const detail = failure instanceof Error ? failure.message : "Registration failed";
        setError(created ? `Account created. Sign-in failed: ${detail}` : detail);
      }
    } finally { if (scope.isCurrent(current)) { setPassword(""); setConfirmPassword(""); setBusy(false); busyRef.current = false; } }
  }
  function restart() { scope.invalidate(); setChallenge(""); setCode(""); setPassword(""); setError(""); }
  function cancelRegistration() { onClearInvitation(); setPassword(""); setConfirmPassword(""); setEmail(""); setDisplayName(""); setError(""); }

  return <section className="auth-page"><Card className="auth-card"><Space orientation="vertical" size="large" style={{ width: "100%" }}>
    <div><Typography.Title level={2}>Open Node</Typography.Title><Typography.Title level={4}>{registering ? "Create Subscriber Account" : challenge ? "Two-Factor Verification" : "Subscriber Sign-In"}</Typography.Title></div>
    {auth.error ? <Alert type="error" showIcon title={auth.error} action={<Button icon={<ReloadOutlined aria-hidden />} aria-label="Retry account connection" onClick={() => void loadSubscriberSession()} />} /> : <Form layout="vertical" onFinish={() => void (registering ? register() : submit())}>
      {error && <Alert className="form-alert" type="error" showIcon title={error} />}
      {(!challenge || registering) && <Form.Item label="Username" htmlFor="subscriber-username" required><Input id="subscriber-username" value={username} onChange={event => setUsername(event.target.value)} autoComplete="username" autoFocus required maxLength={80} disabled={busy} /></Form.Item>}
      {registering && <>
        <Form.Item label="Display name" htmlFor="subscriber-display-name"><Input id="subscriber-display-name" value={displayName} onChange={event => setDisplayName(event.target.value)} autoComplete="name" maxLength={120} disabled={busy} /></Form.Item>
        <Form.Item label="Email" htmlFor="subscriber-email"><Input id="subscriber-email" type="email" value={email} onChange={event => setEmail(event.target.value)} autoComplete="email" maxLength={255} disabled={busy} /></Form.Item>
      </>}
      {(!challenge || registering) && <Form.Item label="Password" htmlFor="subscriber-password" required><Input.Password id="subscriber-password" value={password} onChange={event => setPassword(event.target.value)} autoComplete={registering ? "new-password" : "current-password"} minLength={registering ? 12 : undefined} required maxLength={1024} disabled={busy} /></Form.Item>}
      {registering && <Form.Item label="Confirm password" htmlFor="subscriber-confirm-password" required validateStatus={confirmPassword && confirmPassword !== password ? "error" : undefined} help={confirmPassword && confirmPassword !== password ? "Passwords do not match" : undefined}><Input.Password id="subscriber-confirm-password" value={confirmPassword} onChange={event => setConfirmPassword(event.target.value)} autoComplete="new-password" required minLength={12} maxLength={1024} disabled={busy} /></Form.Item>}
      {!registering && challenge && <Form.Item label="Authenticator or recovery code" htmlFor="subscriber-login-code" required><Input id="subscriber-login-code" value={code} onChange={event => setCode(event.target.value)} autoComplete="one-time-code" autoFocus required maxLength={64} disabled={busy} /></Form.Item>}
      <Space wrap><Button type="primary" htmlType="submit" aria-label={registering ? "Create Account" : challenge ? "Verify" : "Sign In"} icon={<LoginOutlined aria-hidden />} loading={busy} disabled={registering ? !canRegister : challenge ? !code : !username || !password}>{registering ? "Create Account" : challenge ? "Verify" : "Sign In"}</Button>
        {registering ? <Button disabled={busy} onClick={cancelRegistration}>Sign In</Button> : challenge && <Button disabled={busy} onClick={restart}>Back</Button>}
      </Space>
    </Form>}
    <Link to="/">Administrator sign-in</Link>
  </Space></Card></section>;
}

function SubscriberWorkspace({ username }: { username: string }) {
  const scope = useAsyncScope();
  const [profile, setProfile] = useState<SubscriberProfile | null>(null);
  const [subscription, setSubscription] = useState<ProductUserSubscriptionToken | null>(null);
  const [profiles, setProfiles] = useState<SubscriberSubscriptionProfile[]>([]);
  const [configuration, setConfiguration] = useState("default");
  const [format, setFormat] = useState<SubscriptionClientFormat>("clash");
  const [linkType, setLinkType] = useState("full");
  const [tab, setTab] = useState("subscription");
  const [loading, setLoading] = useState(false);
  const [logoutBusy, setLogoutBusy] = useState(false);
  const [error, setError] = useState("");
  const [copied, setCopied] = useState(false);
  const [shortCodeOpen, setShortCodeOpen] = useState(false);
  const selectedProfile = profiles.find(item => item.id === configuration) ?? null;
  const quota = profile?.quota;
  const status = !quota?.has_plan ? "No plan" : quota.expired ? "Expired" : quota.over_quota ? "Quota reached" : "Active";
  let url = "";
  try {
    const value = selectedProfile ? new URL(selectedProfile.subscription_url) : subscription ? new URL(subscriberFormatUrl(subscription, format, linkType === "short")) : null;
    if (value && ["http:", "https:"].includes(value.protocol)) { value.searchParams.set("format", format); url = value.toString(); }
  } catch { /* A malformed server URL must not break or become an executable link. */ }
  const load = useCallback(async () => {
    const current = scope.begin(); setLoading(true); setError("");
    try {
      const [account, token, extra] = await Promise.all([subscriberProfile(), subscriberToken(), subscriberProfiles()]);
      if (!scope.isCurrent(current)) return;
      setProfile(account); setSubscription(token); setProfiles(extra.profiles);
      setConfiguration(previous => previous === "default" || extra.profiles.some(item => item.id === previous) ? previous : "default");
    } catch (failure) {
      if (scope.isCurrent(current)) setError(failure instanceof Error ? failure.message : "Account unavailable");
    } finally { if (scope.isCurrent(current)) setLoading(false); }
  }, [scope]);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { setCopied(false); }, [url]);
  async function logout() {
    if (logoutBusy) return;
    setLogoutBusy(true); setError("");
    try { await subscriberSignOut(); }
    catch (failure) { setError(failure instanceof Error ? failure.message : "Sign-out failed"); }
    finally { setLogoutBusy(false); }
  }
  async function copyLink() {
    if (!url) return;
    try { await navigator.clipboard.writeText(url); setCopied(true); }
    catch { setError("Clipboard unavailable"); }
  }
  const subscriptionContent = profile && quota ? <Space orientation="vertical" size="large" style={{ width: "100%" }}>
    <section aria-label="Current plan"><Card title={quota.plan_name || "No plan assigned"} extra={<Tag color={quota.available ? "success" : "warning"}>{status}</Tag>}>
      <Typography.Paragraph type="secondary">Current plan</Typography.Paragraph>
      <Typography.Title level={3}>{bytes(quota.charged_usage_bytes)} <Typography.Text type="secondary">/ {quota.traffic_limit_bytes ? bytes(quota.traffic_limit_bytes) : quota.has_plan ? "Unlimited" : "0 B"}</Typography.Text></Typography.Title>
      <Progress percent={Math.min(100, Math.max(0, quota.percent_used))} status={quota.over_quota ? "exception" : undefined} aria-label="Traffic quota used" />
      <Descriptions column={{ xs: 1, sm: 2, lg: 3 }} items={[
        { key: "expires", label: "Expires", children: date(quota.plan_expires_at) },
        { key: "reset", label: "Next reset", children: date(quota.next_reset_at) },
        { key: "speed", label: "Default speed", children: profile.speed_limit_mbps ? `${profile.speed_limit_mbps} Mbps` : "Unlimited" },
        { key: "connections", label: "Connection limit", children: profile.device_limit || "Unlimited" },
        { key: "upload", label: "Uploaded", children: bytes(quota.upload) },
        { key: "download", label: "Downloaded", children: bytes(quota.download) },
      ]} />
    </Card></section>
    <section aria-label="Subscription links"><Card title="Subscription"><Form layout="vertical">
      {profiles.length > 0 && <Form.Item label="Configuration" htmlFor="account-configuration"><Select id="account-configuration" value={configuration} options={[{ label: "Default subscription", value: "default" }, ...profiles.map(item => ({ label: item.name, value: item.id }))]} onChange={setConfiguration} /></Form.Item>}
      <Flex gap="middle" justify="space-between" align="center" wrap className="form-alert">
        {!selectedProfile && subscription?.short_links_enabled ? <Segmented aria-label="Subscription link type" value={linkType} onChange={setLinkType} options={[{ label: "Full", value: "full" }, { label: "Short", value: "short" }]} /> : <Tag>{selectedProfile ? "MMWX profile" : "Secure link"}</Tag>}
        {subscription?.short_links_enabled && <Button icon={<EditOutlined aria-hidden />} aria-label="Edit subscription short code" disabled={loading || !subscription || Boolean(selectedProfile)} onClick={() => setShortCodeOpen(true)} />}
      </Flex>
      {selectedProfile && (!selectedProfile.enabled || selectedProfile.warnings.length > 0) && <Alert className="form-alert" type={selectedProfile.enabled ? "warning" : "error"} showIcon title={selectedProfile.enabled ? selectedProfile.warnings.join("; ") : "This profile needs administrator configuration."} />}
      <Form.Item label="Client format" htmlFor="account-client-format"><Select id="account-client-format" value={format} options={formats} onChange={setFormat} /></Form.Item>
      <Form.Item label="Subscription URL" htmlFor="account-subscription-url"><Input id="account-subscription-url" value={url} readOnly /></Form.Item>
      <Space wrap><Button icon={copied ? <CheckOutlined aria-hidden /> : <CopyOutlined aria-hidden />} aria-label="Copy subscription link" disabled={!url} onClick={() => void copyLink()}>{copied ? "Copied" : "Copy link"}</Button><Button icon={<DownloadOutlined aria-hidden />} aria-label="Download subscription" href={url || undefined} disabled={!url || !quota.available || selectedProfile?.enabled === false} rel="noreferrer" download>Download</Button></Space>
      {!quota.available && <Alert className="form-alert" type="warning" showIcon title={!quota.has_plan ? "No subscription plan assigned" : quota.expired ? "Your plan has expired" : "Your traffic quota has been reached"} />}
    </Form></Card></section>
    {profile.node_limits?.length > 0 && <section aria-label="Node limits"><Card title="Node limits"><Table rowKey="node_id" dataSource={profile.node_limits} pagination={false} scroll={{ x: 420 }} columns={[
      { title: "Node", dataIndex: "name" }, { title: "Speed", dataIndex: "speed_limit_mbps", render: value => value ? `${value} Mbps` : "Unlimited speed" },
      { title: "Connections", dataIndex: "device_limit", render: value => value ? `${value} connections` : "Unlimited connections" },
    ]} /></Card></section>}
  </Space> : null;
  return <Layout className="account-layout">
    <Layout.Header className="application-header"><Typography.Title level={4} style={{ margin: 0 }}>Open Node</Typography.Title><Space><Typography.Text>{username}</Typography.Text><Button icon={<LogoutOutlined aria-hidden />} aria-label="Sign out" loading={logoutBusy} onClick={() => void logout()} /></Space></Layout.Header>
    <Layout.Content className="account-content"><Space orientation="vertical" size="middle" style={{ width: "100%" }}>
      <Flex gap="middle" justify="space-between" align="center"><Typography.Title level={2}>{profile?.display_name || username}</Typography.Title><Button icon={<ReloadOutlined aria-hidden />} aria-label="Refresh account" loading={loading} onClick={() => void load()} /></Flex>
      {error && <Alert type="error" showIcon title={error} />}
      {loading && <Spin aria-label="Refreshing account" />}
      <Tabs activeKey={tab} onChange={setTab} destroyOnHidden items={[
        { key: "subscription", label: "Subscription", children: subscriptionContent },
        { key: "routes", label: "Routes", children: <PrivateRoutedNodesPanel /> },
        { key: "templates", label: "Templates", children: <TemplatesWorkspace subscriber /> },
        { key: "security", label: "Security", children: <SubscriberSecurityPanel onChanged={() => void load()} /> },
      ]} />
    </Space></Layout.Content>
    <SubscriptionShortCodeDialog open={shortCodeOpen} onOpenChange={setShortCodeOpen} username={username} subscriber onSaved={setSubscription} />
  </Layout>;
}

// frontend/src/views/AccountView.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, watch } from "vue";
import SubscriberSecurityPanel from "../components/SubscriberSecurityPanel.vue";
import PrivateRoutedNodesPanel from "../components/PrivateRoutedNodesPanel.vue";
import TemplatesWorkspace from "../components/TemplatesWorkspace.vue";
import SubscriptionShortCodeDialog from "../components/SubscriptionShortCodeDialog.vue";
import type { ProductUserSubscriptionToken, SubscriptionClientFormat } from "../domain/subscriptions";
import type { SubscriberSubscriptionProfile } from "../domain/subscription-profiles";
import {
  loadSubscriberSession, subscriberFormatUrl, subscriberProfile, subscriberProfiles, subscriberSignIn, subscriberSignOut,
  subscriberRegister, subscriberState, subscriberToken, verifySubscriberLogin, type SubscriberProfile,
} from "../services/subscriber-auth";

const username = ref("");
const password = ref("");
const confirmPassword = ref("");
const email = ref("");
const displayName = ref("");
const invitationToken = ref("");
const code = ref("");
const challenge = ref("");
const busy = ref(false);
const signInError = ref("");
const error = ref("");
const loading = ref(false);
const tab = ref("subscription");
const profile = ref<SubscriberProfile | null>(null);
const subscription = ref<ProductUserSubscriptionToken | null>(null);
const subscriptionProfiles = ref<SubscriberSubscriptionProfile[]>([]);
const configuration = ref("default");
const format = ref<SubscriptionClientFormat>("clash");
const copied = ref(false);
const shortCodeOpen = ref(false);
const linkType = ref("full");
const registering = computed(() => Boolean(invitationToken.value));
const canRegister = computed(() => Boolean(
  username.value.trim() && password.value.length >= 12 && password.value === confirmPassword.value,
));
const formats = [
  { title: "Clash / Mihomo", value: "clash" }, { title: "sing-box", value: "sing-box" },
  { title: "Surge", value: "surge" }, { title: "Xray", value: "xray" },
  { title: "URI list", value: "uri-list" }, { title: "Base64", value: "base64" },
];
let version = 0;
const selectedProfile = computed(() => subscriptionProfiles.value.find(item => item.id === configuration.value) ?? null);
const configurationOptions = computed(() => [
  { title: "Default subscription", value: "default" },
  ...subscriptionProfiles.value.map(item => ({ title: item.name, value: item.id })),
]);
const url = computed(() => {
  if (selectedProfile.value) {
    const value = new URL(selectedProfile.value.subscription_url);
    value.searchParams.set("format", format.value);
    return value.toString();
  }
  return subscription.value ? subscriberFormatUrl(subscription.value, format.value, linkType.value === "short") : "";
});
const quota = computed(() => profile.value?.quota);
const status = computed(() => !quota.value?.has_plan ? "No plan" : quota.value.expired ? "Expired" : quota.value.over_quota ? "Quota reached" : "Active");
const date = (value?: string | null) => value ? new Date(value).toLocaleDateString() : "None";
function bytes(value: number) {
  if (!value) return "0 B";
  const unit = Math.min(Math.floor(Math.log(value) / Math.log(1024)), 4);
  return `${(value / 1024 ** unit).toLocaleString(undefined, { maximumFractionDigits: 1 })} ${["B", "KiB", "MiB", "GiB", "TiB"][unit]}`;
}
async function submit() {
  if (busy.value) return;
  busy.value = true; signInError.value = "";
  try {
    const result = challenge.value ? await verifySubscriberLogin(challenge.value, code.value) : await subscriberSignIn(username.value, password.value);
    challenge.value = result.challenge ?? "";
  } catch (failure) { signInError.value = failure instanceof Error ? failure.message : "Sign-in failed"; }
  finally { password.value = ""; code.value = ""; busy.value = false; }
}
async function submitRegistration() {
  if (busy.value || !canRegister.value) return;
  busy.value = true; signInError.value = "";
  let created = false;
  try {
    await subscriberRegister({
      token: invitationToken.value,
      username: username.value.trim(),
      password: password.value,
      email: email.value.trim() || null,
      display_name: displayName.value.trim() || null,
    });
    created = true;
    await subscriberSignIn(username.value.trim(), password.value);
    clearInvitation();
  } catch (failure) {
    if (created) clearInvitation();
    const detail = failure instanceof Error ? failure.message : "Registration failed";
    signInError.value = created ? `Account created. Sign-in failed: ${detail}` : detail;
  } finally {
    password.value = ""; confirmPassword.value = ""; busy.value = false;
  }
}
function restartSignIn() { challenge.value = ""; code.value = ""; password.value = ""; signInError.value = ""; }
function clearInvitation() {
  invitationToken.value = "";
  window.history.replaceState(window.history.state, "", window.location.pathname + window.location.search);
}
function cancelRegistration() {
  clearInvitation();
  confirmPassword.value = ""; email.value = ""; displayName.value = ""; signInError.value = "";
}
async function load() {
  const current = ++version;
  loading.value = true; error.value = "";
  try {
    const [account, token, extraProfiles] = await Promise.all([
      subscriberProfile(), subscriberToken(), subscriberProfiles(),
    ]);
    if (current === version) {
      profile.value = account;
      subscription.value = token;
      subscriptionProfiles.value = extraProfiles.profiles;
      if (!configurationOptions.value.some(item => item.value === configuration.value)) configuration.value = "default";
    }
  } catch (failure) {
    if (current === version) error.value = failure instanceof Error ? failure.message : "Account unavailable";
  } finally { if (current === version) loading.value = false; }
}
async function logout() {
  error.value = "";
  try { await subscriberSignOut(); }
  catch (failure) { error.value = failure instanceof Error ? failure.message : "Sign-out failed"; }
}
async function copyLink() {
  try { await navigator.clipboard.writeText(url.value); copied.value = true; }
  catch { error.value = "Clipboard unavailable"; }
}
watch(url, () => { copied.value = false; });
watch(() => subscriberState.ready && subscriberState.session?.authenticated, (authenticated) => {
  shortCodeOpen.value = false; linkType.value = "full";
  ++version; profile.value = null; subscription.value = null; subscriptionProfiles.value = []; configuration.value = "default"; error.value = "";
  if (authenticated) { clearInvitation(); tab.value = "subscription"; void load(); }
  else restartSignIn();
});
onMounted(async () => {
  invitationToken.value = new URLSearchParams(window.location.hash.slice(1)).get("invite") ?? "";
  subscriberState.ready = false;
  await loadSubscriberSession();
});
onBeforeUnmount(() => {
  ++version; password.value = ""; confirmPassword.value = ""; code.value = ""; challenge.value = "";
});
</script>

<template>
  <div v-if="!subscriberState.ready" class="auth-page" role="status" aria-label="Loading account"><v-progress-circular indeterminate color="primary" /></div>
  <section v-else-if="!subscriberState.session?.authenticated" class="auth-page">
    <div class="auth-workspace">
      <div class="brand-mark" aria-hidden="true">ON</div><h1>Open Node</h1><h2>{{ registering ? 'Create Subscriber Account' : challenge ? 'Two-Factor Verification' : 'Subscriber Sign-In' }}</h2>
      <v-alert v-if="subscriberState.error" type="error" variant="tonal">{{ subscriberState.error }}<v-btn icon="mdi-refresh" aria-label="Retry account connection" title="Retry account connection" @click="loadSubscriberSession()" /></v-alert>
      <form v-else-if="registering" class="auth-form" @submit.prevent="submitRegistration">
        <v-alert v-if="signInError" type="error" variant="tonal">{{ signInError }}</v-alert>
        <v-text-field v-model="username" label="Username" autocomplete="username" autofocus required maxlength="80" :disabled="busy" />
        <v-text-field v-model="displayName" label="Display name" autocomplete="name" maxlength="120" :disabled="busy" />
        <v-text-field v-model="email" label="Email" type="email" autocomplete="email" maxlength="255" :disabled="busy" />
        <v-text-field v-model="password" label="Password" type="password" autocomplete="new-password" required minlength="12" maxlength="1024" :disabled="busy" />
        <v-text-field v-model="confirmPassword" label="Confirm password" type="password" autocomplete="new-password" required minlength="12" maxlength="1024" :disabled="busy" :error-messages="confirmPassword && password !== confirmPassword ? ['Passwords do not match'] : []" />
        <v-btn type="submit" color="primary" prepend-icon="mdi-account-plus-outline" :loading="busy" :disabled="!canRegister">Create Account</v-btn>
        <v-btn variant="text" prepend-icon="mdi-arrow-left" :disabled="busy" @click="cancelRegistration">Sign In</v-btn>
      </form>
      <form v-else class="auth-form" @submit.prevent="submit">
        <v-alert v-if="signInError" type="error" variant="tonal">{{ signInError }}</v-alert>
        <template v-if="!challenge"><v-text-field v-model="username" label="Username" autocomplete="username" autofocus required maxlength="80" :disabled="busy" /><v-text-field v-model="password" label="Password" type="password" autocomplete="current-password" required maxlength="1024" :disabled="busy" /></template>
        <v-text-field v-else v-model="code" label="Authenticator or recovery code" autocomplete="one-time-code" autofocus required maxlength="64" :disabled="busy" />
        <v-btn type="submit" color="primary" prepend-icon="mdi-login" :loading="busy" :disabled="challenge ? !code : !username || !password">{{ challenge ? 'Verify' : 'Sign In' }}</v-btn>
        <v-btn v-if="challenge" variant="text" prepend-icon="mdi-arrow-left" :disabled="busy" @click="restartSignIn">Back</v-btn>
      </form>
      <router-link to="/" class="account-admin-link">Administrator sign-in</router-link>
    </div>
  </section>
  <div v-else class="subscriber-account">
    <header class="account-header"><div class="account-brand"><div class="brand-mark" aria-hidden="true">ON</div><h1>Open Node</h1></div><div class="account-identity"><span>{{ subscriberState.session.username }}</span><v-tooltip text="Sign out"><template #activator="{ props: tip }"><v-btn v-bind="tip" icon="mdi-logout" aria-label="Sign out" variant="text" @click="logout" /></template></v-tooltip></div></header>
    <main class="account-content">
      <div class="account-heading"><h2>{{ profile?.display_name || subscriberState.session.username }}</h2><v-tooltip text="Refresh account"><template #activator="{ props: tip }"><v-btn v-bind="tip" icon="mdi-refresh" aria-label="Refresh account" variant="text" :loading="loading" @click="load" /></template></v-tooltip></div>
      <v-tabs v-model="tab" color="primary" class="account-tabs"><v-tab value="subscription" prepend-icon="mdi-link-variant">Subscription</v-tab><v-tab value="routes" prepend-icon="mdi-routes">Routes</v-tab><v-tab value="templates" prepend-icon="mdi-file-document-edit-outline">Templates</v-tab><v-tab value="security" prepend-icon="mdi-shield-account-outline">Security</v-tab></v-tabs>
      <v-alert v-if="error" type="error" variant="tonal" class="my-4">{{ error }}</v-alert>
      <v-progress-linear v-if="loading" indeterminate color="primary" />
      <template v-if="tab === 'subscription' && profile && quota">
        <section class="account-plan" aria-label="Current plan">
          <div class="account-plan-title"><div><p class="account-label">Current plan</p><h3>{{ quota.plan_name || 'No plan assigned' }}</h3></div><v-chip :color="quota.available ? 'success' : 'warning'" size="small" variant="tonal">{{ status }}</v-chip></div>
          <div class="account-usage"><strong>{{ bytes(quota.charged_usage_bytes) }}</strong><span>/ {{ quota.traffic_limit_bytes ? bytes(quota.traffic_limit_bytes) : quota.has_plan ? 'Unlimited' : '0 B' }}</span></div>
          <v-progress-linear :model-value="Math.min(quota.percent_used, 100)" :color="quota.over_quota ? 'error' : 'primary'" height="6" class="my-4" aria-label="Traffic quota used" />
          <dl class="account-facts"><div><dt>Expires</dt><dd>{{ date(quota.plan_expires_at) }}</dd></div><div><dt>Next reset</dt><dd>{{ date(quota.next_reset_at) }}</dd></div><div><dt>Default speed</dt><dd>{{ profile.speed_limit_mbps ? `${profile.speed_limit_mbps} Mbps` : 'Unlimited' }}</dd></div><div><dt>Connection limit</dt><dd>{{ profile.device_limit || 'Unlimited' }}</dd></div><div><dt>Uploaded</dt><dd>{{ bytes(quota.upload) }}</dd></div><div><dt>Downloaded</dt><dd>{{ bytes(quota.download) }}</dd></div></dl>
        </section>
        <section class="account-links" aria-label="Subscription links">
          <h3>Subscription</h3>
          <v-select v-if="subscriptionProfiles.length" v-model="configuration" :items="configurationOptions" label="Configuration" variant="outlined" density="compact" hide-details prepend-inner-icon="mdi-file-tree-outline" />
          <div class="account-link-mode"><v-btn-toggle v-if="!selectedProfile && subscription?.short_links_enabled" v-model="linkType" mandatory density="compact" color="primary" variant="outlined" aria-label="Subscription link type"><v-btn value="full">Full</v-btn><v-btn value="short">Short</v-btn></v-btn-toggle><v-chip v-else size="small" variant="tonal" prepend-icon="mdi-link-variant">{{ selectedProfile ? 'MMWX profile' : 'Secure link' }}</v-chip><v-tooltip v-if="subscription?.short_links_enabled" text="Edit subscription short code"><template #activator="{ props: tip }"><v-btn v-bind="tip" icon="mdi-link-edit" aria-label="Edit subscription short code" variant="text" :disabled="loading || !subscription || Boolean(selectedProfile)" @click="shortCodeOpen = true" /></template></v-tooltip></div>
          <v-alert v-if="selectedProfile && (!selectedProfile.enabled || selectedProfile.warnings.length)" :type="selectedProfile.enabled ? 'warning' : 'error'" variant="tonal" density="compact">{{ selectedProfile.enabled ? selectedProfile.warnings.join('; ') : 'This profile needs administrator configuration.' }}</v-alert>
          <div class="account-link-controls"><v-select v-model="format" :items="formats" label="Client format" variant="outlined" density="compact" hide-details /><div class="account-link-actions"><v-tooltip :text="copied ? 'Copied' : 'Copy subscription link'"><template #activator="{ props: tip }"><v-btn v-bind="tip" :icon="copied ? 'mdi-check' : 'mdi-content-copy'" aria-label="Copy subscription link" variant="text" :disabled="!url" @click="copyLink" /></template></v-tooltip><v-tooltip text="Download subscription"><template #activator="{ props: tip }"><v-btn v-bind="tip" icon="mdi-download" aria-label="Download subscription" variant="text" :href="url" :disabled="!url || !quota.available || selectedProfile?.enabled === false" rel="noreferrer" download /></template></v-tooltip></div></div>
          <v-text-field :model-value="url" label="Subscription URL" variant="outlined" density="compact" readonly hide-details />
          <v-alert v-if="!quota.available" type="warning" variant="tonal" class="mt-4">{{ !quota.has_plan ? 'No subscription plan assigned' : quota.expired ? 'Your plan has expired' : 'Your traffic quota has been reached' }}</v-alert>
        </section>
        <section v-if="profile.node_limits?.length" class="account-nodes" aria-label="Node limits">
          <h3>Node limits</h3>
          <div v-for="node in profile.node_limits" :key="node.node_id" class="account-node-limit">
            <strong>{{ node.name }}</strong><span>{{ node.speed_limit_mbps ? `${node.speed_limit_mbps} Mbps` : 'Unlimited speed' }}</span><span>{{ node.device_limit ? `${node.device_limit} connections` : 'Unlimited connections' }}</span>
          </div>
        </section>
      </template>
      <PrivateRoutedNodesPanel v-else-if="tab === 'routes'" />
      <TemplatesWorkspace v-else-if="tab === 'templates'" subscriber class="account-templates" />
      <SubscriberSecurityPanel v-else-if="tab === 'security'" class="account-security-panel" @changed="load" />
    </main>
    <SubscriptionShortCodeDialog v-model:open="shortCodeOpen" :username="subscriberState.session?.username ?? ''" subscriber @saved="subscription = $event" />
  </div>
</template>

<style scoped>
.subscriber-account, .subscriber-account :deep(*) { letter-spacing: 0; }
.subscriber-account { min-height: 100dvh; background: #fff; }
.account-header { display: flex; align-items: center; justify-content: space-between; gap: 16px; padding: 18px 28px; border-bottom: 1px solid #dbe5e0; }
.account-brand, .account-identity { display: flex; align-items: center; gap: 12px; min-width: 0; }
.account-brand { flex-shrink: 0; }
.account-brand h1 { font-size: 20px; }
.account-identity { font-size: 13px; overflow-wrap: anywhere; }
.account-content { max-width: 1000px; margin: 0 auto; padding: 32px 28px 60px; }
.account-heading { display: flex; align-items: center; justify-content: space-between; gap: 16px; margin-bottom: 12px; }
.account-heading h2 { font-size: 24px; overflow-wrap: anywhere; min-width: 0; }
.account-tabs { border-bottom: 1px solid #dbe5e0; }
.account-plan { padding: 28px 0; }
.account-plan-title { display: flex; justify-content: space-between; align-items: center; gap: 12px; }
.account-label, .account-facts dt { font-size: 12px; color: #66736f; }
.account-plan h3 { font-size: 20px; margin-top: 6px; overflow-wrap: anywhere; }
.account-usage { display: flex; align-items: baseline; flex-wrap: wrap; gap: 8px; margin-top: 28px; }
.account-usage strong { font-size: 28px; }
.account-usage span { font-size: 14px; color: #66736f; }
.account-facts { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 24px; padding-top: 12px; }
.account-facts dd { font-size: 14px; margin-top: 6px; overflow-wrap: anywhere; }
.account-links { border-top: 1px solid #dbe5e0; padding: 28px 0; }
.account-links h3 { font-size: 18px; margin-bottom: 20px; }
.account-link-controls { display: grid; grid-template-columns: minmax(0, 300px) auto; justify-content: space-between; align-items: center; gap: 16px; margin-bottom: 20px; }
.account-link-actions { display: flex; }
.account-link-mode { display: flex; justify-content: space-between; align-items: center; gap: 16px; margin-bottom: 20px; }
.account-nodes { border-top: 1px solid #dbe5e0; padding: 28px 0; }
.account-nodes h3 { font-size: 18px; margin-bottom: 20px; }
.account-node-limit { display: grid; grid-template-columns: minmax(0, 1.5fr) minmax(0, 1fr) minmax(0, 1fr); gap: 16px; padding-block: 14px; border-bottom: 1px solid #e9eeeb; font-size: 14px; overflow-wrap: anywhere; }
.account-security-panel { padding-top: 24px; }
.account-templates { padding-top: 24px; }
.account-admin-link { font-size: 13px; color: #176b5b; justify-self: start; }
@media (max-width: 600px) {
  .account-header { padding: 14px 16px; flex-wrap: wrap; }
  .account-content { padding: 24px 16px 40px; }
  .account-facts { grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 20px; }
  .account-heading h2 { font-size: 22px; }
  .account-link-controls { gap: 8px; }
  .account-node-limit { grid-template-columns: minmax(0, 1fr); gap: 8px; }
  .account-tabs :deep(.v-slide-group__content) { width: 100%; min-width: 100%; max-width: 100%; }
  .account-tabs :deep(.v-tab) { flex: 1 1 25% !important; width: 25% !important; max-width: 25% !important; min-width: 0 !important; padding-inline: 4px; font-size: 11px; }
  .account-tabs :deep(.v-btn__prepend) { display: none; }
}
@media (max-width: 360px) { .account-tabs :deep(.v-tab) { padding-inline: 2px; font-size: 10px; } }
</style>
