// frontend/src/react/views/ProbeView.tsx
import { LineChartOutlined, ReloadOutlined } from "@ant-design/icons";
import { Alert, Avatar, Button, Card, Col, ConfigProvider, Descriptions, Drawer, Empty, Flex, Form, Progress, Row, Segmented, Select, Space, Spin, Statistic, Table, Tag, Tooltip, Typography, theme } from "antd";
import type { TableColumnsType } from "antd";
import { lazy, Suspense, useCallback, useEffect, useState, type ReactNode } from "react";
import type { ProbeMetricPoint, ProbePayload, ProbePingSeries, ProbeServer, ProbeSeriesResponse, ProbeSettings, ProbeSystemSeries, ProbeTargetComparison } from "../../domain/probe";
import { browserProbeAccessToken } from "../../domain/probe-surface";
import { averageLatency, buildRegionOptions, buildSparkline, filterProbeServers, isExpired, isExpiring, latencyBucketLevels, percent, probeHealth, remainingDaysLabel, returnRouteBadges, serverRegionLabel, summarizeSevenDayTraffic, trafficHotspots, trafficTotal, trafficUsed, type ProbeStatusFilter } from "../../domain/probe-insights";
import { getPublicProbePayload, getPublicProbeSeries, getPublicProbeStreamUrl, getPublicProbeTargets, type ProbeRange } from "../../services/probe-public";
import { useAsyncScope } from "../hooks/useAsyncScope";

// The public bundle does not contain the authenticated settings/task module.
const AdministrationPanel = __OPEN_NODE_PUBLIC_PROBE__ ? null : lazy(() => import("../components/ProbeAdministrationPanel"));
export interface ProbeViewProps { publicOnly?: boolean }
const ranges: ProbeRange[] = ["1h", "6h", "24h"];
function bytes(value: number) {
  if (!Number.isFinite(value) || value <= 0) return "0 B";
  if (value < 1024) return `${Math.round(value)} B`;
  const units = ["KB", "MB", "GB", "TB"]; let scaled = value / 1024, index = 0;
  while (scaled >= 1024 && index < units.length - 1) { scaled /= 1024; index += 1; }
  return `${scaled.toFixed(scaled >= 10 ? 0 : 1)} ${units[index]}`;
}
const speed = (value: number) => `${bytes(value)}/s`;
const milliseconds = (value: number) => Number.isFinite(value) && value >= 0 ? `${value.toFixed(0)} ms` : "No sample";
const loss = (value: number) => `${value.toFixed(value >= 10 ? 0 : 1)}% loss`;
const percentage = (value: number) => `${value.toFixed(value >= 10 ? 0 : 1)}%`;
const serverName = (server: ProbeServer, index: number) => server.name || `Node ${index + 1}`;
const tone = (value: string) => value === "info" ? "blue" : value;
const optionalLatency = (value: number | null | undefined) => value == null ? "No sample" : milliseconds(value);
function renewal(server: ProbeServer) {
  const cycles = { month: "Month", quarter: "Quarter", half_year: "Half year", year: "Year" };
  return [server.expires_at ? `expires ${server.expires_at.slice(0, 10)}` : "", server.renewal_price != null ? `${server.renewal_price} ${server.renewal_currency ?? ""}`.trim() : "", server.renewal_cycle ? cycles[server.renewal_cycle] : ""].filter(Boolean).join(" / ") || "No renewal";
}
function isProbePayload(value: unknown): value is ProbePayload {
  if (!value || typeof value !== "object" || Array.isArray(value)) return false;
  const candidate = value as Partial<ProbePayload>;
  return candidate.license_required === false && typeof candidate.enabled === "boolean" && (candidate.servers === undefined || (Array.isArray(candidate.servers) && candidate.servers.every(server => server && typeof server === "object" && typeof server.online === "boolean")));
}
function safeImageUrl(value?: string) {
  if (!value) return undefined;
  try { const url = new URL(value); return ["http:", "https:"].includes(url.protocol) ? url.toString() : undefined; }
  catch { return undefined; }
}

export default function ProbeView({ publicOnly: requestedPublic = false }: ProbeViewProps) {
  const publicOnly = __OPEN_NODE_PUBLIC_PROBE__ || requestedPublic;
  const payloadScope = useAsyncScope();
  const targetScope = useAsyncScope();
  const [payload, setPayload] = useState<ProbePayload | null>(null);
  const [settingsOverride, setSettingsOverride] = useState<ProbeSettings | null>(null);
  const [accessToken, setAccessToken] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [streamActive, setStreamActive] = useState(false);
  const [statusFilter, setStatusFilter] = useState<ProbeStatusFilter>("all");
  const [regionFilter, setRegionFilter] = useState("all");
  const [selected, setSelected] = useState<{ index: number; name: string } | null>(null);
  const [comparisonRange, setComparisonRange] = useState<ProbeRange>("1h");
  const [comparisons, setComparisons] = useState<ProbeTargetComparison[]>([]);
  const [comparisonLoading, setComparisonLoading] = useState(false);
  const [comparisonError, setComparisonError] = useState("");
  const [comparisonGenerated, setComparisonGenerated] = useState("");
  const [systemDark, setSystemDark] = useState(false);
  const token = browserProbeAccessToken(publicOnly, accessToken);
  const settings: ProbeSettings = { enabled: true, ...payload, ...settingsOverride };
  const interval = Math.max(1, Math.min(60, settings.refresh_interval_sec || 5)) * 1000;
  const servers = payload?.servers ?? [];
  const regions = buildRegionOptions(servers);
  const visibleServers = filterProbeServers(servers, statusFilter, regionFilter);
  const showSystem = settings.show_resource_heatmap !== false;
  const showTraffic = settings.show_traffic_quota !== false;
  const showRenewal = settings.show_renewal_timeline === true;
  const showHealth = settings.show_health_score !== false;
  const showRoutes = settings.show_return_route === true;
  const online = servers.filter(server => server.online).length;
  const expired = servers.filter(server => isExpired(server)).length;
  const expiring = servers.filter(server => isExpiring(server)).length;
  const daily = summarizeSevenDayTraffic(servers);
  const hotspots = trafficHotspots(servers);
  const selectedServer = selected ? servers[selected.index] ?? null : null;

  const refreshPayload = useCallback(async () => {
    const request = payloadScope.begin(); setLoading(true); setError("");
    try {
      const result = await getPublicProbePayload(fetch, token);
      if (!isProbePayload(result)) throw new Error("Invalid public probe snapshot.");
      if (payloadScope.isCurrent(request)) setPayload(result);
    } catch (cause) {
      if (payloadScope.isCurrent(request)) setError(cause instanceof Error ? cause.message : "Probe request failed.");
    } finally { if (payloadScope.isCurrent(request)) setLoading(false); }
  }, [payloadScope, token]);
  const refreshTargets = useCallback(async () => {
    const request = targetScope.begin(); setComparisonLoading(true); setComparisonError("");
    try {
      const result = await getPublicProbeTargets(comparisonRange, fetch, token);
      if (targetScope.isCurrent(request)) {
        setComparisons(result.targets); setComparisonGenerated(result.generated_at ? new Date(result.generated_at * 1000).toLocaleString() : "");
      }
    } catch (cause) {
      if (targetScope.isCurrent(request)) { setComparisons([]); setComparisonGenerated(""); setComparisonError(cause instanceof Error ? cause.message : "Probe target comparison failed."); }
    } finally { if (targetScope.isCurrent(request)) setComparisonLoading(false); }
  }, [targetScope, comparisonRange, token]);
  useEffect(() => { void refreshPayload(); }, [refreshPayload]);
  useEffect(() => { void refreshTargets(); }, [refreshTargets]);
  useEffect(() => {
    let disposed = false;
    let timer: ReturnType<typeof setTimeout>;
    const tick = async () => {
      await Promise.allSettled([refreshPayload(), refreshTargets()]);
      if (!disposed) timer = setTimeout(() => void tick(), interval);
    };
    timer = setTimeout(() => void tick(), interval);
    return () => { disposed = true; clearTimeout(timer); };
  }, [interval, refreshPayload, refreshTargets]);
  const allowStream = publicOnly || !settings.require_access_token;
  useEffect(() => {
    if (!allowStream || typeof WebSocket === "undefined") { setStreamActive(false); return; }
    let disposed = false;
    let socket: WebSocket | null = null;
    let reconnect: ReturnType<typeof setTimeout> | undefined;
    const open = () => {
      if (disposed) return;
      try {
        socket = new WebSocket(getPublicProbeStreamUrl());
        socket.onopen = () => { if (!disposed) setStreamActive(true); };
        socket.onmessage = event => {
          if (disposed) return;
          try {
            const snapshot: unknown = JSON.parse(String(event.data));
            if (isProbePayload(snapshot)) { payloadScope.invalidate(); setPayload(snapshot); setError(""); setLoading(false); }
          } catch { /* A later validated snapshot replaces malformed stream frames. */ }
        };
        socket.onerror = () => { if (!disposed) setStreamActive(false); };
        socket.onclose = () => { socket = null; if (!disposed) { setStreamActive(false); reconnect = setTimeout(open, 2000); } };
      } catch { if (!disposed) { setStreamActive(false); reconnect = setTimeout(open, 2000); } }
    };
    open();
    return () => {
      disposed = true; clearTimeout(reconnect);
      if (socket) { socket.onopen = null; socket.onmessage = null; socket.onerror = null; socket.onclose = null; socket.close(); }
    };
  }, [allowStream, publicOnly, payloadScope]);
  useEffect(() => {
    if (typeof window.matchMedia !== "function") return;
    const media = window.matchMedia("(prefers-color-scheme: dark)");
    const update = () => setSystemDark(media.matches); update(); media.addEventListener("change", update);
    return () => media.removeEventListener("change", update);
  }, []);
  useEffect(() => {
    if (regionFilter !== "all" && !regions.some(region => region.code === regionFilter)) setRegionFilter("all");
    if (selected && (!selectedServer || serverName(selectedServer, selected.index) !== selected.name)) setSelected(null);
  }, [payload, regionFilter, selected, selectedServer]);
  const applySettings = useCallback((value: ProbeSettings) => { setSettingsOverride(value); }, []);
  const applyAccessToken = useCallback((value: string, nextSettings: ProbeSettings) => { setAccessToken(value); setSettingsOverride(nextSettings); }, []);
  const refreshAll = useCallback(() => { void refreshPayload(); void refreshTargets(); }, [refreshPayload, refreshTargets]);
  const openDetail = (server: ProbeServer) => { const index = servers.indexOf(server); if (index >= 0) setSelected({ index, name: serverName(server, index) }); };
  const columns: TableColumnsType<ProbeServer> = [
    { title: "Name", key: "name", width: 220, render: (_, server) => <>
      <Flex gap="small" align="center"><Typography.Text strong>{serverName(server, servers.indexOf(server))}</Typography.Text><Button icon={<LineChartOutlined aria-hidden />} size="small" aria-label={`Open probe details for ${serverName(server, servers.indexOf(server))}`} title="Open probe details" onClick={() => openDetail(server)} /></Flex>
      <div><Typography.Text type="secondary">{serverRegionLabel(server)}</Typography.Text></div><div><Typography.Text type="secondary">{server.provider_name ?? "No provider"}</Typography.Text></div>
    </> },
    { title: "Status", key: "status", width: 160, render: (_, server) => { const health = probeHealth(server); return <Space orientation="vertical" size={4}>
      <Tag color={server.online ? "success" : "error"}>{server.online ? "Online" : "Offline"}</Tag>
      <Typography.Text type="secondary">{server.telecom_paid_peer == null ? "Peer unknown" : server.telecom_paid_peer ? "Paid peer" : "Standard peer"}</Typography.Text>
      {showHealth && <Tooltip title={health.issues.length ? health.issues.join(", ") : "No public health issues"}><Tag color={tone(health.tone)}>{health.score} {health.label}</Tag></Tooltip>}
    </Space>; } },
    ...(showSystem ? [{ title: "System", key: "system", width: 220, render: (_: unknown, server: ProbeServer) => <>
      <Typography.Text>{server.cpu_pct != null ? `${server.cpu_pct.toFixed(1)}% CPU` : "CPU n/a"}, {server.mem_used != null && server.mem_total ? `${((server.mem_used / server.mem_total) * 100).toFixed(0)}% mem` : "mem n/a"}</Typography.Text>
      <div><Typography.Text type="secondary">{server.os || "Unknown OS"} / {server.loadavg || "No loadavg"}</Typography.Text></div>
    </> }] : []),
    { title: "Latency", key: "latency", width: 185, render: (_, server) => <>
      <Typography.Text>{!(server.ping?.length) ? "No probe" : averageLatency(server) == null ? "probe failed" : `${averageLatency(server)} ms avg`}</Typography.Text>
      <div className="probe-latency-bars">{latencyBucketLevels(server).map((bucket, index) => <span key={index} className={`is-${bucket.level}`} title={bucket.level === "none" ? "No sample" : `${bucket.ms.toFixed(0)} ms, ${bucket.loss.toFixed(1)}% loss`} />)}</div>
    </> },
    ...(showTraffic ? [{ title: "Traffic", key: "traffic", width: 220, render: (_: unknown, server: ProbeServer) => <>
      <Typography.Text>{!trafficUsed(server) && !server.traffic_limit && server.traffic_used === undefined ? "No traffic" : `${bytes(trafficUsed(server))}${server.traffic_limit ? ` / ${bytes(server.traffic_limit)}` : ""}`}</Typography.Text>
      {Boolean(server.traffic_limit) && <Progress size="small" showInfo={false} percent={percent(trafficUsed(server), server.traffic_limit)} />}
      {settings.show_traffic_7d === true && <div><Typography.Text type="secondary">{server.daily_traffic?.length ? `7d ${bytes(trafficTotal(server.daily_traffic))}` : "No 7d traffic"}</Typography.Text></div>}
      {!showRenewal && <div><Typography.Text type="secondary">{renewal(server)}</Typography.Text></div>}
    </> }] : []),
    ...(showRoutes ? [{ title: "Routes", key: "routes", width: 220, render: (_: unknown, server: ProbeServer) => <RouteBadges server={server} /> }] : []),
    ...(showRenewal ? [{ title: "Renewal", key: "renewal", width: 220, render: (_: unknown, server: ProbeServer) => <>
      <Tag color={isExpired(server) ? "error" : isExpiring(server) ? "warning" : "default"}>{remainingDaysLabel(server.expires_at) || "No expiry"}</Tag>
      <div>{renewal(server)}</div><Typography.Text type="secondary">CNY {server.renewal_price_cny ?? "n/a"}</Typography.Text>
    </> }] : []),
    { title: "Up", key: "up", width: 120, render: (_, server) => speed(server.upload_speed ?? 0) },
    { title: "Down", key: "down", width: 120, render: (_, server) => speed(server.download_speed ?? 0) },
  ];
  const dark = settings.appearance?.color_mode === "dark" || (settings.appearance?.color_mode === "system" && systemDark);
  const endpointNote = streamActive ? "Live stream connected" : !publicOnly && settings.require_access_token ? "Worker token required" : payload?.enabled ? "Probe endpoint enabled" : "Probe endpoint disabled";
  return <ConfigProvider theme={{ algorithm: dark ? theme.darkAlgorithm : theme.defaultAlgorithm }}><ProbeSurface publicOnly={publicOnly} dark={dark}>
    <Flex justify="space-between" align="start" gap="middle"><Flex align="start" gap="small" style={{ flex: 1, minWidth: 0 }}><Avatar src={safeImageUrl(settings.logo)} shape="square" size={48} style={{ flexShrink: 0 }}>ON</Avatar><div style={{ minWidth: 0, overflowWrap: "anywhere" }}><Typography.Text type="secondary">Public probe</Typography.Text><Typography.Title level={1} style={{ margin: "8px 0" }}>{settings.title ?? "Open Node Probe"}</Typography.Title><Typography.Paragraph type="secondary">{settings.description ?? "MMWX probe-compatible node status without license gates."}</Typography.Paragraph></div></Flex><Button style={{ flexShrink: 0 }} icon={<ReloadOutlined aria-hidden />} aria-label="Refresh probe status" loading={loading} onClick={refreshAll} /></Flex>
    {error && <Alert type="error" showIcon title={!publicOnly && settings.require_access_token && !token ? "Worker token required." : error} />}
    <section aria-label="Probe status"><Row gutter={[16, 16]}>
      <Col xs={24} sm={12} lg={8}><Card><Statistic title="Public Nodes" value={servers.length} /><Typography.Text type="secondary">{endpointNote}</Typography.Text></Card></Col>
      <Col xs={24} sm={12} lg={8}><Card><Statistic title="Online" value={online} /><Typography.Text type="secondary">{servers.length - online} offline</Typography.Text></Card></Col>
      <Col xs={24} sm={24} lg={8}><Card><Statistic title="Throughput" value={`${speed(servers.reduce((total, server) => total + (server.upload_speed ?? 0), 0))} / ${speed(servers.reduce((total, server) => total + (server.download_speed ?? 0), 0))}`} /><Typography.Text type="secondary">Upload / download</Typography.Text></Card></Col>
    </Row></section>
    {servers.length > 0 && <section aria-label="Probe insights"><Row gutter={[16, 16]}>
      {settings.show_globe && regions.length > 0 && <Col xs={24} lg={8}><Card title="Regions" extra={`${regions.length} public groups`}><Space orientation="vertical" style={{ width: "100%" }}>{regions.map(region => <div key={region.code}><Flex justify="space-between" align="center" gap="small"><Button type={regionFilter === region.code ? "primary" : "link"} onClick={() => setRegionFilter(region.code)}>{region.label}</Button><Typography.Text>{region.online}/{region.total}</Typography.Text></Flex><Progress percent={(region.total / servers.length) * 100} showInfo={false} size="small" /></div>)}</Space></Card></Col>}
      {settings.show_daily_trend && daily.length > 0 && <Col xs={24} lg={8}><Card title="Daily traffic" extra={`${bytes(daily.at(-1)?.total ?? 0)} today`}><DailyTrafficChart days={daily} /></Card></Col>}
      {settings.show_traffic_hotspots && hotspots.length > 0 && <Col xs={24} lg={8}><Card title="Traffic hotspots" extra="Top live throughput"><Space orientation="vertical" style={{ width: "100%" }}>{hotspots.map(row => <div key={row.index}><Flex gap="small" justify="space-between"><Typography.Text>{row.name}</Typography.Text><Typography.Text>{speed(row.speed)}</Typography.Text></Flex><Progress percent={row.share} showInfo={false} size="small" /></div>)}</Space></Card></Col>}
    </Row></section>}
    <Card role="region" aria-label="Target comparison" className="probe-target-compare" title="Target comparison" extra={<Space wrap><Segmented aria-label="Target comparison range" value={comparisonRange} options={ranges} onChange={setComparisonRange} /><Button icon={<ReloadOutlined aria-hidden />} aria-label="Refresh target comparison" loading={comparisonLoading} onClick={() => void refreshTargets()} /></Space>}>
      <Space orientation="vertical" size="middle" style={{ width: "100%" }}>
        {comparisonError && <Alert type="error" showIcon title={comparisonError} />}
        {comparisonLoading && !comparisons.length && <Spin aria-label="Loading target comparison" />}
        {!comparisonLoading && !comparisonError && !comparisons.length && <Empty description="No target comparison samples." image={Empty.PRESENTED_IMAGE_SIMPLE} />}
        {[...comparisons].sort((left, right) => right.average_loss_pct - left.average_loss_pct || (right.average_ms ?? -1) - (left.average_ms ?? -1) || left.label.localeCompare(right.label)).map(target => <Card key={target.key} type="inner" title={target.label} extra={`${target.healthy_count}/${target.server_count} healthy / ${loss(target.average_loss_pct)}`}>
          <Sparkline values={comparisonValues(target)} height={64} label={`${target.label} average latency`} />
          <Descriptions size="small" column={{ xs: 1, sm: 3 }} items={[
            { key: "average", label: "average", children: optionalLatency(target.average_ms) }, { key: "best", label: "best", children: optionalLatency(target.best_ms) }, { key: "worst", label: "worst", children: optionalLatency(target.worst_ms) },
          ]} />
          <Space wrap>{target.servers.slice(0, 5).map(server => <Tag key={server.server_index} color={server.current_ms >= 0 ? "success" : "error"}>{server.server_name ?? `Node ${server.server_index + 1}`} {server.current_ms >= 0 ? milliseconds(server.current_ms) : "failed"}</Tag>)}</Space>
        </Card>)}
        {comparisonGenerated && <Typography.Text type="secondary">Updated {comparisonGenerated}</Typography.Text>}
      </Space>
    </Card>
    {!publicOnly && AdministrationPanel && <Suspense fallback={<Spin aria-label="Loading probe administration" />}><AdministrationPanel accessToken={accessToken} onSettings={applySettings} onAccessToken={applyAccessToken} onRefresh={refreshAll} /></Suspense>}
    <Card title="Probe nodes" extra={<Typography.Text type="secondary">Public read-only view</Typography.Text>}>
      {servers.length > 0 && <Flex wrap gap="middle" align="center" className="form-alert">
        <Segmented className="probe-status-toggle" aria-label="Node status filter" value={statusFilter} onChange={value => setStatusFilter(value as ProbeStatusFilter)} options={[
          { label: `All ${servers.length}`, value: "all" }, { label: `Online ${online}`, value: "online" }, { label: `Offline ${servers.length - online}`, value: "offline" }, { label: `Renewal ${expired + expiring}`, value: "renewal" }, { label: `Expired ${expired}`, value: "expired" },
        ]} />
        <Select aria-label="Region filter" className="probe-region-select" style={{ minWidth: 190 }} value={regionFilter} options={[{ label: "All regions", value: "all" }, ...regions.map(region => ({ label: `${region.label} (${region.online}/${region.total})`, value: region.code }))]} onChange={setRegionFilter} />
        <Typography.Text type="secondary">{visibleServers.length} / {servers.length} nodes</Typography.Text>
      </Flex>}
      <Table className="server-table" rowKey={server => `${serverName(server, servers.indexOf(server))}-${servers.indexOf(server)}`} dataSource={visibleServers} columns={columns} loading={loading && !servers.length} pagination={false} scroll={{ x: "max-content" }} locale={{ emptyText: servers.length ? "No nodes match the current filters." : "No public probe nodes yet." }} />
    </Card>
    <Drawer open={selected !== null} title={<Typography.Title level={3} style={{ margin: 0 }}>{selected?.name ?? "Node"}</Typography.Title>} className="probe-detail-drawer" size={560} onClose={() => setSelected(null)} destroyOnHidden>
      {selected && selectedServer && <ProbeDetails key={selected.index} server={selectedServer} serverIndex={selected.index} showRoutes={showRoutes} accessToken={token} />}
    </Drawer>
  </ProbeSurface></ConfigProvider>;
}

function ProbeSurface({ publicOnly, dark, children }: { publicOnly: boolean; dark: boolean; children: ReactNode }) {
  const { token } = theme.useToken();
  return <div className={`page-shell probe-page${publicOnly ? " public-probe-surface" : ""}`} style={{ background: token.colorBgLayout, color: token.colorText, colorScheme: dark ? "dark" : "light" }}>{children}</div>;
}

function Sparkline({ values, height = 96, label, color = "#1677ff" }: { values: (number | null | undefined)[]; height?: number; label: string; color?: string }) {
  const chart = buildSparkline(values, 320, height, 6);
  return <svg className="probe-sparkline" role="img" aria-label={label} preserveAspectRatio="none" viewBox={`0 0 320 ${height}`} style={{ height }}>
    {!chart.empty && <><polygon points={chart.areaPoints} fill={color} fillOpacity={0.12} /><polyline points={chart.points} stroke={color} strokeWidth={2} fill="none" /></>}
  </svg>;
}
function TrendCard({ label, values, format, color }: { label: string; values: (number | null | undefined)[]; format: (value: number) => string; color: string }) {
  const chart = buildSparkline(values);
  return <Card size="small" title={label} extra={chart.latest === null ? "No sample" : format(chart.latest)}><Sparkline label={`${label} trend`} values={values} color={color} /><Typography.Text type="secondary">{chart.empty ? "No samples" : `${format(chart.min)} - ${format(chart.max)}`}</Typography.Text></Card>;
}
function RouteBadges({ server }: { server: ProbeServer }) {
  return <Space wrap>{returnRouteBadges(server).map(route => <Tooltip key={route.carrier} title={`${route.carrierLabel} ${route.routeType}${route.region ? ` - ${route.region}` : ""}${route.testedAt ? `, tested ${route.testedAt}` : ""}`}><Tag color={route.missing ? "default" : route.premium ? "success" : "blue"}>{route.carrierLabel} {route.routeType}</Tag></Tooltip>)}</Space>;
}
function DailyTrafficChart({ days }: { days: ReturnType<typeof summarizeSevenDayTraffic> }) {
  const maximum = Math.max(1, ...days.map(day => day.total));
  return <><svg className="probe-daily-chart" viewBox="0 0 350 160" role="img" aria-label="Daily upload and download traffic">{days.map((day, index) => {
    const downHeight = (day.downlink / maximum) * 110, upHeight = (day.uplink / maximum) * 110;
    return <g key={day.date}><title>{day.date}: {bytes(day.total)} total</title><rect x={index * (350 / days.length) + 8} y={125 - downHeight} width={18} height={downHeight} fill="#1677ff" /><rect x={index * (350 / days.length) + 28} y={125 - upHeight} width={18} height={upHeight} fill="#fa8c16" /><text x={index * (350 / days.length) + 24} y={148} textAnchor="middle" fill="currentColor" fontSize={10}>{day.date.slice(5)}</text></g>;
  })}</svg><Space><Tag color="blue">Download</Tag><Tag color="orange">Upload</Tag></Space></>;
}
function comparisonValues(target: ProbeTargetComparison) {
  return Array.from({ length: Math.max(0, ...target.servers.map(server => server.buckets.length)) }, (_, index) => {
    const values = target.servers.map(server => server.buckets[index]?.ms).filter((value): value is number => typeof value === "number" && value >= 0);
    return values.length ? values.reduce((total, value) => total + value, 0) / values.length : null;
  });
}
function ProbeDetails({ server, serverIndex, showRoutes, accessToken }: { server: ProbeServer; serverIndex: number; showRoutes: boolean; accessToken?: string }) {
  const scope = useAsyncScope();
  const [range, setRange] = useState<ProbeRange>("1h");
  const [metric, setMetric] = useState<"ping" | "system">("ping");
  const [series, setSeries] = useState<ProbeSeriesResponse | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  useEffect(() => {
    const request = scope.begin(); setLoading(true); setError(""); setSeries(null);
    void getPublicProbeSeries(serverIndex, { range, metric, all: metric === "ping" }, fetch, accessToken).then(result => {
      if (scope.isCurrent(request)) setSeries(result);
    }).catch(cause => { if (scope.isCurrent(request)) setError(cause instanceof Error ? cause.message : "Probe series request failed."); })
      .finally(() => { if (scope.isCurrent(request)) setLoading(false); });
    return () => scope.invalidate();
  }, [scope, serverIndex, range, metric, accessToken]);
  const ping = series?.series && "buckets" in series.series ? series.series as ProbePingSeries : null;
  const system = series?.series && "cpu_pct" in series.series ? series.series as ProbeSystemSeries : null;
  const values = (points?: ProbeMetricPoint[]) => points?.map(point => point.value) ?? [];
  const totals = new Map((system?.mem_total ?? []).map(point => [point.t, point.value]));
  return <Space className="probe-trend-grid" orientation="vertical" size="large" style={{ width: "100%" }}>
    <div><Typography.Text type="secondary">Probe details</Typography.Text><Typography.Paragraph>{serverRegionLabel(server)}</Typography.Paragraph></div>
    <Flex gap="small" wrap><Segmented aria-label="Probe metric" value={metric} onChange={setMetric} options={[{ label: "Ping", value: "ping" }, { label: "System", value: "system" }]} /><Segmented aria-label="Probe history range" value={range} options={ranges} onChange={setRange} /></Flex>
    {error && <Alert type="error" showIcon title={error} />}{loading && <Spin aria-label="Loading probe history" />}
    {!loading && metric === "ping" && <>
      {ping && <><TrendCard label="Average latency" values={ping.buckets.map(bucket => bucket.ms)} format={milliseconds} color="#1677ff" /><TrendCard label="Packet loss" values={ping.buckets.map(bucket => bucket.loss)} format={loss} color="#ff4d4f" /></>}
      <Typography.Title level={5}>Targets</Typography.Title>
      {!series?.all_series?.length && <Empty description="No target series." image={Empty.PRESENTED_IMAGE_SIMPLE} />}
      {series?.all_series?.map(target => <Card size="small" key={target.key ?? target.label} title={target.label} extra={`${target.current_ms >= 0 ? milliseconds(target.current_ms) : "failed"} / ${loss(target.loss_pct)}`}><Sparkline values={target.buckets.map(bucket => bucket.ms)} label={`${target.label} latency trend`} height={54} /></Card>)}
    </>}
    {!loading && metric === "system" && (system ? <>
      <TrendCard label="CPU" values={values(system.cpu_pct)} format={percentage} color="#52c41a" />
      <TrendCard label="Memory" values={system.mem_used.map(point => percent(point.value, totals.get(point.t)))} format={percentage} color="#722ed1" />
      <TrendCard label="Upload" values={values(system.upload_speed)} format={speed} color="#fa8c16" />
      <TrendCard label="Download" values={values(system.download_speed)} format={speed} color="#1677ff" />
    </> : <Empty description="No system samples." image={Empty.PRESENTED_IMAGE_SIMPLE} />)}
    {showRoutes && <><Typography.Title level={5}>Return routes</Typography.Title><RouteBadges server={server} /></>}
    {series?.generated_at && <Typography.Text type="secondary">Updated {new Date(series.generated_at * 1000).toLocaleString()}</Typography.Text>}
  </Space>;
}

// frontend/src/views/ProbeView.vue
<script setup lang="ts">
import { computed, onMounted, onUnmounted, reactive, ref } from "vue";

import type { ProbePayload, ProbeServer, ProbeSettingsUpdate } from "../domain/probe";
import type { ProbeHealth, ProbeLatencyBucket, ProbeStatusFilter } from "../domain/probe-insights";
import {
  buildRegionOptions,
  filterProbeServers,
  isExpired,
  isExpiring,
  latencyBucketLevels,
  percent,
  probeHealth,
  remainingDaysLabel,
  serverRegionLabel,
  summarizeSevenDayTraffic,
  trafficHotspots,
  trafficTotal,
  trafficUsed,
} from "../domain/probe-insights";
import {
  getPublicProbePayload,
  getPublicProbeStreamUrl,
  updatePublicProbeSettings,
} from "../services/probe";

const payload = ref<ProbePayload | null>(null);
const loading = ref(false);
const savingSettings = ref(false);
const errorMessage = ref("");
const successMessage = ref("");
const streamActive = ref(false);
const statusFilter = ref<ProbeStatusFilter>("all");
const regionFilter = ref("all");
let probeStream: WebSocket | undefined;

const settingsForm = reactive({
  enabled: true,
  title: "Open Node Probe",
  description: "MMWX probe-compatible node status without license gates.",
  logo: "",
  refresh_interval_sec: 5,
  theme: "open-node",
  color_mode: "light" as "light" | "dark" | "system",
  revision: "open-node",
  show_globe: false,
  show_resource_heatmap: true,
  show_traffic_quota: true,
  show_daily_trend: false,
  show_traffic_hotspots: false,
  show_traffic_7d: false,
  show_renewal_timeline: false,
  show_health_score: true,
});

const servers = computed(() => payload.value?.servers ?? []);
const probeDescription = computed(
  () => payload.value?.description ?? "MMWX probe-compatible node status without license gates.",
);
const showSystemColumn = computed(() => payload.value?.show_resource_heatmap !== false);
const showTrafficColumn = computed(() => payload.value?.show_traffic_quota !== false);
const showRenewalColumn = computed(() => payload.value?.show_renewal_timeline === true);
const showHealthScore = computed(() => payload.value?.show_health_score !== false);
const showRegionOverview = computed(() => payload.value?.show_globe === true && regions.value.length > 0);
const showDailyTrend = computed(() => payload.value?.show_daily_trend === true);
const showTrafficHotspots = computed(() => payload.value?.show_traffic_hotspots === true);
const showSevenDayTraffic = computed(() => payload.value?.show_traffic_7d === true);
const onlineCount = computed(() => servers.value.filter((server) => server.online).length);
const expiringCount = computed(() => servers.value.filter((server) => isExpiring(server)).length);
const expiredCount = computed(() => servers.value.filter((server) => isExpired(server)).length);
const totalUpload = computed(() =>
  servers.value.reduce((sum, server) => sum + (server.upload_speed ?? 0), 0),
);
const totalDownload = computed(() =>
  servers.value.reduce((sum, server) => sum + (server.download_speed ?? 0), 0),
);
const metrics = computed(() => [
  {
    label: "Public Nodes",
    value: servers.value.length.toString(),
    note: probeEndpointNote(),
    icon: "mdi-access-point-network",
    color: "primary",
  },
  {
    label: "Online",
    value: onlineCount.value.toString(),
    note: `${servers.value.length - onlineCount.value} offline`,
    icon: "mdi-lan-check",
    color: "success",
  },
  {
    label: "Throughput",
    value: `${formatBytesPerSecond(totalUpload.value)} / ${formatBytesPerSecond(totalDownload.value)}`,
    note: "Upload / download",
    icon: "mdi-chart-timeline-variant",
    color: "info",
  },
]);
const regions = computed(() => buildRegionOptions(servers.value));
const visibleServers = computed(() =>
  filterProbeServers(servers.value, statusFilter.value, regionFilter.value),
);
const filterCountLabel = computed(() => `${visibleServers.value.length} / ${servers.value.length} nodes`);
const statusFilterOptions = computed<
  Array<{ count: number; icon: string; title: string; value: ProbeStatusFilter }>
>(() => [
  { title: "All", value: "all", count: servers.value.length, icon: "mdi-server-network" },
  { title: "Online", value: "online", count: onlineCount.value, icon: "mdi-lan-check" },
  {
    title: "Offline",
    value: "offline",
    count: servers.value.length - onlineCount.value,
    icon: "mdi-lan-disconnect",
  },
  {
    title: "Renewal",
    value: "renewal",
    count: expiringCount.value + expiredCount.value,
    icon: "mdi-calendar-clock",
  },
  { title: "Expired", value: "expired", count: expiredCount.value, icon: "mdi-calendar-remove" },
]);
const regionSelectOptions = computed(() => [
  { title: "All regions", value: "all" },
  ...regions.value.map((region) => ({
    title: `${region.label} (${region.online}/${region.total})`,
    value: region.code,
  })),
]);
const dailyTraffic = computed(() => summarizeSevenDayTraffic(servers.value));
const dailyTrafficPeak = computed(() => Math.max(1, ...dailyTraffic.value.map((day) => day.total)));
const currentDailyTraffic = computed(() => dailyTraffic.value.at(-1)?.total ?? 0);
const hotspots = computed(() => trafficHotspots(servers.value));
const showInsightGrid = computed(
  () =>
    servers.value.length > 0 &&
    ((showRegionOverview.value && regions.value.length > 0) ||
      (showDailyTrend.value && dailyTraffic.value.length > 0) ||
      (showTrafficHotspots.value && hotspots.value.length > 0)),
);
const colorModeOptions = [
  { title: "Light", value: "light" },
  { title: "Dark", value: "dark" },
  { title: "System", value: "system" },
];

onMounted(() => {
  void refreshProbe();
  openProbeStream();
});

onUnmounted(() => {
  probeStream?.close();
  probeStream = undefined;
});

async function refreshProbe() {
  loading.value = true;
  errorMessage.value = "";
  try {
    acceptProbe(await getPublicProbePayload());
  } catch (error) {
    errorMessage.value = error instanceof Error ? error.message : "Probe request failed.";
  } finally {
    loading.value = false;
  }
}

function acceptProbe(nextPayload: ProbePayload) {
  payload.value = nextPayload;
  errorMessage.value = "";
  syncSettingsForm(nextPayload);
  syncFilters(nextPayload.servers ?? []);
}

function probeEndpointNote() {
  if (streamActive.value) {
    return "Live stream connected";
  }
  return payload.value?.enabled ? "Probe endpoint enabled" : "Probe endpoint disabled";
}

function openProbeStream() {
  if (typeof WebSocket === "undefined") {
    return;
  }
  try {
    probeStream = new WebSocket(getPublicProbeStreamUrl(window.location));
    probeStream.onopen = () => {
      streamActive.value = true;
    };
    probeStream.onmessage = (event) => {
      try {
        acceptProbe(JSON.parse(event.data as string) as ProbePayload);
      } catch {
        // Ignore malformed stream frames; the next snapshot replaces the page state.
      }
    };
    probeStream.onerror = () => {
      streamActive.value = false;
    };
    probeStream.onclose = () => {
      streamActive.value = false;
      probeStream = undefined;
    };
  } catch {
    streamActive.value = false;
  }
}

async function saveProbeSettings() {
  savingSettings.value = true;
  errorMessage.value = "";
  successMessage.value = "";
  try {
    await updatePublicProbeSettings(settingsPayload());
    await refreshProbe();
    successMessage.value = "Probe settings saved.";
  } catch (error) {
    errorMessage.value = error instanceof Error ? error.message : "Probe settings failed.";
  } finally {
    savingSettings.value = false;
  }
}

function syncSettingsForm(nextPayload: ProbePayload) {
  settingsForm.enabled = nextPayload.enabled;
  settingsForm.title = nextPayload.title ?? "Open Node Probe";
  settingsForm.description =
    nextPayload.description ?? "MMWX probe-compatible node status without license gates.";
  settingsForm.logo = nextPayload.logo ?? "";
  settingsForm.refresh_interval_sec = nextPayload.refresh_interval_sec ?? 5;
  settingsForm.theme = nextPayload.appearance?.theme ?? "open-node";
  settingsForm.color_mode = nextPayload.appearance?.color_mode ?? "light";
  settingsForm.revision = nextPayload.appearance?.revision ?? "open-node";
  settingsForm.show_globe = nextPayload.show_globe === true;
  settingsForm.show_resource_heatmap = nextPayload.show_resource_heatmap !== false;
  settingsForm.show_traffic_quota = nextPayload.show_traffic_quota !== false;
  settingsForm.show_daily_trend = nextPayload.show_daily_trend === true;
  settingsForm.show_traffic_hotspots = nextPayload.show_traffic_hotspots === true;
  settingsForm.show_traffic_7d = nextPayload.show_traffic_7d === true;
  settingsForm.show_renewal_timeline = nextPayload.show_renewal_timeline === true;
  settingsForm.show_health_score = nextPayload.show_health_score !== false;
}

function settingsPayload(): ProbeSettingsUpdate {
  return {
    enabled: settingsForm.enabled,
    title: settingsForm.title,
    description: settingsForm.description,
    logo: settingsForm.logo,
    refresh_interval_sec: settingsForm.refresh_interval_sec,
    show_globe: settingsForm.show_globe,
    show_resource_heatmap: settingsForm.show_resource_heatmap,
    show_traffic_quota: settingsForm.show_traffic_quota,
    show_daily_trend: settingsForm.show_daily_trend,
    show_traffic_hotspots: settingsForm.show_traffic_hotspots,
    show_traffic_7d: settingsForm.show_traffic_7d,
    show_renewal_timeline: settingsForm.show_renewal_timeline,
    show_health_score: settingsForm.show_health_score,
    appearance: {
      theme: settingsForm.theme,
      color_mode: settingsForm.color_mode,
      revision: settingsForm.revision,
    },
  };
}

function syncFilters(nextServers: ProbeServer[]) {
  if (
    regionFilter.value !== "all" &&
    !buildRegionOptions(nextServers).some((region) => region.code === regionFilter.value)
  ) {
    regionFilter.value = "all";
  }
}

function displayName(server: ProbeServer, index: number) {
  return server.name || `Node ${index + 1}`;
}

function statusColor(server: ProbeServer) {
  return server.online ? "success" : "error";
}

function statusIcon(server: ProbeServer) {
  return server.online ? "mdi-check-network-outline" : "mdi-network-off-outline";
}

function statusLabel(server: ProbeServer) {
  return server.online ? "Online" : "Offline";
}

function healthFor(server: ProbeServer): ProbeHealth {
  return probeHealth(server);
}

function healthHint(server: ProbeServer) {
  const health = healthFor(server);
  return health.issues.length ? health.issues.join(", ") : "No public health issues";
}

function systemSummary(server: ProbeServer) {
  const cpu = server.cpu_pct !== undefined && server.cpu_pct !== null
    ? `${server.cpu_pct.toFixed(1)}% CPU`
    : "CPU n/a";
  const memory =
    server.mem_used !== undefined && server.mem_used !== null && server.mem_total
      ? `${formatPercent(server.mem_used, server.mem_total)} mem`
      : "mem n/a";
  return `${cpu}, ${memory}`;
}

function latencySummary(server: ProbeServer) {
  const ping = server.ping ?? [];
  if (ping.length === 0) {
    return "No probe";
  }
  const live = ping.filter((series) => series.current_ms >= 0);
  if (live.length === 0) {
    return "probe failed";
  }
  const average = live.reduce((sum, series) => sum + series.current_ms, 0) / live.length;
  return `${average.toFixed(0)} ms avg`;
}

function trafficSummary(server: ProbeServer) {
  const used = trafficUsed(server);
  if (used === 0 && !server.traffic_limit && server.traffic_used === undefined) {
    return "No traffic";
  }
  if (server.traffic_limit) {
    return `${formatBytes(used)} / ${formatBytes(server.traffic_limit)}`;
  }
  return formatBytes(used);
}

function regionSummary(server: ProbeServer) {
  return serverRegionLabel(server);
}

function providerSummary(server: ProbeServer) {
  return server.provider_name ?? "No provider";
}

function renewalSummary(server: ProbeServer) {
  const parts: string[] = [];
  if (server.expires_at) {
    parts.push(`expires ${server.expires_at.slice(0, 10)}`);
  }
  if (server.renewal_price !== null && server.renewal_price !== undefined) {
    parts.push(`${server.renewal_price} ${server.renewal_currency ?? ""}`.trim());
  }
  if (server.renewal_cycle) {
    parts.push(renewalCycleLabel(server.renewal_cycle));
  }
  return parts.join(" / ") || "No renewal";
}

function renewalCycleLabel(cycle: NonNullable<ProbeServer["renewal_cycle"]>) {
  const labels: Record<NonNullable<ProbeServer["renewal_cycle"]>, string> = {
    month: "Month",
    quarter: "Quarter",
    half_year: "Half year",
    year: "Year",
  };
  return labels[cycle];
}

function peerSummary(server: ProbeServer) {
  if (server.telecom_paid_peer === null || server.telecom_paid_peer === undefined) {
    return "Peer unknown";
  }
  return server.telecom_paid_peer ? "Paid peer" : "Standard peer";
}

function rowClass(server: ProbeServer) {
  return {
    "is-filtered-offline": !server.online,
    "is-expired": isExpired(server),
    "is-expiring": isExpiring(server),
  };
}

function selectRegion(code: string) {
  regionFilter.value = code;
}

function regionShare(total: number) {
  const share = servers.value.length > 0 ? (total / servers.value.length) * 100 : 0;
  return `${Math.max(4, share)}%`;
}

function dailyBarHeight(value: number) {
  if (value <= 0) {
    return "0%";
  }
  return `${Math.max(6, (value / dailyTrafficPeak.value) * 100)}%`;
}

function dailyBarTitle(day: { date: string; uplink: number; downlink: number; total: number }) {
  return `${day.date}: ${formatBytes(day.total)} total`;
}

function latencyBuckets(server: ProbeServer): ProbeLatencyBucket[] {
  return latencyBucketLevels(server);
}

function latencyBucketTitle(bucket: ProbeLatencyBucket) {
  if (bucket.level === "none") {
    return "No sample";
  }
  return `${bucket.ms.toFixed(0)} ms, ${bucket.loss.toFixed(1)}% loss`;
}

function quotaWidth(server: ProbeServer) {
  return `${percent(trafficUsed(server), server.traffic_limit)}%`;
}

function sevenDayTrafficSummary(server: ProbeServer) {
  const rows = server.daily_traffic ?? [];
  return rows.length ? `7d ${formatBytes(trafficTotal(rows))}` : "No 7d traffic";
}

function renewalTone(server: ProbeServer) {
  if (isExpired(server)) {
    return "error";
  }
  if (isExpiring(server)) {
    return "warning";
  }
  return "default";
}

function renewalCountdown(server: ProbeServer) {
  return remainingDaysLabel(server.expires_at) || "No expiry";
}

function formatPercent(used: number, total: number) {
  return `${((used / total) * 100).toFixed(0)}%`;
}

function formatBytesPerSecond(value: number) {
  return `${formatBytes(value)}/s`;
}

function formatBytes(value: number) {
  if (value < 1024) {
    return `${value} B`;
  }
  const units = ["KB", "MB", "GB", "TB"];
  let scaled = value / 1024;
  let unitIndex = 0;
  while (scaled >= 1024 && unitIndex < units.length - 1) {
    scaled /= 1024;
    unitIndex += 1;
  }
  return `${scaled.toFixed(scaled >= 10 ? 0 : 1)} ${units[unitIndex]}`;
}
</script>

<template>
  <div class="page-shell">
    <section class="page-heading">
      <div class="probe-title-row">
        <v-avatar v-if="payload?.logo" class="probe-logo" rounded="lg" size="52">
          <v-img :src="payload.logo" alt="" cover />
        </v-avatar>
        <div>
          <div class="eyebrow">Public probe</div>
          <h1 class="page-title">{{ payload?.title ?? "Open Node Probe" }}</h1>
          <p class="page-copy">{{ probeDescription }}</p>
        </div>
      </div>

      <v-tooltip text="Refresh probe status">
        <template #activator="{ props }">
          <v-btn
            v-bind="props"
            :loading="loading"
            icon="mdi-refresh"
            variant="text"
            @click="refreshProbe"
          />
        </template>
      </v-tooltip>
    </section>

    <v-alert
      v-if="errorMessage"
      class="status-alert"
      density="comfortable"
      type="error"
      variant="tonal"
    >
      {{ errorMessage }}
    </v-alert>
    <v-alert
      v-if="successMessage"
      class="status-alert"
      density="comfortable"
      type="success"
      variant="tonal"
    >
      {{ successMessage }}
    </v-alert>

    <section class="metric-grid" aria-label="Probe status">
      <v-card
        v-for="tile in metrics"
        :key="tile.label"
        class="metric-card"
        variant="flat"
      >
        <v-icon :color="tile.color" :icon="tile.icon" size="28" />
        <div class="metric-label">{{ tile.label }}</div>
        <div class="metric-value">{{ tile.value }}</div>
        <div class="metric-note">{{ tile.note }}</div>
      </v-card>
    </section>

    <section v-if="showInsightGrid" class="probe-insight-grid" aria-label="Probe insights">
      <v-sheet
        v-if="showRegionOverview"
        class="section-surface probe-insight-panel"
        border
      >
        <div class="section-head compact-head">
          <div>
            <div class="section-title">Regions</div>
            <div class="section-subtitle">{{ regions.length }} public groups</div>
          </div>
          <v-icon color="primary" icon="mdi-map-marker-radius-outline" />
        </div>
        <div class="probe-region-list">
          <button
            v-for="region in regions"
            :key="region.code"
            :class="{ active: regionFilter === region.code }"
            type="button"
            @click="selectRegion(region.code)"
          >
            <span>{{ region.label }}</span>
            <i>
              <b :style="{ width: regionShare(region.total) }" />
            </i>
            <strong>{{ region.online }}/{{ region.total }}</strong>
          </button>
        </div>
      </v-sheet>

      <v-sheet
        v-if="showDailyTrend && dailyTraffic.length > 0"
        class="section-surface probe-insight-panel"
        border
      >
        <div class="section-head compact-head">
          <div>
            <div class="section-title">Daily traffic</div>
            <div class="section-subtitle">{{ formatBytes(currentDailyTraffic) }} today</div>
          </div>
          <v-icon color="warning" icon="mdi-chart-bar" />
        </div>
        <div class="probe-daily-bars">
          <div
            v-for="day in dailyTraffic"
            :key="day.date"
            :title="dailyBarTitle(day)"
            class="probe-day-bar"
          >
            <span>
              <i class="down" :style="{ height: dailyBarHeight(day.downlink) }" />
              <i class="up" :style="{ height: dailyBarHeight(day.uplink) }" />
            </span>
            <small>{{ day.date.slice(5) }}</small>
          </div>
        </div>
      </v-sheet>

      <v-sheet
        v-if="showTrafficHotspots && hotspots.length > 0"
        class="section-surface probe-insight-panel"
        border
      >
        <div class="section-head compact-head">
          <div>
            <div class="section-title">Traffic hotspots</div>
            <div class="section-subtitle">Top live throughput</div>
          </div>
          <v-icon color="info" icon="mdi-chart-timeline-variant-shimmer" />
        </div>
        <div class="probe-hotspot-list">
          <div v-for="row in hotspots" :key="`${row.name}-${row.index}`">
            <span>{{ row.name }}</span>
            <i>
              <b :style="{ width: `${row.share}%` }" />
            </i>
            <strong>{{ formatBytesPerSecond(row.speed) }}</strong>
          </div>
        </div>
      </v-sheet>
    </section>

    <v-sheet class="section-surface" border>
      <div class="section-head">
        <div>
          <div class="section-title">Probe settings</div>
          <div class="section-subtitle">{{ settingsForm.revision }}</div>
        </div>
        <v-chip :color="settingsForm.enabled ? 'success' : 'error'" variant="tonal">
          {{ settingsForm.enabled ? "Enabled" : "Disabled" }}
        </v-chip>
      </div>

      <v-form class="compact-form" @submit.prevent="saveProbeSettings">
        <div class="form-row">
          <v-text-field
            v-model="settingsForm.title"
            density="comfortable"
            label="Title"
            prepend-inner-icon="mdi-format-title"
            variant="outlined"
          />
          <v-text-field
            v-model.number="settingsForm.refresh_interval_sec"
            density="comfortable"
            label="Refresh seconds"
            max="60"
            min="1"
            type="number"
            variant="outlined"
          />
        </div>
        <v-textarea
          v-model="settingsForm.description"
          auto-grow
          density="comfortable"
          label="Description"
          rows="2"
          variant="outlined"
        />
        <div class="form-row">
          <v-text-field
            v-model="settingsForm.logo"
            density="comfortable"
            label="Logo URL"
            prepend-inner-icon="mdi-image-outline"
            variant="outlined"
          />
          <v-text-field
            v-model="settingsForm.theme"
            density="comfortable"
            label="Theme"
            prepend-inner-icon="mdi-palette-outline"
            variant="outlined"
          />
        </div>
        <div class="form-row">
          <v-select
            v-model="settingsForm.color_mode"
            :items="colorModeOptions"
            density="comfortable"
            label="Color mode"
            variant="outlined"
          />
          <v-text-field
            v-model="settingsForm.revision"
            density="comfortable"
            label="Revision"
            prepend-inner-icon="mdi-source-commit"
            variant="outlined"
          />
        </div>
        <div class="probe-toggle-grid">
          <v-switch
            v-model="settingsForm.enabled"
            color="primary"
            density="comfortable"
            hide-details
            label="Enabled"
          />
          <v-switch
            v-model="settingsForm.show_globe"
            color="primary"
            density="comfortable"
            hide-details
            label="Regions"
          />
          <v-switch
            v-model="settingsForm.show_resource_heatmap"
            color="secondary"
            density="comfortable"
            hide-details
            label="System"
          />
          <v-switch
            v-model="settingsForm.show_traffic_quota"
            color="info"
            density="comfortable"
            hide-details
            label="Traffic"
          />
          <v-switch
            v-model="settingsForm.show_health_score"
            color="success"
            density="comfortable"
            hide-details
            label="Health"
          />
          <v-switch
            v-model="settingsForm.show_daily_trend"
            color="warning"
            density="comfortable"
            hide-details
            label="Daily"
          />
          <v-switch
            v-model="settingsForm.show_traffic_hotspots"
            color="info"
            density="comfortable"
            hide-details
            label="Hotspots"
          />
          <v-switch
            v-model="settingsForm.show_traffic_7d"
            color="primary"
            density="comfortable"
            hide-details
            label="7d traffic"
          />
          <v-switch
            v-model="settingsForm.show_renewal_timeline"
            color="secondary"
            density="comfortable"
            hide-details
            label="Renewal"
          />
        </div>
        <div class="settings-action-row">
          <v-btn
            :loading="savingSettings"
            color="primary"
            prepend-icon="mdi-content-save-outline"
            type="submit"
            variant="flat"
          >
            Save settings
          </v-btn>
          <v-btn
            :loading="loading"
            prepend-icon="mdi-refresh"
            variant="tonal"
            @click="refreshProbe"
          >
            Refresh
          </v-btn>
        </div>
      </v-form>
    </v-sheet>

    <v-sheet class="section-surface server-surface" border>
      <div class="section-head">
        <div>
          <div class="section-title">Probe nodes</div>
          <div class="section-subtitle">Public read-only view</div>
        </div>
        <v-progress-circular
          v-if="loading"
          color="primary"
          indeterminate
          size="24"
          width="3"
        />
      </div>

      <div v-if="servers.length > 0" class="probe-filter-row">
        <v-btn-toggle
          v-model="statusFilter"
          class="probe-status-toggle"
          density="comfortable"
          mandatory
          variant="outlined"
        >
          <v-btn
            v-for="option in statusFilterOptions"
            :key="option.value"
            :prepend-icon="option.icon"
            :value="option.value"
            size="small"
          >
            {{ option.title }} {{ option.count }}
          </v-btn>
        </v-btn-toggle>
        <v-select
          v-model="regionFilter"
          :items="regionSelectOptions"
          class="probe-region-select"
          density="comfortable"
          hide-details
          prepend-inner-icon="mdi-map-marker-outline"
          variant="outlined"
        />
        <div class="section-subtitle filter-count">{{ filterCountLabel }}</div>
      </div>

      <v-table v-if="visibleServers.length > 0" class="server-table" density="comfortable">
        <thead>
          <tr>
            <th>Name</th>
            <th>Status</th>
            <th v-if="showSystemColumn">System</th>
            <th>Latency</th>
            <th v-if="showTrafficColumn">Traffic</th>
            <th v-if="showRenewalColumn">Renewal</th>
            <th class="number-cell">Up</th>
            <th class="number-cell">Down</th>
          </tr>
        </thead>
        <tbody>
          <tr
            v-for="(server, index) in visibleServers"
            :key="`${displayName(server, index)}-${index}`"
            :class="rowClass(server)"
          >
            <td>
              <div class="server-name">{{ displayName(server, index) }}</div>
              <div class="server-subline">{{ regionSummary(server) }}</div>
              <div class="server-subline">{{ providerSummary(server) }}</div>
            </td>
            <td>
              <v-chip
                :color="statusColor(server)"
                :prepend-icon="statusIcon(server)"
                density="comfortable"
                size="small"
                variant="tonal"
              >
                {{ statusLabel(server) }}
              </v-chip>
              <div class="server-subline">{{ peerSummary(server) }}</div>
              <v-tooltip v-if="showHealthScore" :text="healthHint(server)">
                <template #activator="{ props }">
                  <v-chip
                    v-bind="props"
                    :color="healthFor(server).tone"
                    class="health-chip"
                    density="compact"
                    size="x-small"
                    variant="tonal"
                  >
                    {{ healthFor(server).score }} {{ healthFor(server).label }}
                  </v-chip>
                </template>
              </v-tooltip>
            </td>
            <td v-if="showSystemColumn" class="telemetry-cell">
              <div class="server-name">{{ systemSummary(server) }}</div>
              <div class="server-subline">
                {{ server.os || "Unknown OS" }} / {{ server.loadavg || "No loadavg" }}
              </div>
            </td>
            <td class="telemetry-cell">
              <div class="server-name">{{ latencySummary(server) }}</div>
              <div v-if="latencyBuckets(server).length > 0" class="probe-latency-bars">
                <span
                  v-for="(bucket, bucketIndex) in latencyBuckets(server)"
                  :key="bucketIndex"
                  :class="`is-${bucket.level}`"
                  :title="latencyBucketTitle(bucket)"
                />
              </div>
            </td>
            <td v-if="showTrafficColumn" class="telemetry-cell">
              <div class="server-name">{{ trafficSummary(server) }}</div>
              <div v-if="server.traffic_limit" class="probe-quota-meter">
                <i :style="{ width: quotaWidth(server) }" />
              </div>
              <div v-if="showSevenDayTraffic" class="server-subline">
                {{ sevenDayTrafficSummary(server) }}
              </div>
              <div v-if="!showRenewalColumn" class="server-subline">
                {{ renewalSummary(server) }}
              </div>
            </td>
            <td v-if="showRenewalColumn" class="telemetry-cell">
              <v-chip
                :color="renewalTone(server)"
                density="compact"
                size="small"
                variant="tonal"
              >
                {{ renewalCountdown(server) }}
              </v-chip>
              <div class="server-subline">{{ renewalSummary(server) }}</div>
              <div class="server-subline">
                CNY {{ server.renewal_price_cny ?? "n/a" }}
              </div>
            </td>
            <td class="number-cell">{{ formatBytesPerSecond(server.upload_speed ?? 0) }}</td>
            <td class="number-cell">{{ formatBytesPerSecond(server.download_speed ?? 0) }}</td>
          </tr>
        </tbody>
      </v-table>

      <div v-else-if="servers.length === 0" class="empty-state">
        <v-icon color="secondary" icon="mdi-chart-line-variant" size="36" />
        <div>No public probe nodes yet.</div>
      </div>
      <div v-else class="empty-state">
        <v-icon color="secondary" icon="mdi-filter-off-outline" size="36" />
        <div>No nodes match the current filters.</div>
      </div>
    </v-sheet>
  </div>
</template>
